#!/bin/sh

USE_CASES=""
MISSING_LIC=""
SNIF=0
DIAG=0

SNIF_LIC="NIOT-S-LIC-SNIF"
DIAG_LIC="NIOT-S-LIC-DIAG"

/usr/sbin/check_license NIOT-S-LIC-SNIF
if [ $? -eq 0 ]; then
  echo "found NIOT-S-LIC-SNIF"
  USE_CASES="${USE_CASES}opcua,nodered,"
  SNIF=1
fi

/usr/sbin/check_license NIOT-S-LIC-DIAG
if [ $? -eq 0 ]; then
  echo "found NIOT-S-LIC-DIAG"
  USE_CASES="${USE_CASES}diagserver,"
  DIAG=1
fi

if [ "$DIAG" == 1 ] && [ "$SNIF" == 1 ]; then
  echo "state=OK" > /opt/nasa/config/operation-settings/nasa-state-info.conf
elif [ "$DIAG" == 0 ] && [ "$SNIF" == 1 ]; then
  echo "state=Warning=Diag License not found ($DIAG_LIC)." > /opt/nasa/config/operation-settings/nasa-state-info.conf
elif [ "$DIAG" == 1 ] && [ "$SNIF" == 0 ]; then
  echo "state=Warning=Sniffer License not found ($SNIF_LIC)." > /opt/nasa/config/operation-settings/nasa-state-info.conf
else
  echo "state=Failed=No License found. Missing Licenses: $SNIF_LIC, $DIAG_LIC" > /opt/nasa/config/operation-settings/nasa-state-info.conf
fi

if [ -z $USE_CASES ]; then
  echo "STANDALONE_ARGS=\"\"" > /opt/nasa/config/operation-settings/standalone-args
  echo "no valid license found"
else
  echo "STANDALONE_ARGS=\"--usecase=${USE_CASES}\"" > /opt/nasa/config/operation-settings/standalone-args
fi
