#!/bin/sh
for service in nasa-standalone nasa-remote-access-server nasa-netanablocker; do
  systemctl stop $service
  systemctl disable $service
done

/usr/sbin/check_license NIOT-S-LIC-SNIF
if [ $? -ne 0 ]; then
  echo "no valid license found"
  systemctl start nasa-netanablocker
  systemctl enable nasa-netanablocker
  echo "state=Failed=Sniffer license not found (NIOT-S-LIC-SNIF)" > /opt/nasa/config/operation-settings/nasa-state-info.conf
else 
  echo "state=OK" > /opt/nasa/config/operation-settings/nasa-state-info.conf
fi

SCRIPTDIR=`dirname $0`
echo "mode=docker" > $SCRIPTDIR/../config/operation-settings/nasa-mode.conf
