#!/bin/sh

case $1 in
  stop)
    for service in nasa-netanablocker nasa-remote-access-server nasa-standalone; do
        systemctl stop ${service}
        systemctl disable ${service}
    done
    ;;

  start)
      # Get configured mode and switch accordingly
    jsonactmode=$(/opt/nasa/scripts/nasa-get-mode)
    actmode=$(python -c "import json; s=$jsonactmode; print s['mode']")
    # echo $actmode
    if [ "${actmode}" = "config mode" ]; then
      # Configuration mode
      /opt/nasa/scripts/nasa-enable-cfg-mode
    elif [ "${actmode}" = "operational mode" ]; then
      # Operational Mode
      /opt/nasa/scripts/nasa-enable-op-mode
    elif [ "${actmode}" = "docker mode" ]; then
      # Docker Mode
      /opt/nasa/scripts/nasa-enable-docker-mode
    else
      # Default to operational mode
      /opt/nasa/scripts/nasa-enable-op-mode
    fi
    ;;
  *)
    echo '{"error":"Invalid option '"${1}"'"}'
    exit -1
    ;;
esac
