#   github.com/AlecAivazis/survey/v2 v2.3.7
# [1] git ls-remote https://github.com/go-survey/survey.git fa37277e6394c29db7bcc94062cb30cd7785a126
SRCREV_v2="fa37277e6394c29db7bcc94062cb30cd7785a126"
SRC_URI += "git://github.com/go-survey/survey.git;name=v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AlecAivazis/survey/v2"

#   github.com/Microsoft/go-winio v0.6.1
# [1] git ls-remote https://github.com/microsoft/go-winio.git 070c828abb873da9e71c7247740253b50f7cf049
SRCREV_go-winio="070c828abb873da9e71c7247740253b50f7cf049"
SRC_URI += "git://github.com/microsoft/go-winio.git;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

#   github.com/buger/goterm v1.0.4
# [1] git ls-remote https://github.com/buger/goterm.git a73545aae7d693f786ce4cc687460efca4845f31
SRCREV_goterm="a73545aae7d693f786ce4cc687460efca4845f31"
SRC_URI += "git://github.com/buger/goterm.git;name=goterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/buger/goterm"

#   github.com/compose-spec/compose-go v1.16.0
# [1] git ls-remote https://github.com/compose-spec/compose-go.git a3837e2378b874f1f6a88e331b231235811c0271
SRCREV_compose-go="a3837e2378b874f1f6a88e331b231235811c0271"
SRC_URI += "git://github.com/compose-spec/compose-go.git;name=compose-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/compose-spec/compose-go"

#   github.com/containerd/console v1.0.3
# [1] git ls-remote https://github.com/containerd/console.git 060a791de16aeb90b3bb4dcd78dfec3ca45fa5df
SRCREV_console="060a791de16aeb90b3bb4dcd78dfec3ca45fa5df"
SRC_URI += "git://github.com/containerd/console.git;name=console;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/console"

#   github.com/containerd/containerd v1.7.2
# [1] git ls-remote https://github.com/containerd/containerd.git d6d1c83955ed62e2833bd470453e0449a3164e7f
SRCREV_containerd="d6d1c83955ed62e2833bd470453e0449a3164e7f"
SRC_URI += "git://github.com/containerd/containerd.git;name=containerd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/containerd"

#   github.com/laurazard/godog v0.0.0-20220922095256-4c4b17abdae7
# [1] git ls-remote https://github.com/laurazard/godog.git 4c4b17abdae7fd4f9d35cfe391ca65d172b092e3
SRCREV_godog="4c4b17abdae7fd4f9d35cfe391ca65d172b092e3"
SRC_URI += "git://github.com/laurazard/godog.git;name=godog;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/laurazard/godog"

#   github.com/distribution/distribution/v3 v3.0.0-20230601133803-97b1d649c493
# [1] git ls-remote https://github.com/distribution/distribution.git 97b1d649c4938d0f608d96454d6a8326b1f96acd
SRCREV_v3="97b1d649c4938d0f608d96454d6a8326b1f96acd"
SRC_URI += "git://github.com/distribution/distribution.git;name=v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/distribution/distribution/v3"

#   github.com/docker/buildx v0.11.1
# [1] git ls-remote https://github.com/docker/buildx.git b4df08551fb12eb2ed17d3d9c3977ca0a903415a
SRCREV_buildx="b4df08551fb12eb2ed17d3d9c3977ca0a903415a"
SRC_URI += "git://github.com/docker/buildx.git;name=buildx;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/buildx"

#   github.com/docker/cli v24.0.2+incompatible
# [1] git ls-remote https://github.com/docker/cli.git d90d05a320d6db7398e1114bd452c3e6e57ffc10
SRCREV_cli="d90d05a320d6db7398e1114bd452c3e6e57ffc10"
SRC_URI += "git://github.com/docker/cli.git;name=cli;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli"

#   github.com/docker/cli-docs-tool v0.6.0
# [1] git ls-remote https://github.com/docker/cli-docs-tool.git 5cb124c70a1f08a8fcbffad5059b4b5b01123124
SRCREV_cli-docs-tool="5cb124c70a1f08a8fcbffad5059b4b5b01123124"
SRC_URI += "git://github.com/docker/cli-docs-tool.git;name=cli-docs-tool;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli-docs-tool"

#   github.com/docker/docker v24.0.4+incompatible
# [1] git ls-remote https://github.com/moby/moby.git 967a54a72a4e41a6b250aca7049cac3ab185460a
SRCREV_docker="967a54a72a4e41a6b250aca7049cac3ab185460a"
SRC_URI += "git://github.com/moby/moby.git;name=docker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker"

#   github.com/docker/go-connections v0.4.0
# [1] git ls-remote https://github.com/docker/go-connections.git 7395e3f8aa162843a74ed6d48e79627d9792ac55
SRCREV_go-connections="7395e3f8aa162843a74ed6d48e79627d9792ac55"
SRC_URI += "git://github.com/docker/go-connections.git;name=go-connections;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-connections"

#   github.com/docker/go-units v0.5.0
# [1] git ls-remote https://github.com/docker/go-units.git 1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8
SRCREV_go-units="1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8"
SRC_URI += "git://github.com/docker/go-units.git;name=go-units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-units"

#   github.com/fsnotify/fsevents v0.1.1
# [1] git ls-remote https://github.com/fsnotify/fsevents.git f721bd2b045774a566e8f7f5fa2a9985e04c875d
SRCREV_fsevents="f721bd2b045774a566e8f7f5fa2a9985e04c875d"
SRC_URI += "git://github.com/fsnotify/fsevents.git;name=fsevents;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fsnotify/fsevents"

#   github.com/golang/mock v1.6.0
# [1] git ls-remote https://github.com/golang/mock.git aba2ff9a6844d5e3289e8472d3217d5b3090f083
SRCREV_mock="aba2ff9a6844d5e3289e8472d3217d5b3090f083"
SRC_URI += "git://github.com/golang/mock.git;name=mock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/mock"

#   github.com/hashicorp/go-multierror v1.1.1
# [1] git ls-remote https://github.com/hashicorp/go-multierror.git 9974e9ec57696378079ecc3accd3d6f29401b3a0
SRCREV_go-multierror="9974e9ec57696378079ecc3accd3d6f29401b3a0"
SRC_URI += "git://github.com/hashicorp/go-multierror.git;name=go-multierror;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-multierror"

#   github.com/hashicorp/go-version v1.6.0
# [1] git ls-remote https://github.com/hashicorp/go-version.git 78d058c5618891f74d604bd15356fca690b64d8a
SRCREV_go-version="78d058c5618891f74d604bd15356fca690b64d8a"
SRC_URI += "git://github.com/hashicorp/go-version.git;name=go-version;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-version"

#   github.com/jonboulle/clockwork v0.4.0
# [1] git ls-remote https://github.com/jonboulle/clockwork.git 3fb70b88bf9d29704406d8de245cdf3972637984
SRCREV_clockwork="3fb70b88bf9d29704406d8de245cdf3972637984"
SRC_URI += "git://github.com/jonboulle/clockwork.git;name=clockwork;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jonboulle/clockwork"

#   github.com/mattn/go-shellwords v1.0.12
# [1] git ls-remote https://github.com/mattn/go-shellwords.git 973b9d5391598d4ee601db46fa32f6e186a356ac
SRCREV_go-shellwords="973b9d5391598d4ee601db46fa32f6e186a356ac"
SRC_URI += "git://github.com/mattn/go-shellwords.git;name=go-shellwords;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-shellwords"

#   github.com/mitchellh/mapstructure v1.5.0
# [1] git ls-remote https://github.com/mitchellh/mapstructure.git ab69d8d93410fce4361f4912bb1ff88110a81311
SRCREV_mapstructure="ab69d8d93410fce4361f4912bb1ff88110a81311"
SRC_URI += "git://github.com/mitchellh/mapstructure.git;name=mapstructure;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/mapstructure"

#   github.com/moby/buildkit v0.11.0-rc3.0.20230609092854-67a08623b95a
# [1] git ls-remote https://github.com/moby/buildkit.git 67a08623b95a85486f5122ee21af095c18ced425
SRCREV_buildkit="67a08623b95a85486f5122ee21af095c18ced425"
SRC_URI += "git://github.com/moby/buildkit.git;name=buildkit;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/buildkit"

#   github.com/moby/patternmatcher v0.5.0
# [1] git ls-remote https://github.com/moby/patternmatcher.git a3db21c2e3f8fdc248f502e96371defcba6566dc
SRCREV_patternmatcher="a3db21c2e3f8fdc248f502e96371defcba6566dc"
SRC_URI += "git://github.com/moby/patternmatcher.git;name=patternmatcher;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/patternmatcher"

#   github.com/moby/term v0.5.0
# [1] git ls-remote https://github.com/moby/term.git 29d1ed41b766a40d15b5bac3b9ab1e07f961604d
SRCREV_term="29d1ed41b766a40d15b5bac3b9ab1e07f961604d"
SRC_URI += "git://github.com/moby/term.git;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/term"

#   github.com/morikuni/aec v1.0.0
# [1] git ls-remote https://github.com/morikuni/aec.git 39771216ff4c63d11f5e604076f9c45e8be1067b
SRCREV_aec="39771216ff4c63d11f5e604076f9c45e8be1067b"
SRC_URI += "git://github.com/morikuni/aec.git;name=aec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/morikuni/aec"

#   github.com/opencontainers/go-digest v1.0.0
# [1] git ls-remote https://github.com/opencontainers/go-digest.git 4a41a1fddd8208cc64f911e551a7f361716f8ae5
SRCREV_go-digest="4a41a1fddd8208cc64f911e551a7f361716f8ae5"
SRC_URI += "git://github.com/opencontainers/go-digest.git;name=go-digest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/go-digest"

#   github.com/opencontainers/image-spec v1.1.0-rc4
# [1] git ls-remote https://github.com/opencontainers/image-spec.git 454f83f7a1db9a427e41917fee20f82eb01428e7
SRCREV_image-spec="454f83f7a1db9a427e41917fee20f82eb01428e7"
SRC_URI += "git://github.com/opencontainers/image-spec.git;name=image-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/image-spec"

#   github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors.git 614d223910a179a466c1767a985424175c39b465
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors.git;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

#   github.com/sirupsen/logrus v1.9.3
# [1] git ls-remote https://github.com/sirupsen/logrus.git d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd
SRCREV_logrus="d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd"
SRC_URI += "git://github.com/sirupsen/logrus.git;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

#   github.com/spf13/cobra v1.7.0
# [1] git ls-remote https://github.com/spf13/cobra.git 4dd4b25de38418174a6e859e8a32eaccca32dccc
SRCREV_cobra="4dd4b25de38418174a6e859e8a32eaccca32dccc"
SRC_URI += "git://github.com/spf13/cobra.git;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

#   github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag.git 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag.git;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

#   github.com/stretchr/testify v1.8.4
# [1] git ls-remote https://github.com/stretchr/testify.git f97607b89807936ac4ff96748d766cf4b9711f78
SRCREV_testify="f97607b89807936ac4ff96748d766cf4b9711f78"
SRC_URI += "git://github.com/stretchr/testify.git;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

#   github.com/theupdateframework/notary v0.7.0
# [1] git ls-remote https://github.com/notaryproject/notary.git 9d266b20442b87d5faa2d4f5ab19604c79cd4c10
SRCREV_notary="9d266b20442b87d5faa2d4f5ab19604c79cd4c10"
SRC_URI += "git://github.com/notaryproject/notary.git;name=notary;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/theupdateframework/notary"

#   github.com/tilt-dev/fsnotify v1.4.8-0.20220602155310-fff9c274a375
# [1] git ls-remote https://github.com/tilt-dev/fsnotify.git fff9c274a375301ae46812f257aa68393790c45b
SRCREV_fsnotify="fff9c274a375301ae46812f257aa68393790c45b"
SRC_URI += "git://github.com/tilt-dev/fsnotify.git;name=fsnotify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tilt-dev/fsnotify"

#   go.opentelemetry.io/otel v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 65f9fb5a2a6114def10d36d063df772d1fb43010
SRCREV_otel="65f9fb5a2a6114def10d36d063df772d1fb43010"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otel;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_otlptrace="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptrace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_otlptracegrpc="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptracegrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"

#   go.opentelemetry.io/otel/sdk v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_sdk="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=sdk;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/sdk"

#   go.opentelemetry.io/otel/trace v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_trace="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=trace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/trace"

#   go.uber.org/goleak v1.2.1
# [1] git ls-remote https://github.com/uber-go/goleak 3ad786091b1f249ead9fefc411f508ac074f9852
SRCREV_goleak="3ad786091b1f249ead9fefc411f508ac074f9852"
SRC_URI += "git://github.com/uber-go/goleak;name=goleak;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/goleak"

#   golang.org/x/sync v0.3.0
# [1] git ls-remote https://go.googlesource.com/sync 93782cc822b6b554cb7df40332fd010f0473cbc8
SRCREV_sync="93782cc822b6b554cb7df40332fd010f0473cbc8"
SRC_URI += "git://go.googlesource.com/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

#   google.golang.org/grpc v1.56.2
# [1] git ls-remote https://github.com/grpc/grpc-go faab8736bf73291f92b867d5dae31c927d53d508
SRCREV_grpc="faab8736bf73291f92b867d5dae31c927d53d508"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/grpc"

#   gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2 7649d4548cb53a614db133b2a8ac1f31859dda8c
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

#   gotest.tools/v3 v3.5.0
# [1] git ls-remote https://github.com/gotestyourself/gotest.tools a80f057529047c44e1a85d0d017b200787e537e0
SRCREV_v3v3_5_0="a80f057529047c44e1a85d0d017b200787e537e0"
SRC_URI += "git://github.com/gotestyourself/gotest.tools;name=v3v3_5_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gotest.tools/v3"

#   github.com/AdaLogics/go-fuzz-headers v0.0.0-20230106234847-43070de90fa1
# [1] git ls-remote https://github.com/AdaLogics/go-fuzz-headers.git 43070de90fa134c9ea55cd6de4308a2ae59658d3
SRCREV_go-fuzz-headers="43070de90fa134c9ea55cd6de4308a2ae59658d3"
SRC_URI += "git://github.com/AdaLogics/go-fuzz-headers.git;name=go-fuzz-headers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AdaLogics/go-fuzz-headers"

#   github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
# [1] git ls-remote https://github.com/Azure/go-ansiterm.git d185dfc1b5a126116ea5a19e148e29d16b4574c9
SRCREV_go-ansiterm="d185dfc1b5a126116ea5a19e148e29d16b4574c9"
SRC_URI += "git://github.com/Azure/go-ansiterm.git;name=go-ansiterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Azure/go-ansiterm"

#   github.com/Masterminds/semver/v3 v3.2.1
# [1] git ls-remote https://github.com/Masterminds/semver.git 95a60f04f6ef4fccbc26300575409658fad9616e
SRCREV_v3v3_2_1="95a60f04f6ef4fccbc26300575409658fad9616e"
SRC_URI += "git://github.com/Masterminds/semver.git;name=v3v3_2_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Masterminds/semver/v3"

#   github.com/aws/aws-sdk-go-v2 v1.17.6
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git c41faa945b100a9d8d577c0976fbf4138e7427e7
SRCREV_aws-sdk-go-v2="c41faa945b100a9d8d577c0976fbf4138e7427e7"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=aws-sdk-go-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2"

#   github.com/aws/aws-sdk-go-v2/config v1.18.16
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_config="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=config;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/config"

#   github.com/aws/aws-sdk-go-v2/credentials v1.13.16
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_credentials="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=credentials;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/credentials"

#   github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_imds="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=imds;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/feature/ec2/imds"

#   github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.30
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_configsources="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=configsources;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/configsources"

#   github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git b23becc33b6fa4cbd0c1996eb66957372c0246a0
SRCREV_v2v2_4_24="b23becc33b6fa4cbd0c1996eb66957372c0246a0"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=v2v2_4_24;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"

#   github.com/aws/aws-sdk-go-v2/internal/ini v1.3.31
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_ini="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=ini;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/ini"

#   github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_presigned-url="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=presigned-url;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"

#   github.com/aws/aws-sdk-go-v2/service/sso v1.12.5
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_sso="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=sso;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/sso"

#   github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.5
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_ssooidc="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=ssooidc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/ssooidc"

#   github.com/aws/aws-sdk-go-v2/service/sts v1.18.6
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_sts="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=sts;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/sts"

#   github.com/aws/smithy-go v1.13.5
# [1] git ls-remote https://github.com/aws/smithy-go.git 6178fd4e871aa9cbcfce9ccf96d5e39854a9751e
SRCREV_smithy-go="6178fd4e871aa9cbcfce9ccf96d5e39854a9751e"
SRC_URI += "git://github.com/aws/smithy-go.git;name=smithy-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/smithy-go"

#   github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks.git c49ff274687222a7373c4cd83578f1065cf3e143
SRCREV_perks="c49ff274687222a7373c4cd83578f1065cf3e143"
SRC_URI += "git://github.com/beorn7/perks.git;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

#   github.com/bugsnag/bugsnag-go v1.5.0
# [1] git ls-remote https://github.com/bugsnag/bugsnag-go.git d5b63da7e1f93d83e3980e5ab2bf33179bad7b2a
SRCREV_bugsnag-go="d5b63da7e1f93d83e3980e5ab2bf33179bad7b2a"
SRC_URI += "git://github.com/bugsnag/bugsnag-go.git;name=bugsnag-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/bugsnag/bugsnag-go"

#   github.com/cenkalti/backoff/v4 v4.2.0
# [1] git ls-remote https://github.com/cenkalti/backoff.git e5c9822f4eaffe6a2abac94d7fbf85380dd629a8
SRCREV_v4="e5c9822f4eaffe6a2abac94d7fbf85380dd629a8"
SRC_URI += "git://github.com/cenkalti/backoff.git;name=v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cenkalti/backoff/v4"

#   github.com/cespare/xxhash/v2 v2.2.0
# [1] git ls-remote https://github.com/cespare/xxhash.git 50472e8238a5564de4b2f10531e8b6d1529876e8
SRCREV_v2v2_2_0="50472e8238a5564de4b2f10531e8b6d1529876e8"
SRC_URI += "git://github.com/cespare/xxhash.git;name=v2v2_2_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

#   github.com/cloudflare/cfssl v1.6.4
# [1] git ls-remote https://github.com/cloudflare/cfssl.git 631f951bb32c400d4ed8a5b62b4668cd4d4acb45
SRCREV_cfssl="631f951bb32c400d4ed8a5b62b4668cd4d4acb45"
SRC_URI += "git://github.com/cloudflare/cfssl.git;name=cfssl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cloudflare/cfssl"

#   github.com/containerd/continuity v0.4.1
# [1] git ls-remote https://github.com/containerd/continuity.git 2375d88ea137dd01bd9b2eaf5ac8c2c427768821
SRCREV_continuity="2375d88ea137dd01bd9b2eaf5ac8c2c427768821"
SRC_URI += "git://github.com/containerd/continuity.git;name=continuity;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/continuity"

#   github.com/containerd/ttrpc v1.2.2
# [1] git ls-remote https://github.com/containerd/ttrpc.git ac26f8cbea1c440d451dd19a4a1b847fd073f3c3
SRCREV_ttrpc="ac26f8cbea1c440d451dd19a4a1b847fd073f3c3"
SRC_URI += "git://github.com/containerd/ttrpc.git;name=ttrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/ttrpc"

#   github.com/containerd/typeurl/v2 v2.1.1
# [1] git ls-remote https://github.com/containerd/typeurl.git 7ef6316b771f959cbb208b229e3423a466947df3
SRCREV_v2v2_1_1="7ef6316b771f959cbb208b229e3423a466947df3"
SRC_URI += "git://github.com/containerd/typeurl.git;name=v2v2_1_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/typeurl/v2"

#   github.com/cucumber/gherkin-go/v19 v19.0.3
# [1] git ls-remote https://github.com/cucumber/gherkin-go.git 9f5f52dff3eb053e4964e1dc36bcd5d359006238
SRCREV_v19="9f5f52dff3eb053e4964e1dc36bcd5d359006238"
SRC_URI += "git://github.com/cucumber/gherkin-go.git;name=v19;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cucumber/gherkin-go/v19"

#   github.com/cucumber/messages-go/v16 v16.0.1
# [1] git ls-remote https://github.com/cucumber/messages-go.git dbd338d7e762f11b5aa2b5e6fa529a727177b82a
SRCREV_v16="dbd338d7e762f11b5aa2b5e6fa529a727177b82a"
SRC_URI += "git://github.com/cucumber/messages-go.git;name=v16;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cucumber/messages-go/v16"

#   github.com/cyphar/filepath-securejoin v0.2.3
# [1] git ls-remote https://github.com/cyphar/filepath-securejoin.git a89baba1e4f44c5512e245cbd156de1293d6185a
SRCREV_filepath-securejoin="a89baba1e4f44c5512e245cbd156de1293d6185a"
SRC_URI += "git://github.com/cyphar/filepath-securejoin.git;name=filepath-securejoin;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cyphar/filepath-securejoin"

#   github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew.git 152484fe5c9ff65d013f0f372d748c03e8749e6d
SRCREV_go-spew="152484fe5c9ff65d013f0f372d748c03e8749e6d"
SRC_URI += "git://github.com/davecgh/go-spew.git;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

#   github.com/docker/distribution v2.8.2+incompatible
# [1] git ls-remote https://github.com/distribution/distribution.git 13b6286808a261e3313429b35f0ff8827ae585d9
SRCREV_distribution="13b6286808a261e3313429b35f0ff8827ae585d9"
SRC_URI += "git://github.com/distribution/distribution.git;name=distribution;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/distribution"

#   github.com/docker/docker-credential-helpers v0.7.0
# [1] git ls-remote https://github.com/docker/docker-credential-helpers.git ac5992b5f4756fc0398a7d0c93c609e624368bde
SRCREV_docker-credential-helpers="ac5992b5f4756fc0398a7d0c93c609e624368bde"
SRC_URI += "git://github.com/docker/docker-credential-helpers.git;name=docker-credential-helpers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker-credential-helpers"

#   github.com/docker/go v1.5.1-1.0.20160303222718-d30aec9fd63c
# [1] git ls-remote https://github.com/docker/go.git d30aec9fd63c35133f8f79c3412ad91a3b08be06
SRCREV_go="d30aec9fd63c35133f8f79c3412ad91a3b08be06"
SRC_URI += "git://github.com/docker/go.git;name=go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go"

#   github.com/docker/go-metrics v0.0.1
# [1] git ls-remote https://github.com/docker/go-metrics.git b619b3592b65de4f087d9f16863a7e6ff905973c
SRCREV_go-metrics="b619b3592b65de4f087d9f16863a7e6ff905973c"
SRC_URI += "git://github.com/docker/go-metrics.git;name=go-metrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-metrics"

#   github.com/emicklei/go-restful/v3 v3.10.1
# [1] git ls-remote https://github.com/emicklei/go-restful.git 0927716e5613277c3010149357f37f79151255c6
SRCREV_v3v3_10_1="0927716e5613277c3010149357f37f79151255c6"
SRC_URI += "git://github.com/emicklei/go-restful.git;name=v3v3_10_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/emicklei/go-restful/v3"

#   github.com/felixge/httpsnoop v1.0.3
# [1] git ls-remote https://github.com/felixge/httpsnoop.git ef9fc62cdc3cc5abc33d6018fe1324890bb48145
SRCREV_httpsnoop="ef9fc62cdc3cc5abc33d6018fe1324890bb48145"
SRC_URI += "git://github.com/felixge/httpsnoop.git;name=httpsnoop;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/felixge/httpsnoop"

#   github.com/fvbommel/sortorder v1.0.2
# [1] git ls-remote https://github.com/fvbommel/sortorder.git 26fad50c6b32a3064c09ed089865c16f2f3615f6
SRCREV_sortorder="26fad50c6b32a3064c09ed089865c16f2f3615f6"
SRC_URI += "git://github.com/fvbommel/sortorder.git;name=sortorder;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fvbommel/sortorder"

#   github.com/go-logr/logr v1.2.4
# [1] git ls-remote https://github.com/go-logr/logr.git 4da5305ff29a64c62f54ad43ebbfcb5e1b015fb2
SRCREV_logr="4da5305ff29a64c62f54ad43ebbfcb5e1b015fb2"
SRC_URI += "git://github.com/go-logr/logr.git;name=logr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/logr"

#   github.com/go-logr/stdr v1.2.2
# [1] git ls-remote https://github.com/go-logr/stdr.git 521af2addfa7c81c8a65d0e85ed34bb6bb6dc262
SRCREV_stdr="521af2addfa7c81c8a65d0e85ed34bb6bb6dc262"
SRC_URI += "git://github.com/go-logr/stdr.git;name=stdr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/stdr"

#   github.com/go-openapi/jsonpointer v0.19.5
# [1] git ls-remote https://github.com/go-openapi/jsonpointer.git a48280f97959fc230ba72550e0a7e7e49d321e1d
SRCREV_jsonpointer="a48280f97959fc230ba72550e0a7e7e49d321e1d"
SRC_URI += "git://github.com/go-openapi/jsonpointer.git;name=jsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonpointer"

#   github.com/go-openapi/jsonreference v0.20.0
# [1] git ls-remote https://github.com/go-openapi/jsonreference.git 5f9ac7dd3cfc5644a4ee6ffa6a90de4a7dc6acf7
SRCREV_jsonreference="5f9ac7dd3cfc5644a4ee6ffa6a90de4a7dc6acf7"
SRC_URI += "git://github.com/go-openapi/jsonreference.git;name=jsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonreference"

#   github.com/go-openapi/swag v0.19.14
# [1] git ls-remote https://github.com/go-openapi/swag.git c78fa6719bc3d4b977d19a09064feda1c07571af
SRCREV_swag="c78fa6719bc3d4b977d19a09064feda1c07571af"
SRC_URI += "git://github.com/go-openapi/swag.git;name=swag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/swag"

#   github.com/gofrs/flock v0.8.1
# [1] git ls-remote https://github.com/gofrs/flock.git a14e9f39bdc9c4be4c0ccddb25b72bbc9670c429
SRCREV_flock="a14e9f39bdc9c4be4c0ccddb25b72bbc9670c429"
SRC_URI += "git://github.com/gofrs/flock.git;name=flock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gofrs/flock"

#   github.com/gofrs/uuid v4.2.0+incompatible
# [1] git ls-remote https://github.com/gofrs/uuid.git 0c84a43ce25087b7041833685982950a65630d28
SRCREV_uuid="0c84a43ce25087b7041833685982950a65630d28"
SRC_URI += "git://github.com/gofrs/uuid.git;name=uuid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gofrs/uuid"

#   github.com/gogo/googleapis v1.4.1
# [1] git ls-remote https://github.com/gogo/googleapis.git 1f0e43f50bc0606e385ffae1bc80b5b231dcd042
SRCREV_googleapis="1f0e43f50bc0606e385ffae1bc80b5b231dcd042"
SRC_URI += "git://github.com/gogo/googleapis.git;name=googleapis;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/googleapis"

#   github.com/gogo/protobuf v1.3.2
# [1] git ls-remote https://github.com/gogo/protobuf.git b03c65ea87cdc3521ede29f62fe3ce239267c1bc
SRCREV_protobuf="b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf.git;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/protobuf"

#   github.com/golang/protobuf v1.5.3
# [1] git ls-remote https://github.com/golang/protobuf.git 5d5e8c018a13017f9d5b8bf4fad64aaa42a87308
SRCREV_protobufv1_5_3="5d5e8c018a13017f9d5b8bf4fad64aaa42a87308"
SRC_URI += "git://github.com/golang/protobuf.git;name=protobufv1_5_3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

#   github.com/google/gnostic v0.5.7-v3refs
# [1] git ls-remote https://github.com/google/gnostic.git b49832d97d25b6a41cbe34ea12257924a934eeee
SRCREV_gnostic="b49832d97d25b6a41cbe34ea12257924a934eeee"
SRC_URI += "git://github.com/google/gnostic.git;name=gnostic;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gnostic"

#   github.com/google/go-cmp v0.5.9
# [1] git ls-remote https://github.com/google/go-cmp.git a97318bf6562f2ed2632c5f985db51b1bc5bdcd0
SRCREV_go-cmp="a97318bf6562f2ed2632c5f985db51b1bc5bdcd0"
SRC_URI += "git://github.com/google/go-cmp.git;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

#   github.com/google/gofuzz v1.2.0
# [1] git ls-remote https://github.com/google/gofuzz.git 41febe7ec24d8c0e442e940f3f15ee4e8511c447
SRCREV_gofuzz="41febe7ec24d8c0e442e940f3f15ee4e8511c447"
SRC_URI += "git://github.com/google/gofuzz.git;name=gofuzz;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gofuzz"

#   github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
# [1] git ls-remote https://github.com/google/shlex.git e7afc7fbc51079733e9468cdfd1efcd7d196cd1d
SRCREV_shlex="e7afc7fbc51079733e9468cdfd1efcd7d196cd1d"
SRC_URI += "git://github.com/google/shlex.git;name=shlex;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/shlex"

#   github.com/gorilla/mux v1.8.0
# [1] git ls-remote https://github.com/gorilla/mux.git 98cb6bf42e086f6af920b965c38cacc07402d51b
SRCREV_mux="98cb6bf42e086f6af920b965c38cacc07402d51b"
SRC_URI += "git://github.com/gorilla/mux.git;name=mux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/mux"

#   github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
# [1] git ls-remote https://github.com/grpc-ecosystem/go-grpc-middleware.git df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd
SRCREV_go-grpc-middleware="df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd"
SRC_URI += "git://github.com/grpc-ecosystem/go-grpc-middleware.git;name=go-grpc-middleware;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/go-grpc-middleware"

#   github.com/grpc-ecosystem/grpc-gateway/v2 v2.11.3
# [1] git ls-remote https://github.com/grpc-ecosystem/grpc-gateway.git 0197faf8b072910084edd1209aa2ac51833b895c
SRCREV_v2v2_11_3="0197faf8b072910084edd1209aa2ac51833b895c"
SRC_URI += "git://github.com/grpc-ecosystem/grpc-gateway.git;name=v2v2_11_3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/grpc-gateway/v2"

#   github.com/hashicorp/errwrap v1.1.0
# [1] git ls-remote https://github.com/hashicorp/errwrap.git 7b00e5db719c64d14dd0caaacbd13e76254d02c0
SRCREV_errwrap="7b00e5db719c64d14dd0caaacbd13e76254d02c0"
SRC_URI += "git://github.com/hashicorp/errwrap.git;name=errwrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/errwrap"

#   github.com/hashicorp/go-immutable-radix v1.3.1
# [1] git ls-remote https://github.com/hashicorp/go-immutable-radix.git 49d1d02c49a783de548d1ba8ae8fde466a20b9e6
SRCREV_go-immutable-radix="49d1d02c49a783de548d1ba8ae8fde466a20b9e6"
SRC_URI += "git://github.com/hashicorp/go-immutable-radix.git;name=go-immutable-radix;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-immutable-radix"

#   github.com/hashicorp/go-memdb v1.3.2
# [1] git ls-remote https://github.com/hashicorp/go-memdb.git 542a5804dedaaddf1a0cad8b6a7b0b3fcf438776
SRCREV_go-memdb="542a5804dedaaddf1a0cad8b6a7b0b3fcf438776"
SRC_URI += "git://github.com/hashicorp/go-memdb.git;name=go-memdb;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-memdb"

#   github.com/hashicorp/golang-lru v0.5.4
# [1] git ls-remote https://github.com/hashicorp/golang-lru.git 14eae340515388ca95aa8e7b86f0de668e981f54
SRCREV_golang-lru="14eae340515388ca95aa8e7b86f0de668e981f54"
SRC_URI += "git://github.com/hashicorp/golang-lru.git;name=golang-lru;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/golang-lru"

#   github.com/hashicorp/hcl v1.0.0
# [1] git ls-remote https://github.com/hashicorp/hcl.git 5592d2526badd60c172ffa95c6a3b209bea9d1ee
SRCREV_hcl="5592d2526badd60c172ffa95c6a3b209bea9d1ee"
SRC_URI += "git://github.com/hashicorp/hcl.git;name=hcl;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/hcl"

#   github.com/imdario/mergo v0.3.16
# [1] git ls-remote https://github.com/imdario/mergo.git 14fe2b165b83359196f820886a2b24f2771729e9
SRCREV_mergo="14fe2b165b83359196f820886a2b24f2771729e9"
SRC_URI += "git://github.com/imdario/mergo.git;name=mergo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/imdario/mergo"

#   github.com/in-toto/in-toto-golang v0.5.0
# [1] git ls-remote https://github.com/in-toto/in-toto-golang.git 118241e367e929595bb651c62182576bb964cffc
SRCREV_in-toto-golang="118241e367e929595bb651c62182576bb964cffc"
SRC_URI += "git://github.com/in-toto/in-toto-golang.git;name=in-toto-golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/in-toto/in-toto-golang"

#   github.com/inconshreveable/mousetrap v1.1.0
# [1] git ls-remote https://github.com/inconshreveable/mousetrap.git 4e8053ee7ef85a6bd26368364a6d27f1641c1d21
SRCREV_mousetrap="4e8053ee7ef85a6bd26368364a6d27f1641c1d21"
SRC_URI += "git://github.com/inconshreveable/mousetrap.git;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

#   github.com/jinzhu/gorm v1.9.11
# [1] git ls-remote https://github.com/jinzhu/gorm.git 81c17a7e2529c59efc4e74c5b32c1fb71fb12fa2
SRCREV_gorm="81c17a7e2529c59efc4e74c5b32c1fb71fb12fa2"
SRC_URI += "git://github.com/jinzhu/gorm.git;name=gorm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jinzhu/gorm"

#   github.com/josharian/intern v1.0.0
# [1] git ls-remote https://github.com/josharian/intern.git 8e6ff32b3e7c0b018c43953085fe2ac330fe9acd
SRCREV_intern="8e6ff32b3e7c0b018c43953085fe2ac330fe9acd"
SRC_URI += "git://github.com/josharian/intern.git;name=intern;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/josharian/intern"

#   github.com/json-iterator/go v1.1.12
# [1] git ls-remote https://github.com/json-iterator/go.git 024077e996b048517130b21ea6bf12aa23055d3d
SRCREV_gov1_1_12="024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go.git;name=gov1_1_12;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/json-iterator/go"

#   github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
# [1] git ls-remote https://github.com/kballard/go-shellquote.git 95032a82bc518f77982ea72343cc1ade730072f0
SRCREV_go-shellquote="95032a82bc518f77982ea72343cc1ade730072f0"
SRC_URI += "git://github.com/kballard/go-shellquote.git;name=go-shellquote;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kballard/go-shellquote"

#   github.com/klauspost/compress v1.16.5
# [1] git ls-remote https://github.com/klauspost/compress.git ed6feffc3bb26797dc2a376516b16611046cdecd
SRCREV_compress="ed6feffc3bb26797dc2a376516b16611046cdecd"
SRC_URI += "git://github.com/klauspost/compress.git;name=compress;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/klauspost/compress"

#   github.com/kr/pretty v0.3.0
# [1] git ls-remote https://github.com/kr/pretty.git 6259398fb07372ee10ef52d88375fdab383bcf9d
SRCREV_pretty="6259398fb07372ee10ef52d88375fdab383bcf9d"
SRC_URI += "git://github.com/kr/pretty.git;name=pretty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kr/pretty"

#   github.com/magiconair/properties v1.8.6
# [1] git ls-remote https://github.com/magiconair/properties.git e97104ee21cdf9cc3ac33992fc829cdc3664d238
SRCREV_properties="e97104ee21cdf9cc3ac33992fc829cdc3664d238"
SRC_URI += "git://github.com/magiconair/properties.git;name=properties;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/magiconair/properties"

#   github.com/mailru/easyjson v0.7.6
# [1] git ls-remote https://github.com/mailru/easyjson.git 8ab5ff9cd8e4e432e8b79f6c47d324a31dd803cf
SRCREV_easyjson="8ab5ff9cd8e4e432e8b79f6c47d324a31dd803cf"
SRC_URI += "git://github.com/mailru/easyjson.git;name=easyjson;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mailru/easyjson"

#   github.com/mattn/go-colorable v0.1.13
# [1] git ls-remote https://github.com/mattn/go-colorable.git 11a925cff3d38c293ddc8c05a16b504e3e2c63be
SRCREV_go-colorable="11a925cff3d38c293ddc8c05a16b504e3e2c63be"
SRC_URI += "git://github.com/mattn/go-colorable.git;name=go-colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

#   github.com/mattn/go-isatty v0.0.17
# [1] git ls-remote https://github.com/mattn/go-isatty.git ed75e619dc0f0489fd4062163a7d061eaa249b9c
SRCREV_go-isatty="ed75e619dc0f0489fd4062163a7d061eaa249b9c"
SRC_URI += "git://github.com/mattn/go-isatty.git;name=go-isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

#   github.com/mattn/go-runewidth v0.0.14
# [1] git ls-remote https://github.com/mattn/go-runewidth.git 2c6a438f68cfe01255a90824599da41fdf76d1e2
SRCREV_go-runewidth="2c6a438f68cfe01255a90824599da41fdf76d1e2"
SRC_URI += "git://github.com/mattn/go-runewidth.git;name=go-runewidth;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-runewidth"

#   github.com/matttproud/golang_protobuf_extensions v1.0.4
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions.git c182affec369e30f25d3eb8cd8a478dee585ae7d
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions.git;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

#   github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
# [1] git ls-remote https://github.com/mgutz/ansi.git 9520e82c474b0a04dd04f8a40959027271bab992
SRCREV_ansi="9520e82c474b0a04dd04f8a40959027271bab992"
SRC_URI += "git://github.com/mgutz/ansi.git;name=ansi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mgutz/ansi"

#   github.com/miekg/pkcs11 v1.1.1
# [1] git ls-remote https://github.com/miekg/pkcs11.git f3481918a208bd212aa995a41f92d786eb418a7d
SRCREV_pkcs11="f3481918a208bd212aa995a41f92d786eb418a7d"
SRC_URI += "git://github.com/miekg/pkcs11.git;name=pkcs11;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/miekg/pkcs11"

#   github.com/moby/locker v1.0.1
# [1] git ls-remote https://github.com/moby/locker.git e15721d7a0126008853f3cefbdbb368685cd1f4d
SRCREV_locker="e15721d7a0126008853f3cefbdbb368685cd1f4d"
SRC_URI += "git://github.com/moby/locker.git;name=locker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/locker"

#   github.com/moby/spdystream v0.2.0
# [1] git ls-remote https://github.com/moby/spdystream.git dbc715126c0e3fa07721879c6d265b2b82c71e5b
SRCREV_spdystream="dbc715126c0e3fa07721879c6d265b2b82c71e5b"
SRC_URI += "git://github.com/moby/spdystream.git;name=spdystream;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/spdystream"

#   github.com/moby/sys/mountinfo v0.6.2
# [1] git ls-remote https://github.com/moby/sys.git 1bf36f7188c31f2797c556c4c4d7d9af7a6a965b
SRCREV_mountinfo="1bf36f7188c31f2797c556c4c4d7d9af7a6a965b"
SRC_URI += "git://github.com/moby/sys.git;name=mountinfo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mountinfo"

#   github.com/moby/sys/sequential v0.5.0
# [1] git ls-remote https://github.com/moby/sys.git b22ba8a69b306f0b4adbbe2a529457e6283ed9f7
SRCREV_sequential="b22ba8a69b306f0b4adbbe2a529457e6283ed9f7"
SRC_URI += "git://github.com/moby/sys.git;name=sequential;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/sequential"

#   github.com/moby/sys/signal v0.7.0
# [1] git ls-remote https://github.com/moby/sys.git b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5
SRCREV_signal="b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5"
SRC_URI += "git://github.com/moby/sys.git;name=signal;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/signal"

#   github.com/moby/sys/symlink v0.2.0
# [1] git ls-remote https://github.com/moby/sys.git 03b9f8d59a07f5206a2264105f4903a222aea964
SRCREV_symlink="03b9f8d59a07f5206a2264105f4903a222aea964"
SRC_URI += "git://github.com/moby/sys.git;name=symlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/symlink"

#   github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
# [1] git ls-remote https://github.com/modern-go/concurrent.git bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
SRCREV_concurrent="bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent.git;name=concurrent;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/concurrent"

#   github.com/modern-go/reflect2 v1.0.2
# [1] git ls-remote https://github.com/modern-go/reflect2.git 2b33151c9bbc5231aea69b8861c540102b087070
SRCREV_reflect2="2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2.git;name=reflect2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/reflect2"

#   github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
# [1] git ls-remote https://github.com/munnerz/goautoneg.git a7dc8b61c822528f973a5e4e7b272055c6fdb43e
SRCREV_goautoneg="a7dc8b61c822528f973a5e4e7b272055c6fdb43e"
SRC_URI += "git://github.com/munnerz/goautoneg.git;name=goautoneg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/munnerz/goautoneg"

#   github.com/opencontainers/runc v1.1.7
# [1] git ls-remote https://github.com/opencontainers/runc.git 532d81d385677036958916d9aed5dd3431c5edb5
SRCREV_runc="532d81d385677036958916d9aed5dd3431c5edb5"
SRC_URI += "git://github.com/opencontainers/runc.git;name=runc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runc"

#   github.com/pelletier/go-toml v1.9.5
# [1] git ls-remote https://github.com/pelletier/go-toml.git fed1464066413075eac02cd4dc368b5221845541
SRCREV_go-toml="fed1464066413075eac02cd4dc368b5221845541"
SRC_URI += "git://github.com/pelletier/go-toml.git;name=go-toml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pelletier/go-toml"

#   github.com/pelletier/go-toml/v2 v2.0.5
# [1] git ls-remote https://github.com/pelletier/go-toml.git 942841787a7d70422e4d8bc7d0be28ab911402df
SRCREV_v2v2_0_5="942841787a7d70422e4d8bc7d0be28ab911402df"
SRC_URI += "git://github.com/pelletier/go-toml.git;name=v2v2_0_5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pelletier/go-toml/v2"

#   github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib.git c0b812dadcf4498dede02bb7f0c5c478be997e34
SRCREV_go-difflib="c0b812dadcf4498dede02bb7f0c5c478be997e34"
SRC_URI += "git://github.com/pmezard/go-difflib.git;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

#   github.com/prometheus/client_golang v1.14.0
# [1] git ls-remote https://github.com/prometheus/client_golang.git 254e5468413f19fb75cdad45f5ddc0b8c975188c
SRCREV_client_golang="254e5468413f19fb75cdad45f5ddc0b8c975188c"
SRC_URI += "git://github.com/prometheus/client_golang.git;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

#   github.com/prometheus/client_model v0.3.0
# [1] git ls-remote https://github.com/prometheus/client_model.git ac628887ccf5dae9ff7625bc75a14f11b763252e
SRCREV_client_model="ac628887ccf5dae9ff7625bc75a14f11b763252e"
SRC_URI += "git://github.com/prometheus/client_model.git;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

#   github.com/prometheus/common v0.42.0
# [1] git ls-remote https://github.com/prometheus/common.git bdfacee9482b4ecedb0ab17b72b83e9aa9203199
SRCREV_common="bdfacee9482b4ecedb0ab17b72b83e9aa9203199"
SRC_URI += "git://github.com/prometheus/common.git;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

#   github.com/prometheus/procfs v0.9.0
# [1] git ls-remote https://github.com/prometheus/procfs.git bb7727a9ca9b3cd1559b42ffa74e13ef7efb6283
SRCREV_procfs="bb7727a9ca9b3cd1559b42ffa74e13ef7efb6283"
SRC_URI += "git://github.com/prometheus/procfs.git;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

#   github.com/rivo/uniseg v0.2.0
# [1] git ls-remote https://github.com/rivo/uniseg.git 75711fccf6a3e85bc74c241e2dddd06a9bc9e53d
SRCREV_uniseg="75711fccf6a3e85bc74c241e2dddd06a9bc9e53d"
SRC_URI += "git://github.com/rivo/uniseg.git;name=uniseg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rivo/uniseg"

#   github.com/secure-systems-lab/go-securesystemslib v0.4.0
# [1] git ls-remote https://github.com/secure-systems-lab/go-securesystemslib.git 900aa2558e30069e21350cb1151d805c6e0c661d
SRCREV_go-securesystemslib="900aa2558e30069e21350cb1151d805c6e0c661d"
SRC_URI += "git://github.com/secure-systems-lab/go-securesystemslib.git;name=go-securesystemslib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/secure-systems-lab/go-securesystemslib"

#   github.com/serialx/hashring v0.0.0-20190422032157-8b2912629002
# [1] git ls-remote https://github.com/serialx/hashring.git 8b2912629002c928de72c69aae20c8600bef41a6
SRCREV_hashring="8b2912629002c928de72c69aae20c8600bef41a6"
SRC_URI += "git://github.com/serialx/hashring.git;name=hashring;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/serialx/hashring"

#   github.com/shibumi/go-pathspec v1.3.0
# [1] git ls-remote https://github.com/shibumi/go-pathspec.git ff20d718fefa5bcffc4d9f4da812042e428cff33
SRCREV_go-pathspec="ff20d718fefa5bcffc4d9f4da812042e428cff33"
SRC_URI += "git://github.com/shibumi/go-pathspec.git;name=go-pathspec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/shibumi/go-pathspec"

#   github.com/spf13/afero v1.9.2
# [1] git ls-remote https://github.com/spf13/afero.git 2a70f2bb2db1524bf2aa3ca0cfebefa8d6367b7b
SRCREV_afero="2a70f2bb2db1524bf2aa3ca0cfebefa8d6367b7b"
SRC_URI += "git://github.com/spf13/afero.git;name=afero;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/afero"

#   github.com/spf13/cast v1.5.0
# [1] git ls-remote https://github.com/spf13/cast.git 2b0eb0f724e320b655240e331aef36d1175986c2
SRCREV_cast="2b0eb0f724e320b655240e331aef36d1175986c2"
SRC_URI += "git://github.com/spf13/cast.git;name=cast;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cast"

#   github.com/spf13/jwalterweatherman v1.1.0
# [1] git ls-remote https://github.com/spf13/jwalterweatherman.git 94f6ae3ed3bceceafa716478c5fbf8d29ca601a1
SRCREV_jwalterweatherman="94f6ae3ed3bceceafa716478c5fbf8d29ca601a1"
SRC_URI += "git://github.com/spf13/jwalterweatherman.git;name=jwalterweatherman;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/jwalterweatherman"

#   github.com/subosito/gotenv v1.4.1
# [1] git ls-remote https://github.com/subosito/gotenv.git 04c527a2392fc7d56b1f49da887ec7cfce43a3bf
SRCREV_gotenv="04c527a2392fc7d56b1f49da887ec7cfce43a3bf"
SRC_URI += "git://github.com/subosito/gotenv.git;name=gotenv;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/subosito/gotenv"

#   github.com/tonistiigi/fsutil v0.0.0-20230407161946-9e7a6df48576
# [1] git ls-remote https://github.com/tonistiigi/fsutil.git 9e7a6df4857652bc85225f55e2edb8aece3ecd43
SRCREV_fsutil="9e7a6df4857652bc85225f55e2edb8aece3ecd43"
SRC_URI += "git://github.com/tonistiigi/fsutil.git;name=fsutil;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/fsutil"

#   github.com/tonistiigi/units v0.0.0-20180711220420-6950e57a87ea
# [1] git ls-remote https://github.com/tonistiigi/units.git 6950e57a87eaf136bbe44ef2ec8e75b9e3569de2
SRCREV_units="6950e57a87eaf136bbe44ef2ec8e75b9e3569de2"
SRC_URI += "git://github.com/tonistiigi/units.git;name=units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/units"

#   github.com/tonistiigi/vt100 v0.0.0-20230623042737-f9a4f7ef6531
# [1] git ls-remote https://github.com/tonistiigi/vt100.git f9a4f7ef65311848d4d4791c649a178c8e97386b
SRCREV_vt100="f9a4f7ef65311848d4d4791c649a178c8e97386b"
SRC_URI += "git://github.com/tonistiigi/vt100.git;name=vt100;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/vt100"

#   github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
# [1] git ls-remote https://github.com/xeipuuv/gojsonpointer.git 02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb
SRCREV_gojsonpointer="02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb"
SRC_URI += "git://github.com/xeipuuv/gojsonpointer.git;name=gojsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonpointer"

#   github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
# [1] git ls-remote https://github.com/xeipuuv/gojsonreference.git bd5ef7bd5415a7ac448318e64f11a24cd21e594b
SRCREV_gojsonreference="bd5ef7bd5415a7ac448318e64f11a24cd21e594b"
SRC_URI += "git://github.com/xeipuuv/gojsonreference.git;name=gojsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonreference"

#   github.com/xeipuuv/gojsonschema v1.2.0
# [1] git ls-remote https://github.com/xeipuuv/gojsonschema.git 82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927
SRCREV_gojsonschema="82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927"
SRC_URI += "git://github.com/xeipuuv/gojsonschema.git;name=gojsonschema;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonschema"

#   github.com/zmap/zcrypto v0.0.0-20220605182715-4dfcec6e9a8c
# [1] git ls-remote https://github.com/zmap/zcrypto.git 4dfcec6e9a8c2014f73dd584e64dc797129d77b8
SRCREV_zcrypto="4dfcec6e9a8c2014f73dd584e64dc797129d77b8"
SRC_URI += "git://github.com/zmap/zcrypto.git;name=zcrypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/zmap/zcrypto"

#   go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.40.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 3311cc2a734d7597598cc67910f8f292d13eeda7
SRCREV_otelgrpc="3311cc2a734d7597598cc67910f8f292d13eeda7"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelgrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"

#   go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.40.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 3311cc2a734d7597598cc67910f8f292d13eeda7
SRCREV_otelhttptrace="3311cc2a734d7597598cc67910f8f292d13eeda7"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelhttptrace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace"

#   go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.40.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 3311cc2a734d7597598cc67910f8f292d13eeda7
SRCREV_otelhttp="3311cc2a734d7597598cc67910f8f292d13eeda7"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelhttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"

#   go.opentelemetry.io/otel/exporters/otlp/internal/retry v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_retry="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=retry;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/internal/retry"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.14.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_otlptracehttp="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptracehttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"

#   go.opentelemetry.io/otel/metric v0.37.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 2e54fbb3fede5b54f316b3a08eab236febd854e0
SRCREV_metric="2e54fbb3fede5b54f316b3a08eab236febd854e0"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=metric;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/metric"

#   go.opentelemetry.io/proto/otlp v0.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-proto-go c98f6b5f7362c9b4a717c7a4dab1ba90796a8f21
SRCREV_otlp="c98f6b5f7362c9b4a717c7a4dab1ba90796a8f21"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-proto-go;name=otlp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/proto/otlp"

#   golang.org/x/crypto v0.7.0
# [1] git ls-remote https://go.googlesource.com/crypto 776e461a4e6d8b372a43c72122c5c28cfc40dca2
SRCREV_crypto="776e461a4e6d8b372a43c72122c5c28cfc40dca2"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

#   golang.org/x/mod v0.9.0
# [1] git ls-remote https://go.googlesource.com/mod 69aa7acea306dfd277ec48fcc687ef8fa0f2bdb4
SRCREV_mod="69aa7acea306dfd277ec48fcc687ef8fa0f2bdb4"
SRC_URI += "git://go.googlesource.com/mod;name=mod;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/mod"

#   golang.org/x/net v0.9.0
# [1] git ls-remote https://go.googlesource.com/net 694cff8668bac64e0864b552bffc280cd27f21b1
SRCREV_net="694cff8668bac64e0864b552bffc280cd27f21b1"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

#   golang.org/x/oauth2 v0.7.0
# [1] git ls-remote https://go.googlesource.com/oauth2 36075149c5b89480def496c735b8a1ba5fc63218
SRCREV_oauth2="36075149c5b89480def496c735b8a1ba5fc63218"
SRC_URI += "git://go.googlesource.com/oauth2;name=oauth2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/oauth2"

#   golang.org/x/sys v0.7.0
# [1] git ls-remote https://go.googlesource.com/sys 64840c112d2335ed9874114aed48f946e778a769
SRCREV_sys="64840c112d2335ed9874114aed48f946e778a769"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#   golang.org/x/term v0.7.0
# [1] git ls-remote https://go.googlesource.com/term 7ae6be6d0150527c2c41e70586b9ade6a972a186
SRCREV_termv0_7_0="7ae6be6d0150527c2c41e70586b9ade6a972a186"
SRC_URI += "git://go.googlesource.com/term;name=termv0_7_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

#   golang.org/x/text v0.9.0
# [1] git ls-remote https://go.googlesource.com/text 48e4a4a957429d31328a685863b594ca9a06b552
SRCREV_text="48e4a4a957429d31328a685863b594ca9a06b552"
SRC_URI += "git://go.googlesource.com/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

#   golang.org/x/time v0.3.0
# [1] git ls-remote https://go.googlesource.com/time 2c09566ef13fb5556401ddff3c53c3dbc2a42dac
SRCREV_time="2c09566ef13fb5556401ddff3c53c3dbc2a42dac"
SRC_URI += "git://go.googlesource.com/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"

#   golang.org/x/tools v0.7.0
# [1] git ls-remote https://go.googlesource.com/tools 031fc75960d487b0b15db12fb328676236a3a39c
SRCREV_tools="031fc75960d487b0b15db12fb328676236a3a39c"
SRC_URI += "git://go.googlesource.com/tools;name=tools;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/tools"

#   google.golang.org/appengine v1.6.7
# [1] git ls-remote https://github.com/golang/appengine 5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a
SRCREV_appengine="5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a"
SRC_URI += "git://github.com/golang/appengine;name=appengine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/appengine"

#   google.golang.org/genproto v0.0.0-20230410155749-daa745c078e1
# [1] git ls-remote https://github.com/googleapis/go-genproto daa745c078e18def54ea6b63235554b59c97f01d
SRCREV_genproto="daa745c078e18def54ea6b63235554b59c97f01d"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto"

#   google.golang.org/protobuf v1.30.0
# [1] git ls-remote https://go.googlesource.com/protobuf f221882bfb484564f1714ae05f197dea2c76898d
SRCREV_protobufv1_30_0="f221882bfb484564f1714ae05f197dea2c76898d"
SRC_URI += "git://go.googlesource.com/protobuf;name=protobufv1_30_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/protobuf"

#   gopkg.in/inf.v0 v0.9.1
# [1] git ls-remote https://gopkg.in/inf.v0 d2d2541c53f18d2a059457998ce2876cc8e67cbf
SRCREV_inf.v0="d2d2541c53f18d2a059457998ce2876cc8e67cbf"
SRC_URI += "git://gopkg.in/inf.v0;name=inf.v0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/inf.v0"

#   gopkg.in/ini.v1 v1.67.0
# [1] git ls-remote https://gopkg.in/ini.v1 b2f570e5b5b844226bbefe6fb521d891f529a951
SRCREV_ini.v1="b2f570e5b5b844226bbefe6fb521d891f529a951"
SRC_URI += "git://gopkg.in/ini.v1;name=ini.v1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/ini.v1"

#   gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://gopkg.in/yaml.v3 f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#   k8s.io/api v0.26.2
# [1] git ls-remote https://github.com/kubernetes/api f64af0da17d62530a91be0775eaf7b321177728a
SRCREV_api="f64af0da17d62530a91be0775eaf7b321177728a"
SRC_URI += "git://github.com/kubernetes/api;name=api;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/api"

#   k8s.io/apimachinery v0.26.2
# [1] git ls-remote https://github.com/kubernetes/apimachinery 7d572c20dc6d2cd872a1cfc8db4f3ae4512fc9ef
SRCREV_apimachinery="7d572c20dc6d2cd872a1cfc8db4f3ae4512fc9ef"
SRC_URI += "git://github.com/kubernetes/apimachinery;name=apimachinery;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/apimachinery"

#   k8s.io/client-go v0.26.2
# [1] git ls-remote https://github.com/kubernetes/client-go b069f1a206c4a669439cc6fc156a6797ea4cdf9c
SRCREV_client-go="b069f1a206c4a669439cc6fc156a6797ea4cdf9c"
SRC_URI += "git://github.com/kubernetes/client-go;name=client-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/client-go"

#   k8s.io/klog/v2 v2.90.1
# [1] git ls-remote https://github.com/kubernetes/klog d7fc50528570f8276de46570f916682257821e22
SRCREV_v2v2_90_1="d7fc50528570f8276de46570f916682257821e22"
SRC_URI += "git://github.com/kubernetes/klog;name=v2v2_90_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/klog/v2"

#   k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280
# [1] git ls-remote https://github.com/kubernetes/kube-openapi 172d655c2280350c77cf05962948fc67ff043492
SRCREV_kube-openapi="172d655c2280350c77cf05962948fc67ff043492"
SRC_URI += "git://github.com/kubernetes/kube-openapi;name=kube-openapi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/kube-openapi"

#   k8s.io/utils v0.0.0-20230220204549-a5ecb0141aa5
# [1] git ls-remote https://github.com/kubernetes/utils a5ecb0141aa5b1b224e745aca203afdfd22d8b3a
SRCREV_utils="a5ecb0141aa5b1b224e745aca203afdfd22d8b3a"
SRC_URI += "git://github.com/kubernetes/utils;name=utils;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/utils"

#   sigs.k8s.io/json v0.0.0-20220713155537-f223a00ba0e2
# [1] git ls-remote https://github.com/kubernetes-sigs/json f223a00ba0e27f539157f69f9c919c204ea7f40b
SRCREV_json="f223a00ba0e27f539157f69f9c919c204ea7f40b"
SRC_URI += "git://github.com/kubernetes-sigs/json;name=json;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/json"

#   sigs.k8s.io/structured-merge-diff/v4 v4.2.3
# [1] git ls-remote https://github.com/kubernetes-sigs/structured-merge-diff 26781d0c10bfdbd7d66b18d8be83985f623df9f8
SRCREV_v4v4_2_3="26781d0c10bfdbd7d66b18d8be83985f623df9f8"
SRC_URI += "git://github.com/kubernetes-sigs/structured-merge-diff;name=v4v4_2_3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/structured-merge-diff/v4"

#   sigs.k8s.io/yaml v1.3.0
# [1] git ls-remote https://github.com/kubernetes-sigs/yaml 9535b3b1e2893fe44efb37c5c9f5665e245d786a
SRCREV_yaml="9535b3b1e2893fe44efb37c5c9f5665e245d786a"
SRC_URI += "git://github.com/kubernetes-sigs/yaml;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/yaml"

