#   github.com/AlecAivazis/survey/v2 v2.3.7
# [1] git ls-remote https://github.com/AlecAivazis/survey.git fa37277e6394c29db7bcc94062cb30cd7785a126
SRCREV_v2="fa37277e6394c29db7bcc94062cb30cd7785a126"
SRC_URI += "git://github.com/AlecAivazis/survey.git;name=v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AlecAivazis/survey/v2"

#   github.com/Microsoft/go-winio v0.6.1
# [1] git ls-remote https://github.com/microsoft/go-winio.git 070c828abb873da9e71c7247740253b50f7cf049
SRCREV_go-winio="070c828abb873da9e71c7247740253b50f7cf049"
SRC_URI += "git://github.com/microsoft/go-winio.git;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

#   github.com/buger/goterm v1.0.4
# [1] git ls-remote https://github.com/buger/goterm.git a73545aae7d693f786ce4cc687460efca4845f31
SRCREV_goterm="a73545aae7d693f786ce4cc687460efca4845f31"
SRC_URI += "git://github.com/buger/goterm.git;name=goterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/buger/goterm"

#   github.com/compose-spec/compose-go/v2 v2.0.0-rc.8.0.20240228111658-a0507e98fe60
# [1] git ls-remote https://github.com/compose-spec/compose-go.git a0507e98fe6033944fc520f3488d4254e79fc6a2
SRCREV_v2v2_0_0_rc_8_0_20240228111658_a0507e98fe60="a0507e98fe6033944fc520f3488d4254e79fc6a2"
SRC_URI += "git://github.com/compose-spec/compose-go.git;name=v2v2_0_0_rc_8_0_20240228111658_a0507e98fe60;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/compose-spec/compose-go/v2"

#   github.com/containerd/console v1.0.3
# [1] git ls-remote https://github.com/containerd/console.git 060a791de16aeb90b3bb4dcd78dfec3ca45fa5df
SRCREV_console="060a791de16aeb90b3bb4dcd78dfec3ca45fa5df"
SRC_URI += "git://github.com/containerd/console.git;name=console;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/console"

#   github.com/containerd/containerd v1.7.12
# [1] git ls-remote https://github.com/containerd/containerd.git a2defb5c2e76ce50506a323828ee26ea158a5a60
SRCREV_containerd="a2defb5c2e76ce50506a323828ee26ea158a5a60"
SRC_URI += "git://github.com/containerd/containerd.git;name=containerd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/containerd"

#   github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew.git 152484fe5c9ff65d013f0f372d748c03e8749e6d
SRCREV_go-spew="152484fe5c9ff65d013f0f372d748c03e8749e6d"
SRC_URI += "git://github.com/davecgh/go-spew.git;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

#   github.com/distribution/reference v0.5.0
# [1] git ls-remote https://github.com/distribution/reference.git 7be746a6cd867c6cece517b557fa086ca26ac214
SRCREV_reference="7be746a6cd867c6cece517b557fa086ca26ac214"
SRC_URI += "git://github.com/distribution/reference.git;name=reference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/distribution/reference"

#   github.com/docker/buildx v0.12.0-rc2.0.20231219140829-617f538cb315
# [1] git ls-remote https://github.com/docker/buildx.git 617f538cb315e8fe2286b263f402ef3acfe2edff
SRCREV_buildx="617f538cb315e8fe2286b263f402ef3acfe2edff"
SRC_URI += "git://github.com/docker/buildx.git;name=buildx;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/buildx"

#   github.com/docker/cli v25.0.4-0.20240305161310-2bf4225ad269+incompatible
# [1] git ls-remote https://github.com/docker/cli.git 2bf4225ad2695106b0094269d613190196ebc5bc
SRCREV_cli="2bf4225ad2695106b0094269d613190196ebc5bc"
SRC_URI += "git://github.com/docker/cli.git;name=cli;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli"

#   github.com/docker/cli-docs-tool v0.6.0
# [1] git ls-remote https://github.com/docker/cli-docs-tool.git 5cb124c70a1f08a8fcbffad5059b4b5b01123124
SRCREV_cli-docs-tool="5cb124c70a1f08a8fcbffad5059b4b5b01123124"
SRC_URI += "git://github.com/docker/cli-docs-tool.git;name=cli-docs-tool;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/cli-docs-tool"

#   github.com/docker/docker v25.0.4-0.20240301160236-51e876cd964c+incompatible
# [1] git ls-remote https://github.com/moby/moby.git 51e876cd964c4bb1f0a7c1bc24ecab9321b3ff1c
SRCREV_docker="51e876cd964c4bb1f0a7c1bc24ecab9321b3ff1c"
SRC_URI += "git://github.com/moby/moby.git;name=docker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker"

#   github.com/docker/go-connections v0.5.0
# [1] git ls-remote https://github.com/docker/go-connections.git 9ef9d5a8e904216e104cb86ad35d6b02bb9d723b
SRCREV_go-connections="9ef9d5a8e904216e104cb86ad35d6b02bb9d723b"
SRC_URI += "git://github.com/docker/go-connections.git;name=go-connections;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-connections"

#   github.com/docker/go-units v0.5.0
# [1] git ls-remote https://github.com/docker/go-units.git 1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8
SRCREV_go-units="1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8"
SRC_URI += "git://github.com/docker/go-units.git;name=go-units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-units"

#   github.com/fsnotify/fsevents v0.1.1
# [1] git ls-remote https://github.com/fsnotify/fsevents.git f721bd2b045774a566e8f7f5fa2a9985e04c875d
SRCREV_fsevents="f721bd2b045774a566e8f7f5fa2a9985e04c875d"
SRC_URI += "git://github.com/fsnotify/fsevents.git;name=fsevents;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fsnotify/fsevents"

#   github.com/google/go-cmp v0.6.0
# [1] git ls-remote https://github.com/google/go-cmp.git c3ad8435e7bef96af35732bc0789e5a2278c6d5f
SRCREV_go-cmp="c3ad8435e7bef96af35732bc0789e5a2278c6d5f"
SRC_URI += "git://github.com/google/go-cmp.git;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

#   github.com/hashicorp/go-multierror v1.1.1
# [1] git ls-remote https://github.com/hashicorp/go-multierror.git 9974e9ec57696378079ecc3accd3d6f29401b3a0
SRCREV_go-multierror="9974e9ec57696378079ecc3accd3d6f29401b3a0"
SRC_URI += "git://github.com/hashicorp/go-multierror.git;name=go-multierror;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-multierror"

#   github.com/hashicorp/go-version v1.6.0
# [1] git ls-remote https://github.com/hashicorp/go-version.git 78d058c5618891f74d604bd15356fca690b64d8a
SRCREV_go-version="78d058c5618891f74d604bd15356fca690b64d8a"
SRC_URI += "git://github.com/hashicorp/go-version.git;name=go-version;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-version"

#   github.com/jonboulle/clockwork v0.4.0
# [1] git ls-remote https://github.com/jonboulle/clockwork.git 3fb70b88bf9d29704406d8de245cdf3972637984
SRCREV_clockwork="3fb70b88bf9d29704406d8de245cdf3972637984"
SRC_URI += "git://github.com/jonboulle/clockwork.git;name=clockwork;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jonboulle/clockwork"

#   github.com/mattn/go-shellwords v1.0.12
# [1] git ls-remote https://github.com/mattn/go-shellwords.git 973b9d5391598d4ee601db46fa32f6e186a356ac
SRCREV_go-shellwords="973b9d5391598d4ee601db46fa32f6e186a356ac"
SRC_URI += "git://github.com/mattn/go-shellwords.git;name=go-shellwords;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-shellwords"

#   github.com/mitchellh/go-ps v1.0.0
# [1] git ls-remote https://github.com/mitchellh/go-ps.git 147ff83818ae939913b2e20b91ae3cd6c391771c
SRCREV_go-ps="147ff83818ae939913b2e20b91ae3cd6c391771c"
SRC_URI += "git://github.com/mitchellh/go-ps.git;name=go-ps;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/go-ps"

#   github.com/mitchellh/mapstructure v1.5.0
# [1] git ls-remote https://github.com/mitchellh/mapstructure.git ab69d8d93410fce4361f4912bb1ff88110a81311
SRCREV_mapstructure="ab69d8d93410fce4361f4912bb1ff88110a81311"
SRC_URI += "git://github.com/mitchellh/mapstructure.git;name=mapstructure;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/mapstructure"

#   github.com/moby/buildkit v0.13.0-beta1.0.20231219135447-957cb50df991
# [1] git ls-remote https://github.com/moby/buildkit.git 957cb50df9910502a284ed3e49a3381ec2a96bbf
SRCREV_buildkit="957cb50df9910502a284ed3e49a3381ec2a96bbf"
SRC_URI += "git://github.com/moby/buildkit.git;name=buildkit;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/buildkit"

#   github.com/moby/patternmatcher v0.6.0
# [1] git ls-remote https://github.com/moby/patternmatcher.git e3572525e1d01ce14d673d39a2f1e743a318df36
SRCREV_patternmatcher="e3572525e1d01ce14d673d39a2f1e743a318df36"
SRC_URI += "git://github.com/moby/patternmatcher.git;name=patternmatcher;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/patternmatcher"

#   github.com/moby/term v0.5.0
# [1] git ls-remote https://github.com/moby/term.git 29d1ed41b766a40d15b5bac3b9ab1e07f961604d
SRCREV_term="29d1ed41b766a40d15b5bac3b9ab1e07f961604d"
SRC_URI += "git://github.com/moby/term.git;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/term"

#   github.com/morikuni/aec v1.0.0
# [1] git ls-remote https://github.com/morikuni/aec.git 39771216ff4c63d11f5e604076f9c45e8be1067b
SRCREV_aec="39771216ff4c63d11f5e604076f9c45e8be1067b"
SRC_URI += "git://github.com/morikuni/aec.git;name=aec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/morikuni/aec"

#   github.com/opencontainers/go-digest v1.0.0
# [1] git ls-remote https://github.com/opencontainers/go-digest.git 4a41a1fddd8208cc64f911e551a7f361716f8ae5
SRCREV_go-digest="4a41a1fddd8208cc64f911e551a7f361716f8ae5"
SRC_URI += "git://github.com/opencontainers/go-digest.git;name=go-digest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/go-digest"

#   github.com/opencontainers/image-spec v1.1.0-rc6
# [1] git ls-remote https://github.com/opencontainers/image-spec.git ca040e000ac59f9fe75e9f4857ef16f549dddb2c
SRCREV_image-spec="ca040e000ac59f9fe75e9f4857ef16f549dddb2c"
SRC_URI += "git://github.com/opencontainers/image-spec.git;name=image-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/image-spec"

#   github.com/otiai10/copy v1.14.0
# [1] git ls-remote https://github.com/otiai10/copy.git fba066acb0eb6e25d510073787741c0a8b31bf1e
SRCREV_copy="fba066acb0eb6e25d510073787741c0a8b31bf1e"
SRC_URI += "git://github.com/otiai10/copy.git;name=copy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/otiai10/copy"

#   github.com/sirupsen/logrus v1.9.3
# [1] git ls-remote https://github.com/sirupsen/logrus.git d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd
SRCREV_logrus="d40e25cd45ed9c6b2b66e6b97573a0413e4c23bd"
SRC_URI += "git://github.com/sirupsen/logrus.git;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

#   github.com/spf13/cobra v1.8.0
# [1] git ls-remote https://github.com/spf13/cobra.git a0a6ae020bb3899ff0276067863e50523f897370
SRCREV_cobra="a0a6ae020bb3899ff0276067863e50523f897370"
SRC_URI += "git://github.com/spf13/cobra.git;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

#   github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag.git 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag.git;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

#   github.com/stretchr/testify v1.8.4
# [1] git ls-remote https://github.com/stretchr/testify.git f97607b89807936ac4ff96748d766cf4b9711f78
SRCREV_testify="f97607b89807936ac4ff96748d766cf4b9711f78"
SRC_URI += "git://github.com/stretchr/testify.git;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

#   github.com/theupdateframework/notary v0.7.0
# [1] git ls-remote https://github.com/notaryproject/notary.git 9d266b20442b87d5faa2d4f5ab19604c79cd4c10
SRCREV_notary="9d266b20442b87d5faa2d4f5ab19604c79cd4c10"
SRC_URI += "git://github.com/notaryproject/notary.git;name=notary;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/theupdateframework/notary"

#   github.com/tilt-dev/fsnotify v1.4.8-0.20220602155310-fff9c274a375
# [1] git ls-remote https://github.com/tilt-dev/fsnotify.git fff9c274a375301ae46812f257aa68393790c45b
SRCREV_fsnotify="fff9c274a375301ae46812f257aa68393790c45b"
SRC_URI += "git://github.com/tilt-dev/fsnotify.git;name=fsnotify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tilt-dev/fsnotify"

#   go.opentelemetry.io/otel v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 5d4abb4f5ce669ce4e98668aaaa9760a18629077
SRCREV_otel="5d4abb4f5ce669ce4e98668aaaa9760a18629077"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otel;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlptrace="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptrace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlptracegrpc="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptracegrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc"

#   go.opentelemetry.io/otel/sdk v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_sdk="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=sdk;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/sdk"

#   go.opentelemetry.io/otel/trace v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_trace="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=trace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/trace"

#   go.uber.org/goleak v1.3.0
# [1] git ls-remote https://github.com/uber-go/goleak 31095c657c34bba405a8d480db27989aa5f60b9c
SRCREV_goleak="31095c657c34bba405a8d480db27989aa5f60b9c"
SRC_URI += "git://github.com/uber-go/goleak;name=goleak;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/goleak"

#   go.uber.org/mock v0.4.0
# [1] git ls-remote https://github.com/uber/mock e9f4675deaed5e5239ed94b03b65b16f6cbff4dc
SRCREV_mock="e9f4675deaed5e5239ed94b03b65b16f6cbff4dc"
SRC_URI += "git://github.com/uber/mock;name=mock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/mock"

#   golang.org/x/exp v0.0.0-20240112132812-db7319d0e0e3
# [1] git ls-remote https://go.googlesource.com/exp db7319d0e0e361ccef5c449b760df8e5f2d5087c
SRCREV_exp="db7319d0e0e361ccef5c449b760df8e5f2d5087c"
SRC_URI += "git://go.googlesource.com/exp;name=exp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/exp"

#   golang.org/x/sync v0.6.0
# [1] git ls-remote https://go.googlesource.com/sync 59c1ca1e4661ed4452be4069ceea3c233f4deec1
SRCREV_sync="59c1ca1e4661ed4452be4069ceea3c233f4deec1"
SRC_URI += "git://go.googlesource.com/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

#   golang.org/x/sys v0.16.0
# [1] git ls-remote https://go.googlesource.com/sys 0829ab15b6946f47c40012db2e0c04772730317d
SRCREV_sys="0829ab15b6946f47c40012db2e0c04772730317d"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#   google.golang.org/grpc v1.59.0
# [1] git ls-remote https://github.com/grpc/grpc-go 7765221f4bf6104973db7946d56936cf838cad46
SRCREV_grpc="7765221f4bf6104973db7946d56936cf838cad46"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/grpc"

#   gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://gopkg.in/yaml.v3 f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#   gotest.tools/v3 v3.5.1
# [1] git ls-remote https://github.com/gotestyourself/gotest.tools 81cea1abc596b025bf2573c7fdf97740512e4c6c
SRCREV_v3="81cea1abc596b025bf2573c7fdf97740512e4c6c"
SRC_URI += "git://github.com/gotestyourself/gotest.tools;name=v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gotest.tools/v3"

#   github.com/darccio/mergo v1.0.0
# [1] git ls-remote https://github.com/darccio/mergo.git 131de815afc35a77c41ae99da6c8f4288b6cb513
SRCREV_mergo="131de815afc35a77c41ae99da6c8f4288b6cb513"
SRC_URI += "git://github.com/darccio/mergo.git;name=mergo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/darccio/mergo"

#   github.com/AdaLogics/go-fuzz-headers v0.0.0-20230811130428-ced1acdcaa24
# [1] git ls-remote https://github.com/AdaLogics/go-fuzz-headers.git ced1acdcaa24dc39c01b039fc37576c395f506cf
SRCREV_go-fuzz-headers="ced1acdcaa24dc39c01b039fc37576c395f506cf"
SRC_URI += "git://github.com/AdaLogics/go-fuzz-headers.git;name=go-fuzz-headers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/AdaLogics/go-fuzz-headers"

#   github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
# [1] git ls-remote https://github.com/Azure/go-ansiterm.git d185dfc1b5a126116ea5a19e148e29d16b4574c9
SRCREV_go-ansiterm="d185dfc1b5a126116ea5a19e148e29d16b4574c9"
SRC_URI += "git://github.com/Azure/go-ansiterm.git;name=go-ansiterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Azure/go-ansiterm"

#   github.com/Masterminds/semver/v3 v3.2.1
# [1] git ls-remote https://github.com/Masterminds/semver.git 95a60f04f6ef4fccbc26300575409658fad9616e
SRCREV_v3v3_2_1="95a60f04f6ef4fccbc26300575409658fad9616e"
SRC_URI += "git://github.com/Masterminds/semver.git;name=v3v3_2_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Masterminds/semver/v3"

#   github.com/Microsoft/hcsshim v0.11.4
# [1] git ls-remote https://github.com/microsoft/hcsshim.git b16edf62c1723deb948632261b445d0228d973e0
SRCREV_hcsshim="b16edf62c1723deb948632261b445d0228d973e0"
SRC_URI += "git://github.com/microsoft/hcsshim.git;name=hcsshim;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/hcsshim"

#   github.com/aws/aws-sdk-go-v2 v1.17.6
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git c41faa945b100a9d8d577c0976fbf4138e7427e7
SRCREV_aws-sdk-go-v2="c41faa945b100a9d8d577c0976fbf4138e7427e7"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=aws-sdk-go-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2"

#   github.com/aws/aws-sdk-go-v2/config v1.18.16
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_config="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=config;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/config"

#   github.com/aws/aws-sdk-go-v2/credentials v1.13.16
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_credentials="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=credentials;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/credentials"

#   github.com/aws/aws-sdk-go-v2/feature/ec2/imds v1.12.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_imds="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=imds;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/feature/ec2/imds"

#   github.com/aws/aws-sdk-go-v2/internal/configsources v1.1.30
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_configsources="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=configsources;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/configsources"

#   github.com/aws/aws-sdk-go-v2/internal/endpoints/v2 v2.4.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git b23becc33b6fa4cbd0c1996eb66957372c0246a0
SRCREV_v2v2_4_24="b23becc33b6fa4cbd0c1996eb66957372c0246a0"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=v2v2_4_24;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"

#   github.com/aws/aws-sdk-go-v2/internal/ini v1.3.31
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_ini="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=ini;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/internal/ini"

#   github.com/aws/aws-sdk-go-v2/service/internal/presigned-url v1.9.24
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_presigned-url="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=presigned-url;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"

#   github.com/aws/aws-sdk-go-v2/service/sso v1.12.5
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_sso="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=sso;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/sso"

#   github.com/aws/aws-sdk-go-v2/service/ssooidc v1.14.5
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_ssooidc="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=ssooidc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/ssooidc"

#   github.com/aws/aws-sdk-go-v2/service/sts v1.18.6
# [1] git ls-remote https://github.com/aws/aws-sdk-go-v2.git 18bff5e44f4c2c140feaf54b2dd92140630c7e50
SRCREV_sts="18bff5e44f4c2c140feaf54b2dd92140630c7e50"
SRC_URI += "git://github.com/aws/aws-sdk-go-v2.git;name=sts;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/aws-sdk-go-v2/service/sts"

#   github.com/aws/smithy-go v1.13.5
# [1] git ls-remote https://github.com/aws/smithy-go.git 6178fd4e871aa9cbcfce9ccf96d5e39854a9751e
SRCREV_smithy-go="6178fd4e871aa9cbcfce9ccf96d5e39854a9751e"
SRC_URI += "git://github.com/aws/smithy-go.git;name=smithy-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/aws/smithy-go"

#   github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks.git c49ff274687222a7373c4cd83578f1065cf3e143
SRCREV_perks="c49ff274687222a7373c4cd83578f1065cf3e143"
SRC_URI += "git://github.com/beorn7/perks.git;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

#   github.com/cenkalti/backoff/v4 v4.2.1
# [1] git ls-remote https://github.com/cenkalti/backoff.git a04a6fe64ffb0e3fd0816460529d300be5f252df
SRCREV_v4="a04a6fe64ffb0e3fd0816460529d300be5f252df"
SRC_URI += "git://github.com/cenkalti/backoff.git;name=v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cenkalti/backoff/v4"

#   github.com/cespare/xxhash/v2 v2.2.0
# [1] git ls-remote https://github.com/cespare/xxhash.git 50472e8238a5564de4b2f10531e8b6d1529876e8
SRCREV_v2v2_2_0="50472e8238a5564de4b2f10531e8b6d1529876e8"
SRC_URI += "git://github.com/cespare/xxhash.git;name=v2v2_2_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

#   github.com/containerd/continuity v0.4.2
# [1] git ls-remote https://github.com/containerd/continuity.git 6816d5b42b74123bb8b0bd6dadd01fc09990d732
SRCREV_continuity="6816d5b42b74123bb8b0bd6dadd01fc09990d732"
SRC_URI += "git://github.com/containerd/continuity.git;name=continuity;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/continuity"

#   github.com/containerd/log v0.1.0
# [1] git ls-remote https://github.com/containerd/log.git 0fc1e28871fdf2786e2cc51bbe4133db6547a199
SRCREV_log="0fc1e28871fdf2786e2cc51bbe4133db6547a199"
SRC_URI += "git://github.com/containerd/log.git;name=log;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/log"

#   github.com/containerd/typeurl/v2 v2.1.1
# [1] git ls-remote https://github.com/containerd/typeurl.git 7ef6316b771f959cbb208b229e3423a466947df3
SRCREV_v2v2_1_1="7ef6316b771f959cbb208b229e3423a466947df3"
SRC_URI += "git://github.com/containerd/typeurl.git;name=v2v2_1_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/typeurl/v2"

#   github.com/docker/distribution v2.8.3+incompatible
# [1] git ls-remote https://github.com/distribution/distribution.git df5f20f2e92e343f314c8f0192fff6de159f71a3
SRCREV_distribution="df5f20f2e92e343f314c8f0192fff6de159f71a3"
SRC_URI += "git://github.com/distribution/distribution.git;name=distribution;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/distribution"

#   github.com/docker/docker-credential-helpers v0.8.0
# [1] git ls-remote https://github.com/docker/docker-credential-helpers.git 8396edb35f8d7229e75482e9d82c7729fa7001b7
SRCREV_docker-credential-helpers="8396edb35f8d7229e75482e9d82c7729fa7001b7"
SRC_URI += "git://github.com/docker/docker-credential-helpers.git;name=docker-credential-helpers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/docker-credential-helpers"

#   github.com/docker/go v1.5.1-1.0.20160303222718-d30aec9fd63c
# [1] git ls-remote https://github.com/docker/go.git d30aec9fd63c35133f8f79c3412ad91a3b08be06
SRCREV_go="d30aec9fd63c35133f8f79c3412ad91a3b08be06"
SRC_URI += "git://github.com/docker/go.git;name=go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go"

#   github.com/docker/go-metrics v0.0.1
# [1] git ls-remote https://github.com/docker/go-metrics.git b619b3592b65de4f087d9f16863a7e6ff905973c
SRCREV_go-metrics="b619b3592b65de4f087d9f16863a7e6ff905973c"
SRC_URI += "git://github.com/docker/go-metrics.git;name=go-metrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-metrics"

#   github.com/emicklei/go-restful/v3 v3.10.1
# [1] git ls-remote https://github.com/emicklei/go-restful.git 0927716e5613277c3010149357f37f79151255c6
SRCREV_v3v3_10_1="0927716e5613277c3010149357f37f79151255c6"
SRC_URI += "git://github.com/emicklei/go-restful.git;name=v3v3_10_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/emicklei/go-restful/v3"

#   github.com/felixge/httpsnoop v1.0.4
# [1] git ls-remote https://github.com/felixge/httpsnoop.git c5817c27ec125409c069052fdd171023c353501c
SRCREV_httpsnoop="c5817c27ec125409c069052fdd171023c353501c"
SRC_URI += "git://github.com/felixge/httpsnoop.git;name=httpsnoop;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/felixge/httpsnoop"

#   github.com/fvbommel/sortorder v1.0.2
# [1] git ls-remote https://github.com/fvbommel/sortorder.git 26fad50c6b32a3064c09ed089865c16f2f3615f6
SRCREV_sortorder="26fad50c6b32a3064c09ed089865c16f2f3615f6"
SRC_URI += "git://github.com/fvbommel/sortorder.git;name=sortorder;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fvbommel/sortorder"

#   github.com/go-logr/logr v1.2.4
# [1] git ls-remote https://github.com/go-logr/logr.git 4da5305ff29a64c62f54ad43ebbfcb5e1b015fb2
SRCREV_logr="4da5305ff29a64c62f54ad43ebbfcb5e1b015fb2"
SRC_URI += "git://github.com/go-logr/logr.git;name=logr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/logr"

#   github.com/go-logr/stdr v1.2.2
# [1] git ls-remote https://github.com/go-logr/stdr.git 521af2addfa7c81c8a65d0e85ed34bb6bb6dc262
SRCREV_stdr="521af2addfa7c81c8a65d0e85ed34bb6bb6dc262"
SRC_URI += "git://github.com/go-logr/stdr.git;name=stdr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/stdr"

#   github.com/go-openapi/jsonpointer v0.19.5
# [1] git ls-remote https://github.com/go-openapi/jsonpointer.git a48280f97959fc230ba72550e0a7e7e49d321e1d
SRCREV_jsonpointer="a48280f97959fc230ba72550e0a7e7e49d321e1d"
SRC_URI += "git://github.com/go-openapi/jsonpointer.git;name=jsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonpointer"

#   github.com/go-openapi/jsonreference v0.20.0
# [1] git ls-remote https://github.com/go-openapi/jsonreference.git 5f9ac7dd3cfc5644a4ee6ffa6a90de4a7dc6acf7
SRCREV_jsonreference="5f9ac7dd3cfc5644a4ee6ffa6a90de4a7dc6acf7"
SRC_URI += "git://github.com/go-openapi/jsonreference.git;name=jsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonreference"

#   github.com/go-openapi/swag v0.19.14
# [1] git ls-remote https://github.com/go-openapi/swag.git c78fa6719bc3d4b977d19a09064feda1c07571af
SRCREV_swag="c78fa6719bc3d4b977d19a09064feda1c07571af"
SRC_URI += "git://github.com/go-openapi/swag.git;name=swag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/swag"

#   github.com/gofrs/flock v0.8.1
# [1] git ls-remote https://github.com/gofrs/flock.git a14e9f39bdc9c4be4c0ccddb25b72bbc9670c429
SRCREV_flock="a14e9f39bdc9c4be4c0ccddb25b72bbc9670c429"
SRC_URI += "git://github.com/gofrs/flock.git;name=flock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gofrs/flock"

#   github.com/gogo/googleapis v1.4.1
# [1] git ls-remote https://github.com/gogo/googleapis.git 1f0e43f50bc0606e385ffae1bc80b5b231dcd042
SRCREV_googleapis="1f0e43f50bc0606e385ffae1bc80b5b231dcd042"
SRC_URI += "git://github.com/gogo/googleapis.git;name=googleapis;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/googleapis"

#   github.com/gogo/protobuf v1.3.2
# [1] git ls-remote https://github.com/gogo/protobuf.git b03c65ea87cdc3521ede29f62fe3ce239267c1bc
SRCREV_protobuf="b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf.git;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/protobuf"

#   github.com/golang/protobuf v1.5.3
# [1] git ls-remote https://github.com/golang/protobuf.git 5d5e8c018a13017f9d5b8bf4fad64aaa42a87308
SRCREV_protobufv1_5_3="5d5e8c018a13017f9d5b8bf4fad64aaa42a87308"
SRC_URI += "git://github.com/golang/protobuf.git;name=protobufv1_5_3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

#   github.com/google/gnostic v0.5.7-v3refs
# [1] git ls-remote https://github.com/google/gnostic.git b49832d97d25b6a41cbe34ea12257924a934eeee
SRCREV_gnostic="b49832d97d25b6a41cbe34ea12257924a934eeee"
SRC_URI += "git://github.com/google/gnostic.git;name=gnostic;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gnostic"

#   github.com/google/gofuzz v1.2.0
# [1] git ls-remote https://github.com/google/gofuzz.git 41febe7ec24d8c0e442e940f3f15ee4e8511c447
SRCREV_gofuzz="41febe7ec24d8c0e442e940f3f15ee4e8511c447"
SRC_URI += "git://github.com/google/gofuzz.git;name=gofuzz;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gofuzz"

#   github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
# [1] git ls-remote https://github.com/google/shlex.git e7afc7fbc51079733e9468cdfd1efcd7d196cd1d
SRCREV_shlex="e7afc7fbc51079733e9468cdfd1efcd7d196cd1d"
SRC_URI += "git://github.com/google/shlex.git;name=shlex;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/shlex"

#   github.com/google/uuid v1.5.0
# [1] git ls-remote https://github.com/google/uuid.git 4d47f8eb066f43cfaedd728a543479d9c9dfa8f6
SRCREV_uuid="4d47f8eb066f43cfaedd728a543479d9c9dfa8f6"
SRC_URI += "git://github.com/google/uuid.git;name=uuid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/uuid"

#   github.com/gorilla/mux v1.8.1
# [1] git ls-remote https://github.com/gorilla/mux.git b4617d0b9670ad14039b2739167fd35a60f557c5
SRCREV_mux="b4617d0b9670ad14039b2739167fd35a60f557c5"
SRC_URI += "git://github.com/gorilla/mux.git;name=mux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/mux"

#   github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
# [1] git ls-remote https://github.com/grpc-ecosystem/go-grpc-middleware.git df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd
SRCREV_go-grpc-middleware="df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd"
SRC_URI += "git://github.com/grpc-ecosystem/go-grpc-middleware.git;name=go-grpc-middleware;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/go-grpc-middleware"

#   github.com/grpc-ecosystem/grpc-gateway/v2 v2.16.0
# [1] git ls-remote https://github.com/grpc-ecosystem/grpc-gateway.git 09e3965a330155f7db8482269d7d91b9bceb7641
SRCREV_v2v2_16_0="09e3965a330155f7db8482269d7d91b9bceb7641"
SRC_URI += "git://github.com/grpc-ecosystem/grpc-gateway.git;name=v2v2_16_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/grpc-gateway/v2"

#   github.com/hashicorp/errwrap v1.1.0
# [1] git ls-remote https://github.com/hashicorp/errwrap.git 7b00e5db719c64d14dd0caaacbd13e76254d02c0
SRCREV_errwrap="7b00e5db719c64d14dd0caaacbd13e76254d02c0"
SRC_URI += "git://github.com/hashicorp/errwrap.git;name=errwrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/errwrap"

#   github.com/hashicorp/go-cleanhttp v0.5.2
# [1] git ls-remote https://github.com/hashicorp/go-cleanhttp.git 6d9e2ac5d828e5f8594b97f88c4bde14a67bb6d2
SRCREV_go-cleanhttp="6d9e2ac5d828e5f8594b97f88c4bde14a67bb6d2"
SRC_URI += "git://github.com/hashicorp/go-cleanhttp.git;name=go-cleanhttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/hashicorp/go-cleanhttp"

#   github.com/imdario/mergo v0.3.16
# [1] git ls-remote https://github.com/darccio/mergo.git 14fe2b165b83359196f820886a2b24f2771729e9
SRCREV_mergov0_3_16="14fe2b165b83359196f820886a2b24f2771729e9"
SRC_URI += "git://github.com/darccio/mergo.git;name=mergov0_3_16;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/imdario/mergo"

#   github.com/in-toto/in-toto-golang v0.5.0
# [1] git ls-remote https://github.com/in-toto/in-toto-golang.git 118241e367e929595bb651c62182576bb964cffc
SRCREV_in-toto-golang="118241e367e929595bb651c62182576bb964cffc"
SRC_URI += "git://github.com/in-toto/in-toto-golang.git;name=in-toto-golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/in-toto/in-toto-golang"

#   github.com/inconshreveable/mousetrap v1.1.0
# [1] git ls-remote https://github.com/inconshreveable/mousetrap.git 4e8053ee7ef85a6bd26368364a6d27f1641c1d21
SRCREV_mousetrap="4e8053ee7ef85a6bd26368364a6d27f1641c1d21"
SRC_URI += "git://github.com/inconshreveable/mousetrap.git;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

#   github.com/josharian/intern v1.0.0
# [1] git ls-remote https://github.com/josharian/intern.git 8e6ff32b3e7c0b018c43953085fe2ac330fe9acd
SRCREV_intern="8e6ff32b3e7c0b018c43953085fe2ac330fe9acd"
SRC_URI += "git://github.com/josharian/intern.git;name=intern;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/josharian/intern"

#   github.com/json-iterator/go v1.1.12
# [1] git ls-remote https://github.com/json-iterator/go.git 024077e996b048517130b21ea6bf12aa23055d3d
SRCREV_gov1_1_12="024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go.git;name=gov1_1_12;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/json-iterator/go"

#   github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
# [1] git ls-remote https://github.com/kballard/go-shellquote.git 95032a82bc518f77982ea72343cc1ade730072f0
SRCREV_go-shellquote="95032a82bc518f77982ea72343cc1ade730072f0"
SRC_URI += "git://github.com/kballard/go-shellquote.git;name=go-shellquote;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kballard/go-shellquote"

#   github.com/klauspost/compress v1.17.4
# [1] git ls-remote https://github.com/klauspost/compress.git 98ff542abe3108aa760c1558f80d393be0136539
SRCREV_compress="98ff542abe3108aa760c1558f80d393be0136539"
SRC_URI += "git://github.com/klauspost/compress.git;name=compress;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/klauspost/compress"

#   github.com/mailru/easyjson v0.7.6
# [1] git ls-remote https://github.com/mailru/easyjson.git 8ab5ff9cd8e4e432e8b79f6c47d324a31dd803cf
SRCREV_easyjson="8ab5ff9cd8e4e432e8b79f6c47d324a31dd803cf"
SRC_URI += "git://github.com/mailru/easyjson.git;name=easyjson;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mailru/easyjson"

#   github.com/mattn/go-colorable v0.1.13
# [1] git ls-remote https://github.com/mattn/go-colorable.git 11a925cff3d38c293ddc8c05a16b504e3e2c63be
SRCREV_go-colorable="11a925cff3d38c293ddc8c05a16b504e3e2c63be"
SRC_URI += "git://github.com/mattn/go-colorable.git;name=go-colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

#   github.com/mattn/go-isatty v0.0.17
# [1] git ls-remote https://github.com/mattn/go-isatty.git ed75e619dc0f0489fd4062163a7d061eaa249b9c
SRCREV_go-isatty="ed75e619dc0f0489fd4062163a7d061eaa249b9c"
SRC_URI += "git://github.com/mattn/go-isatty.git;name=go-isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

#   github.com/mattn/go-runewidth v0.0.15
# [1] git ls-remote https://github.com/mattn/go-runewidth.git 44b7c5b4d67df8ca22917b6800c158a6d3be3560
SRCREV_go-runewidth="44b7c5b4d67df8ca22917b6800c158a6d3be3560"
SRC_URI += "git://github.com/mattn/go-runewidth.git;name=go-runewidth;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-runewidth"

#   github.com/matttproud/golang_protobuf_extensions v1.0.4
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions.git c182affec369e30f25d3eb8cd8a478dee585ae7d
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions.git;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

#   github.com/mgutz/ansi v0.0.0-20170206155736-9520e82c474b
# [1] git ls-remote https://github.com/mgutz/ansi.git 9520e82c474b0a04dd04f8a40959027271bab992
SRCREV_ansi="9520e82c474b0a04dd04f8a40959027271bab992"
SRC_URI += "git://github.com/mgutz/ansi.git;name=ansi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mgutz/ansi"

#   github.com/miekg/pkcs11 v1.1.1
# [1] git ls-remote https://github.com/miekg/pkcs11.git f3481918a208bd212aa995a41f92d786eb418a7d
SRCREV_pkcs11="f3481918a208bd212aa995a41f92d786eb418a7d"
SRC_URI += "git://github.com/miekg/pkcs11.git;name=pkcs11;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/miekg/pkcs11"

#   github.com/mitchellh/copystructure v1.2.0
# [1] git ls-remote https://github.com/mitchellh/copystructure.git d4ce1f938f7a7ea2a40bff4544b56be9c00b5e84
SRCREV_copystructure="d4ce1f938f7a7ea2a40bff4544b56be9c00b5e84"
SRC_URI += "git://github.com/mitchellh/copystructure.git;name=copystructure;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/copystructure"

#   github.com/mitchellh/reflectwalk v1.0.2
# [1] git ls-remote https://github.com/mitchellh/reflectwalk.git e0c24fdb021963cd2c4013097a0b993a7c4e344f
SRCREV_reflectwalk="e0c24fdb021963cd2c4013097a0b993a7c4e344f"
SRC_URI += "git://github.com/mitchellh/reflectwalk.git;name=reflectwalk;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/reflectwalk"

#   github.com/moby/locker v1.0.1
# [1] git ls-remote https://github.com/moby/locker.git e15721d7a0126008853f3cefbdbb368685cd1f4d
SRCREV_locker="e15721d7a0126008853f3cefbdbb368685cd1f4d"
SRC_URI += "git://github.com/moby/locker.git;name=locker;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/locker"

#   github.com/moby/spdystream v0.2.0
# [1] git ls-remote https://github.com/moby/spdystream.git dbc715126c0e3fa07721879c6d265b2b82c71e5b
SRCREV_spdystream="dbc715126c0e3fa07721879c6d265b2b82c71e5b"
SRC_URI += "git://github.com/moby/spdystream.git;name=spdystream;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/spdystream"

#   github.com/moby/sys/mountinfo v0.7.1
# [1] git ls-remote https://github.com/moby/sys.git 4950d7687cf6c9b138dc0e18c2c7351e1f6ed497
SRCREV_mountinfo="4950d7687cf6c9b138dc0e18c2c7351e1f6ed497"
SRC_URI += "git://github.com/moby/sys.git;name=mountinfo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mountinfo"

#   github.com/moby/sys/sequential v0.5.0
# [1] git ls-remote https://github.com/moby/sys.git b22ba8a69b306f0b4adbbe2a529457e6283ed9f7
SRCREV_sequential="b22ba8a69b306f0b4adbbe2a529457e6283ed9f7"
SRC_URI += "git://github.com/moby/sys.git;name=sequential;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/sequential"

#   github.com/moby/sys/signal v0.7.0
# [1] git ls-remote https://github.com/moby/sys.git b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5
SRCREV_signal="b8d8fabf1fa5cf0de7c1a1729145eee854ea31f5"
SRC_URI += "git://github.com/moby/sys.git;name=signal;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/signal"

#   github.com/moby/sys/symlink v0.2.0
# [1] git ls-remote https://github.com/moby/sys.git 03b9f8d59a07f5206a2264105f4903a222aea964
SRCREV_symlink="03b9f8d59a07f5206a2264105f4903a222aea964"
SRC_URI += "git://github.com/moby/sys.git;name=symlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/symlink"

#   github.com/moby/sys/user v0.1.0
# [1] git ls-remote https://github.com/moby/sys.git c0711cde08c8fa33857a2c28721659267f49b5e2
SRCREV_user="c0711cde08c8fa33857a2c28721659267f49b5e2"
SRC_URI += "git://github.com/moby/sys.git;name=user;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/user"

#   github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
# [1] git ls-remote https://github.com/modern-go/concurrent.git bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
SRCREV_concurrent="bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent.git;name=concurrent;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/concurrent"

#   github.com/modern-go/reflect2 v1.0.2
# [1] git ls-remote https://github.com/modern-go/reflect2.git 2b33151c9bbc5231aea69b8861c540102b087070
SRCREV_reflect2="2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2.git;name=reflect2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/reflect2"

#   github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
# [1] git ls-remote https://github.com/munnerz/goautoneg.git a7dc8b61c822528f973a5e4e7b272055c6fdb43e
SRCREV_goautoneg="a7dc8b61c822528f973a5e4e7b272055c6fdb43e"
SRC_URI += "git://github.com/munnerz/goautoneg.git;name=goautoneg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/munnerz/goautoneg"

#   github.com/pelletier/go-toml v1.9.5
# [1] git ls-remote https://github.com/pelletier/go-toml.git fed1464066413075eac02cd4dc368b5221845541
SRCREV_go-toml="fed1464066413075eac02cd4dc368b5221845541"
SRC_URI += "git://github.com/pelletier/go-toml.git;name=go-toml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pelletier/go-toml"

#   github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors.git 614d223910a179a466c1767a985424175c39b465
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors.git;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

#   github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib.git c0b812dadcf4498dede02bb7f0c5c478be997e34
SRCREV_go-difflib="c0b812dadcf4498dede02bb7f0c5c478be997e34"
SRC_URI += "git://github.com/pmezard/go-difflib.git;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

#   github.com/prometheus/client_golang v1.16.0
# [1] git ls-remote https://github.com/prometheus/client_golang.git 3583c1e1d085b75cab406c78b015562d45552b39
SRCREV_client_golang="3583c1e1d085b75cab406c78b015562d45552b39"
SRC_URI += "git://github.com/prometheus/client_golang.git;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

#   github.com/prometheus/client_model v0.4.0
# [1] git ls-remote https://github.com/prometheus/client_model.git 91c3945f2cfbfb9040e34a0b6764d804b5a5a490
SRCREV_client_model="91c3945f2cfbfb9040e34a0b6764d804b5a5a490"
SRC_URI += "git://github.com/prometheus/client_model.git;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

#   github.com/prometheus/common v0.42.0
# [1] git ls-remote https://github.com/prometheus/common.git bdfacee9482b4ecedb0ab17b72b83e9aa9203199
SRCREV_common="bdfacee9482b4ecedb0ab17b72b83e9aa9203199"
SRC_URI += "git://github.com/prometheus/common.git;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

#   github.com/prometheus/procfs v0.10.1
# [1] git ls-remote https://github.com/prometheus/procfs.git 332e865adfebaa7eaedc94535a3f12f7e5eeb2d4
SRCREV_procfs="332e865adfebaa7eaedc94535a3f12f7e5eeb2d4"
SRC_URI += "git://github.com/prometheus/procfs.git;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

#   github.com/rivo/uniseg v0.2.0
# [1] git ls-remote https://github.com/rivo/uniseg.git 75711fccf6a3e85bc74c241e2dddd06a9bc9e53d
SRCREV_uniseg="75711fccf6a3e85bc74c241e2dddd06a9bc9e53d"
SRC_URI += "git://github.com/rivo/uniseg.git;name=uniseg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rivo/uniseg"

#   github.com/secure-systems-lab/go-securesystemslib v0.4.0
# [1] git ls-remote https://github.com/secure-systems-lab/go-securesystemslib.git 900aa2558e30069e21350cb1151d805c6e0c661d
SRCREV_go-securesystemslib="900aa2558e30069e21350cb1151d805c6e0c661d"
SRC_URI += "git://github.com/secure-systems-lab/go-securesystemslib.git;name=go-securesystemslib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/secure-systems-lab/go-securesystemslib"

#   github.com/serialx/hashring v0.0.0-20190422032157-8b2912629002
# [1] git ls-remote https://github.com/serialx/hashring.git 8b2912629002c928de72c69aae20c8600bef41a6
SRCREV_hashring="8b2912629002c928de72c69aae20c8600bef41a6"
SRC_URI += "git://github.com/serialx/hashring.git;name=hashring;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/serialx/hashring"

#   github.com/shibumi/go-pathspec v1.3.0
# [1] git ls-remote https://github.com/shibumi/go-pathspec.git ff20d718fefa5bcffc4d9f4da812042e428cff33
SRCREV_go-pathspec="ff20d718fefa5bcffc4d9f4da812042e428cff33"
SRC_URI += "git://github.com/shibumi/go-pathspec.git;name=go-pathspec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/shibumi/go-pathspec"

#   github.com/tonistiigi/fsutil v0.0.0-20230825212630-f09800878302
# [1] git ls-remote https://github.com/tonistiigi/fsutil.git f09800878302d3317064d14961ae81d034584552
SRCREV_fsutil="f09800878302d3317064d14961ae81d034584552"
SRC_URI += "git://github.com/tonistiigi/fsutil.git;name=fsutil;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/fsutil"

#   github.com/tonistiigi/units v0.0.0-20180711220420-6950e57a87ea
# [1] git ls-remote https://github.com/tonistiigi/units.git 6950e57a87eaf136bbe44ef2ec8e75b9e3569de2
SRCREV_units="6950e57a87eaf136bbe44ef2ec8e75b9e3569de2"
SRC_URI += "git://github.com/tonistiigi/units.git;name=units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/units"

#   github.com/tonistiigi/vt100 v0.0.0-20230623042737-f9a4f7ef6531
# [1] git ls-remote https://github.com/tonistiigi/vt100.git f9a4f7ef65311848d4d4791c649a178c8e97386b
SRCREV_vt100="f9a4f7ef65311848d4d4791c649a178c8e97386b"
SRC_URI += "git://github.com/tonistiigi/vt100.git;name=vt100;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tonistiigi/vt100"

#   github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
# [1] git ls-remote https://github.com/xeipuuv/gojsonpointer.git 02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb
SRCREV_gojsonpointer="02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb"
SRC_URI += "git://github.com/xeipuuv/gojsonpointer.git;name=gojsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonpointer"

#   github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
# [1] git ls-remote https://github.com/xeipuuv/gojsonreference.git bd5ef7bd5415a7ac448318e64f11a24cd21e594b
SRCREV_gojsonreference="bd5ef7bd5415a7ac448318e64f11a24cd21e594b"
SRC_URI += "git://github.com/xeipuuv/gojsonreference.git;name=gojsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonreference"

#   github.com/xeipuuv/gojsonschema v1.2.0
# [1] git ls-remote https://github.com/xeipuuv/gojsonschema.git 82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927
SRCREV_gojsonschema="82fcdeb203eb6ab2a67d0a623d9c19e5e5a64927"
SRC_URI += "git://github.com/xeipuuv/gojsonschema.git;name=gojsonschema;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonschema"

#   go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.45.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 9d4eb7e7706038b07d33f83f76afbe13f53d171d
SRCREV_otelgrpc="9d4eb7e7706038b07d33f83f76afbe13f53d171d"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelgrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"

#   go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace v0.45.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 9d4eb7e7706038b07d33f83f76afbe13f53d171d
SRCREV_otelhttptrace="9d4eb7e7706038b07d33f83f76afbe13f53d171d"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelhttptrace;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/net/http/httptrace/otelhttptrace"

#   go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.45.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 9d4eb7e7706038b07d33f83f76afbe13f53d171d
SRCREV_otelhttp="9d4eb7e7706038b07d33f83f76afbe13f53d171d"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelhttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"

#   go.opentelemetry.io/otel/exporters/otlp/otlpmetric v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlpmetric="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlpmetric;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlpmetric"

#   go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlpmetricgrpc="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlpmetricgrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetricgrpc"

#   go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlpmetrichttp="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlpmetrichttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlpmetric/otlpmetrichttp"

#   go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otlptracehttp="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otlptracehttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracehttp"

#   go.opentelemetry.io/otel/exporters/prometheus v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_prometheus="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=prometheus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/exporters/prometheus"

#   go.opentelemetry.io/otel/metric v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_metric="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=metric;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/metric"

#   go.opentelemetry.io/otel/sdk/metric v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_metricv1_19_0="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=metricv1_19_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel/sdk/metric"

#   go.opentelemetry.io/proto/otlp v1.0.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-proto-go 97744b2e4a0fa6787b96b9c3c740daefca754333
SRCREV_otlp="97744b2e4a0fa6787b96b9c3c740daefca754333"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-proto-go;name=otlp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/proto/otlp"

#   golang.org/x/crypto v0.18.0
# [1] git ls-remote https://go.googlesource.com/crypto dbb6ec16ecef7a66638d8514be54b13660551b0a
SRCREV_crypto="dbb6ec16ecef7a66638d8514be54b13660551b0a"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

#   golang.org/x/mod v0.14.0
# [1] git ls-remote https://go.googlesource.com/mod 6e58e47c7bd6672665dc35cce7b1f325d2addd67
SRCREV_mod="6e58e47c7bd6672665dc35cce7b1f325d2addd67"
SRC_URI += "git://go.googlesource.com/mod;name=mod;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/mod"

#   golang.org/x/net v0.20.0
# [1] git ls-remote https://go.googlesource.com/net cb5b10f0bbc51089bf49030ce3bd43bbfee08c23
SRCREV_net="cb5b10f0bbc51089bf49030ce3bd43bbfee08c23"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

#   golang.org/x/oauth2 v0.11.0
# [1] git ls-remote https://go.googlesource.com/oauth2 2e4a4e2bfb69ca7609cb423438c55caa131431c1
SRCREV_oauth2="2e4a4e2bfb69ca7609cb423438c55caa131431c1"
SRC_URI += "git://go.googlesource.com/oauth2;name=oauth2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/oauth2"

#   golang.org/x/term v0.16.0
# [1] git ls-remote https://go.googlesource.com/term ae941452f58ff9bf62f7e9dca3ea6ae3d214a68b
SRCREV_termv0_16_0="ae941452f58ff9bf62f7e9dca3ea6ae3d214a68b"
SRC_URI += "git://go.googlesource.com/term;name=termv0_16_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

#   golang.org/x/text v0.14.0
# [1] git ls-remote https://go.googlesource.com/text 6c97a165dd661335ff7bce6104a008558123c353
SRCREV_text="6c97a165dd661335ff7bce6104a008558123c353"
SRC_URI += "git://go.googlesource.com/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

#   golang.org/x/time v0.3.0
# [1] git ls-remote https://go.googlesource.com/time 2c09566ef13fb5556401ddff3c53c3dbc2a42dac
SRCREV_time="2c09566ef13fb5556401ddff3c53c3dbc2a42dac"
SRC_URI += "git://go.googlesource.com/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"

#   golang.org/x/tools v0.17.0
# [1] git ls-remote https://go.googlesource.com/tools 0b1f1d4bc227cc2e610854f23e14696becb9e46c
SRCREV_tools="0b1f1d4bc227cc2e610854f23e14696becb9e46c"
SRC_URI += "git://go.googlesource.com/tools;name=tools;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/tools"

#   google.golang.org/appengine v1.6.7
# [1] git ls-remote https://github.com/golang/appengine 5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a
SRCREV_appengine="5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a"
SRC_URI += "git://github.com/golang/appengine;name=appengine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/appengine"

#   google.golang.org/genproto v0.0.0-20230822172742-b8732ec3820d
# [1] git ls-remote https://github.com/googleapis/go-genproto b8732ec3820db4bd1e4eda89392b7728e81bd825
SRCREV_genproto="b8732ec3820db4bd1e4eda89392b7728e81bd825"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto"

#   google.golang.org/genproto/googleapis/api v0.0.0-20230822172742-b8732ec3820d
# [1] git ls-remote https://github.com/googleapis/go-genproto b8732ec3820db4bd1e4eda89392b7728e81bd825
SRCREV_api="b8732ec3820db4bd1e4eda89392b7728e81bd825"
SRC_URI += "git://github.com/googleapis/go-genproto;name=api;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto/googleapis/api"

#   google.golang.org/genproto/googleapis/rpc v0.0.0-20230822172742-b8732ec3820d
# [1] git ls-remote https://github.com/googleapis/go-genproto b8732ec3820db4bd1e4eda89392b7728e81bd825
SRCREV_rpc="b8732ec3820db4bd1e4eda89392b7728e81bd825"
SRC_URI += "git://github.com/googleapis/go-genproto;name=rpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto/googleapis/rpc"

#   google.golang.org/protobuf v1.31.0
# [1] git ls-remote https://go.googlesource.com/protobuf 68463f0e96c93bc19ef36ccd3adfe690bfdb568c
SRCREV_protobufv1_31_0="68463f0e96c93bc19ef36ccd3adfe690bfdb568c"
SRC_URI += "git://go.googlesource.com/protobuf;name=protobufv1_31_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/protobuf"

#   gopkg.in/inf.v0 v0.9.1
# [1] git ls-remote https://gopkg.in/inf.v0 d2d2541c53f18d2a059457998ce2876cc8e67cbf
SRCREV_inf.v0="d2d2541c53f18d2a059457998ce2876cc8e67cbf"
SRC_URI += "git://gopkg.in/inf.v0;name=inf.v0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/inf.v0"

#   gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2 7649d4548cb53a614db133b2a8ac1f31859dda8c
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

#   k8s.io/api v0.26.7
# [1] git ls-remote https://github.com/kubernetes/api 555a165748067975c277bc93b7effc3d4e87d890
SRCREV_apiv0_26_7="555a165748067975c277bc93b7effc3d4e87d890"
SRC_URI += "git://github.com/kubernetes/api;name=apiv0_26_7;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/api"

#   k8s.io/apimachinery v0.26.7
# [1] git ls-remote https://github.com/kubernetes/apimachinery edb3e0f235766be2c13003f47e9f558f77ac0f50
SRCREV_apimachinery="edb3e0f235766be2c13003f47e9f558f77ac0f50"
SRC_URI += "git://github.com/kubernetes/apimachinery;name=apimachinery;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/apimachinery"

#   k8s.io/apiserver v0.26.7
# [1] git ls-remote https://github.com/kubernetes/apiserver a7536614b462367370988fc6da2d0b054b369c15
SRCREV_apiserver="a7536614b462367370988fc6da2d0b054b369c15"
SRC_URI += "git://github.com/kubernetes/apiserver;name=apiserver;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/apiserver"

#   k8s.io/client-go v0.26.7
# [1] git ls-remote https://github.com/kubernetes/client-go 937bbff8a47d051d31220e622deb53a721baa30e
SRCREV_client-go="937bbff8a47d051d31220e622deb53a721baa30e"
SRC_URI += "git://github.com/kubernetes/client-go;name=client-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/client-go"

#   k8s.io/klog/v2 v2.90.1
# [1] git ls-remote https://github.com/kubernetes/klog d7fc50528570f8276de46570f916682257821e22
SRCREV_v2v2_90_1="d7fc50528570f8276de46570f916682257821e22"
SRC_URI += "git://github.com/kubernetes/klog;name=v2v2_90_1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/klog/v2"

#   k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280
# [1] git ls-remote https://github.com/kubernetes/kube-openapi 172d655c2280350c77cf05962948fc67ff043492
SRCREV_kube-openapi="172d655c2280350c77cf05962948fc67ff043492"
SRC_URI += "git://github.com/kubernetes/kube-openapi;name=kube-openapi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/kube-openapi"

#   k8s.io/utils v0.0.0-20230220204549-a5ecb0141aa5
# [1] git ls-remote https://github.com/kubernetes/utils a5ecb0141aa5b1b224e745aca203afdfd22d8b3a
SRCREV_utils="a5ecb0141aa5b1b224e745aca203afdfd22d8b3a"
SRC_URI += "git://github.com/kubernetes/utils;name=utils;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/utils"

#   sigs.k8s.io/json v0.0.0-20220713155537-f223a00ba0e2
# [1] git ls-remote https://github.com/kubernetes-sigs/json f223a00ba0e27f539157f69f9c919c204ea7f40b
SRCREV_json="f223a00ba0e27f539157f69f9c919c204ea7f40b"
SRC_URI += "git://github.com/kubernetes-sigs/json;name=json;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/json"

#   sigs.k8s.io/structured-merge-diff/v4 v4.2.3
# [1] git ls-remote https://github.com/kubernetes-sigs/structured-merge-diff 26781d0c10bfdbd7d66b18d8be83985f623df9f8
SRCREV_v4v4_2_3="26781d0c10bfdbd7d66b18d8be83985f623df9f8"
SRC_URI += "git://github.com/kubernetes-sigs/structured-merge-diff;name=v4v4_2_3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/structured-merge-diff/v4"

#   sigs.k8s.io/yaml v1.3.0
# [1] git ls-remote https://github.com/kubernetes-sigs/yaml 9535b3b1e2893fe44efb37c5c9f5665e245d786a
SRCREV_yaml="9535b3b1e2893fe44efb37c5c9f5665e245d786a"
SRC_URI += "git://github.com/kubernetes-sigs/yaml;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/yaml"

#   tags.cncf.io/container-device-interface v0.6.2
# [1] git ls-remote https://github.com/cncf-tags/container-device-interface fb50bf8fc8b2c3c8fda6d23ab7e044774dcca678
SRCREV_container-device-interface="fb50bf8fc8b2c3c8fda6d23ab7e044774dcca678"
SRC_URI += "git://github.com/cncf-tags/container-device-interface;name=container-device-interface;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/tags.cncf.io/container-device-interface"

