#!/bin/sh

KEY_LOCATION_CA="/etc/ssl/private/iotedge-ca"

# Calculcate days to 2038 (which is the current limit of iotedge)
today=$(date +%s)
lastday=$(date +%s -d 01/01/2038)
maxvalidity=$((($lastday - $today) / 86400))

generate_ca_key_and_cert() {
    subject="$1"

    mkdir -p ${KEY_LOCATION_CA}

    openssl genpkey \
            -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
            -out ${KEY_LOCATION_CA}/privkey.pem

    chown aziotks:aziotks ${KEY_LOCATION_CA}/privkey.pem
    chmod 0640 ${KEY_LOCATION_CA}/privkey.pem

    openssl rsa -in ${KEY_LOCATION_CA}/privkey.pem -pubout > ${KEY_LOCATION_CA}/pubkey.pem

    # root CA (self-signed)
    openssl req \
            -new -x509 \
            -key ${KEY_LOCATION_CA}/privkey.pem \
            -subj "$subject" \
            -days $maxvalidity \
            -sha512 \
            -extensions "v3_ca" \
            -out ${KEY_LOCATION_CA}/cert.pem

    chown aziotcs:aziotcs ${KEY_LOCATION_CA}/cert.pem
    chmod 0644 ${KEY_LOCATION_CA}/cert.pem
}

if [ ! -e "/etc/aziot/config.toml" ]; then
	echo "/etc/aziot/config.toml is missing. Exiting"
	exit 0
fi

update_config_toml="1"
if grep -q "\[edge_ca\]" /etc/aziot/config.toml; then
	echo "Custom certificates detected. Assuming already patched config.toml"
	update_config_toml="0"
fi

update_keys="0"

size_cert=$(stat -c %s ${KEY_LOCATION_CA}/cert.pem 2>/dev/null || echo "0")
size_key=$(stat -c %s ${KEY_LOCATION_CA}/privkey.pem 2>/dev/null || echo "0")
if [ "$size_cert" = "0" ] || [ "$size_key" = "0" ]; then
	echo "No valid CA key and certificate found, re-generating"
	update_keys="1"
elif ! openssl rsa -in ${KEY_LOCATION_CA}/privkey.pem -check -noout >/dev/null 2>&1; then
	echo "Invalid private key for CA, re-generating"
	update_keys="1"
else
	cert_modulus=$(openssl x509 -noout -modulus -in ${KEY_LOCATION_CA}/cert.pem 2>/dev/null)
	key_modulus=$(openssl rsa -noout -modulus -in ${KEY_LOCATION_CA}/privkey.pem 2>/dev/null)
	if [ "$key_modulus" != "$cert_modulus" ]; then
		echo "Private key and certificate do not match, re-generating"
		update_keys="1"
	else
		echo "Found valid CA key and certificate. Skipping generation"
	fi
fi

if [ "$update_keys" = "1" ]; then
	generate_ca_key_and_cert "/CN=$(hostname)-local-owner-ca"
fi

if [ "$update_config_toml" = "1" ]; then
	# Adjust super config
	cat <<EOF>>/etc/aziot/config.toml

[edge_ca]
cert = "file://${KEY_LOCATION_CA}/cert.pem"
pk = "file://${KEY_LOCATION_CA}/privkey.pem"
EOF

	# Delete previously generated CA certificates (if any)
	rm -f /var/lib/aziot/certd/certs/* /var/lib/aziot/keyd/keys/*

	OMIT_SERVICE_RESTART=1 iotedge config apply
fi
