hostname = "null"

[provisioning]
source = "manual"
connection_string = "null"

[agent]
name = "edgeAgent"
type = "docker"

  [agent.config]
  image = "mcr.microsoft.com/azureiotedge-agent:1.5"

  [agent.env]
  UpstreamProtocol = "AmqpWs"
