#!/bin/sh

KEY_LOCATION_DEVICE="/etc/ssl/private/iotedge-device"
KEY_LOCATION_CA="/etc/ssl/private/iotedge-ca"

keys_to_check=" \
 device_ca_cert;${KEY_LOCATION_DEVICE}/cert.pem \
 device_ca_pk;${KEY_LOCATION_DEVICE}/privkey.pem \
 trusted_ca_certs;${KEY_LOCATION_CA}/cert.pem"

# Calculcate days to 2038 (which is the current limit of iotedge)
today=$(date +%s)
lastday=$(date +%s -d 01/01/2038)
maxvalidity=$((($lastday - $today) / 86400))

delete_certs="false"

check_and_generate_key_and_cert() {
    path="$1"
    subject="$2"
    crt_ext="$3"
    if [ ! -e "$path/privkey.pem" ]; then
        openssl genpkey \
                -algorithm RSA -pkeyopt rsa_keygen_bits:2048 \
                -out $path/privkey.pem
        chgrp iotedge $path/privkey.pem
        chmod g+r $path/privkey.pem
    fi
    if [ ! -e "$path/pubkey.pem" ]; then
        openssl rsa -in $path/privkey.pem -pubout > $path/pubkey.pem
    fi

    key_modulus=$(openssl rsa -noout -modulus -in $path/privkey.pem 2> /dev/null)
    cert_modulus=$(openssl x509 -noout -modulus -in $path/cert.pem 2> /dev/null)
    if [ "$key_modulus" != "$cert_modulus" ]; then
        delete_certs="true"
        if [ "$crt_ext" = "v3_ca" ]; then
            # root CA (self-signed)
            openssl req \
                    -new -x509 \
                    -key $path/privkey.pem \
                    -subj "$subject" \
                    -days $maxvalidity \
                    -sha512 \
                    -extensions "v3_ca" \
                    -out $path/cert.pem
        else
            # Create CSR
            openssl req \
                    -key $path/privkey.pem \
                    -out $path/csr.pem \
                    -new \
                    -subj "$subject" \
                    -sha512

            # CA-sign CSR
            tmpdir=$(mktemp -d)
            cat <<EOF> $tmpdir/config
[ca]
default_ca    = CA_default

[ CA_default ]
# Directory and file locations.
dir           = $tmpdir
certs         = $tmpdir/certs
crl_dir       = $tmpdir/crl
new_certs_dir = $tmpdir/newcerts
database      = $tmpdir/index.txt
serial        = $tmpdir/serial
RANDFILE      = $tmpdir/.rnd
default_md    = sha512
policy        = policy_loose

[ policy_loose ]
# Allow the intermediate CA to sign a more diverse range of certificates.
countryName             = optional
stateOrProvinceName     = optional
localityName            = optional
organizationName        = optional
organizationalUnitName  = optional
commonName              = supplied
emailAddress            = optional

[ v3_intermediate_ca ]
# Extensions for a typical intermediate CA.
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer:always
basicConstraints = critical, CA:true
keyUsage = critical, digitalSignature, cRLSign, keyCertSign
EOF
            touch $tmpdir/index.txt
            mkdir -p $tmpdir/certs $tmpdir/crl $tmpdir/newcerts
            hexdump -n 4 -e '1/4 "%08X""\n"' /dev/urandom > $tmpdir/serial
            echo "unique_subject = yes" > $tmpdir/index.txt.attr

            openssl ca \
                    -batch \
                    -config "$tmpdir/config" \
                    -extensions "$crt_ext" \
                    -days $maxvalidity \
                    -cert ${KEY_LOCATION_CA}/cert.pem \
                    -keyfile ${KEY_LOCATION_CA}/privkey.pem -keyform PEM \
                    -in $path/csr.pem \
                    -out $path/cert.pem \
                    -outdir $tmpdir

            # Add local-owner-ca certificate to intermediate certificate to be able to verify chain in iotedged
            cat ${KEY_LOCATION_CA}/cert.pem >> $path/cert.pem

            rm -rf $tmpdir
        fi
    fi
}

check_default_certificates="1"

# Check if iotedged's config.yaml contains required keys
for entry in $keys_to_check; do
    key=$(echo $entry | cut -d ';' -f1)
    defvalue=$(echo $entry | cut -d ';' -f2)

    check=$(yq eval ".certificates.${key}" /etc/iotedge/config.yaml | sed -e 's@file://@@g')
    if [ "$check" = "null" ]; then
        yq --inplace eval ".certificates.${key}=\"file://${defvalue}\" | .certificates.${key} style=\"double\"" /etc/iotedge/config.yaml
        check="$defvalue"
    fi

    if [ "$check" != "$defvalue" ]; then
        echo "Detected manually modified config.yaml ($check != $defvalue), skipping certificate checking/generation"
        check_default_certificates="0"
        break
    fi
done

if [ "$check_default_certificates" = "1" ]; then
    mkdir -p ${KEY_LOCATION_CA} ${KEY_LOCATION_DEVICE}

    check_and_generate_key_and_cert "${KEY_LOCATION_CA}" "/CN=$(hostname)-local-owner-ca" "v3_ca"
    check_and_generate_key_and_cert "${KEY_LOCATION_DEVICE}" "/CN=$(hostname)-local-device-ca" "v3_intermediate_ca"

    if [ "$delete_certs" = "true" ]; then
        rm -rf /var/lib/iotedge/hsm/certs/* /var/lib/iotedge/hsm/cert_keys/*
    fi
fi

# Add max validity parameter if not existing
check=$(yq eval ".certificates.auto_generated_ca_lifetime_days" /etc/iotedge/config.yaml)
if [ "$check" = "null" ]; then
    yq --inplace eval ".certificates.auto_generated_ca_lifetime_days=365 | .certificates.auto_generated_ca_lifetime_days style=\"\"" /etc/iotedge/config.yaml
    delete_certs="true"
fi

if [ "$delete_certs" = "true" ]; then
    rm -rf /var/lib/iotedge/hsm/certs/* /var/lib/iotedge/hsm/cert_keys/*
fi
