# /etc/security/pam_abl.conf
#debug

# Database location
db_home=/var/lib/abl

# data base module
user_db=/var/lib/abl/user.db
host_db=/var/lib/abl/host.db

# Black-list any remote host with 10 consecutive authentication failures
# in one hour, or 30 in one day.  Keep them in the black-list for a day
# and then purge them.
host_purge=1d
host_rule=*:10/1h,30/1d
#host_block_cmd=[logger] [block] [host] [%h]
#host_clear_cmd=[logger] [clear] [host] [%h]
# uncomment the next lines to completly drop network traffic from host while blocked
#host_block_cmd=[/usr/sbin/iptables] [-I] [INPUT] [-s] [%h] [-j] [DROP]
#host_clear_cmd=[/usr/sbin/iptables] [-D] [INPUT] [-s] [%h] [-j] [DROP]

# Black-list any local user for which there are 10 consecutive 
# authentication failures in one hour, or 30 in one day.
# Keep them in the black-list for a day and then purge them.
# Note that this means that users may be subjected to denial of
# service attacks caused by remote password guessing.
#user_purge=1d
#user_rule=*:10/1h,30/1d
#user_clear_cmd=[logger] [clear] [user] [%u]
#user_block_cmd=[logger] [block] [user] [%u]

limits=1000-1200
