#!/bin/sh

BACKUP_DIR="/backup/updateapparmor"

updateapparmor_preoverlay() {
	mkdir -p ${BACKUP_DIR}
	cp -r /rootfs/etc/apparmor.d/* ${BACKUP_DIR}/
}

updateapparmor_postoverlay() {
	echo "Updating apparmor rules..."
	cp -r ${BACKUP_DIR}/* ${ROOTFS_DIR}/etc/apparmor.d/
	sync
}
