# https://kb.hilscher.com/pages/viewpage.action?spaceKey=NETXSYS&title=File+system+layout

# --------------------------------------
PLATFORM_SIGN ??= "0"
PLATFORM_KEYDIR ??= ""
PLATFORM_KEYNAME ??= ""

# --------------------------------------
INITRAMFS_IMAGE ?= "core-image-minimal-initramfs"
# NOTE: INITRAMFS_IMAGE_NAME is defined in kernel.bbclass so we have to define it here as well
#       to be able to reference it in other recipes (which do not inherit the class).
INITRAMFS_IMAGE_NAME ?= "${@['${INITRAMFS_IMAGE}-${MACHINE}', ''][d.getVar('INITRAMFS_IMAGE') == '']}"

# --------------------------------------
IMAGE_CLASSES_append += "hilscher_image_types"
IMAGE_FSTYPES += "wic.bz2 swu licenses.tar.bz2"

# --------------------------------------
PART_SCHEME ??= "boot-rescue-system-lvm"
WKS_SEARCH_PATH_prepend = "${TOPDIR}/../meta-hilscher-distro/files/part-schemes/${PART_SCHEME}:"
WKS_FILES_prepend =+ "hilscher-wic-image.wks.in"

HILSCHER_RESCUE_IMAGE ??= "hilscher-rescue-image"

HILSCHER_OVERLAY ??= "/dev/mapper/data-data"
HILSCHER_OVERLAYTARGETS ??= "rootfs"

##WIC_BOOT_PART_BASE_CONTENT ??= ""
WIC_BOOT_PART_EXTRA_CONTENT ??= "netx.rom;netx.rom"

##WIC_RESCUE_PART_BASE_CONTENT ??= "${HILSCHER_RESCUE_IMAGE_LINK_NAME}.squashfs"
WIC_RESCUE_PART_EXTRA_CONTENT ??= "rboot.cfg fitImage initrd-api-part-cfg;initrd-api"

##WIC_SYSTEM_PART_BASE_CONTENT ??= "${IMAGE_LINK_NAME}.squashfs"
WIC_SYSTEM_PART_EXTRA_CONTENT ??= "boot.cfg fitImage"

SWU_RSYNC_PART_UPDATE ??= "boot system"

##SWU_BOOT_PART_BASE_CONTENT ??= "${WIC_BOOT_PART_BASE_CONTENT}"
SWU_BOOT_PART_EXTRA_CONTENT ??= ""

##SWU_SYSTEM_PART_BASE_CONTENT ??= "${WIC_SYSTEM_PART_BASE_CONTENT}"
SWU_SYSTEM_PART_EXTRA_CONTENT ??= "nboot.cfg fitImage"

# Physical device of system partitions
PHYSICAL_SYSTEM_DEVICE ??= "/dev/mmcblk0"

# Size of boot partition
IMAGE_PART_BOOT_SIZE ??= "16M"

# Size of rescue partition
IMAGE_PART_RESCUE_SIZE ??= "128M"

# Size of system partition
IMAGE_PART_SYSTEM_SIZE ??= "2G"

# Size of data partition
IMAGE_PART_DATA_SIZE ??= "max"

# Size of logical volume "data" in userdata partition
PART_DATA_LV_DATA_SIZE ??= "60%VG"

# Size of logical volume "backup" in userdata partition
PART_DATA_LV_BACKUP_SIZE ??= "35%VG"

# Size of logical volume "snapshot" in userdata partition
PART_DATA_LV_SNAPSHOT_SIZE ??= "5%VG"
