#   github.com/elliotchance/orderedmap v1.3.0
# [1] git ls-remote https://github.com/elliotchance/orderedmap.git 5498093722c63dd8ce9de086a8d97e687e22d78f
SRCREV_orderedmap="5498093722c63dd8ce9de086a8d97e687e22d78f"
SRC_URI += "git://github.com/elliotchance/orderedmap.git;name=orderedmap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/elliotchance/orderedmap"

#   github.com/fatih/color v1.10.0
# [1] git ls-remote https://github.com/fatih/color.git bc2269661d49c6c9d0e514eef49710556883f3fa
SRCREV_color="bc2269661d49c6c9d0e514eef49710556883f3fa"
SRC_URI += "git://github.com/fatih/color.git;name=color;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fatih/color"

#   github.com/goccy/go-yaml v1.8.4
# [1] git ls-remote https://github.com/goccy/go-yaml.git bdb73b469f3cada6f5f8749b21e06f6c77e48540
SRCREV_go-yaml="bdb73b469f3cada6f5f8749b21e06f6c77e48540"
SRC_URI += "git://github.com/goccy/go-yaml.git;name=go-yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/goccy/go-yaml"

#   github.com/jinzhu/copier v0.1.0
# [1] git ls-remote https://github.com/jinzhu/copier.git fc254513a8dcc0d7605f87d87976b937be68c181
SRCREV_copier="fc254513a8dcc0d7605f87d87976b937be68c181"
SRC_URI += "git://github.com/jinzhu/copier.git;name=copier;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jinzhu/copier"

#   github.com/spf13/cobra v1.1.1
# [1] git ls-remote https://github.com/spf13/cobra.git 86f8bfd7fef868a174e1b606783bd7f5c82ddf8f
SRCREV_cobra="86f8bfd7fef868a174e1b606783bd7f5c82ddf8f"
SRC_URI += "git://github.com/spf13/cobra.git;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

#   github.com/timtadh/data-structures v0.5.3
# [1] git ls-remote https://github.com/timtadh/data-structures.git a129e3f22e38b4028f45cc3b77b98149884f4c75
SRCREV_data-structures="a129e3f22e38b4028f45cc3b77b98149884f4c75"
SRC_URI += "git://github.com/timtadh/data-structures.git;name=data-structures;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/timtadh/data-structures"

#   github.com/timtadh/lexmachine v0.2.2
# [1] git ls-remote https://github.com/timtadh/lexmachine.git cde49191c807daa1fd820e1c424cea6a73c47858
SRCREV_lexmachine="cde49191c807daa1fd820e1c424cea6a73c47858"
SRC_URI += "git://github.com/timtadh/lexmachine.git;name=lexmachine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/timtadh/lexmachine"

#   golang.org/x/sys v0.0.0-20210105210732-16f7687f5001
# [1] git ls-remote https://go.googlesource.com/sys 16f7687f5001b816ff9f6b586071238941e88a9d
SRCREV_sys="16f7687f5001b816ff9f6b586071238941e88a9d"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#   gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
# [1] git ls-remote https://gopkg.in/op/go-logging.v1 b2cb9fa56473e98db8caba80237377e83fe44db5
SRCREV_go-logging.v1="b2cb9fa56473e98db8caba80237377e83fe44db5"
SRC_URI += "git://gopkg.in/op/go-logging.v1;name=go-logging.v1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/op/go-logging.v1"

#   gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
# [1] git ls-remote https://gopkg.in/yaml.v3 496545a6307b2a7d7a710fd516e5e16e8ab62dbc
SRCREV_yaml.v3="496545a6307b2a7d7a710fd516e5e16e8ab62dbc"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#  github.com/mattn/go-colorable v0.1.8
# [1] git ls-remote https://github.com/mattn/go-colorable 2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1
SRCREV_go_colorable="2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1"
SRC_URI += "git://github.com/mattn/go-colorable;name=go_colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

#  github.com/mattn/go-isatty v0.0.12
# [1] git ls-remote https://github.com/mattn/go-isatty 7b513a986450394f7bbf1476909911b3aa3a55ce
SRCREV_go_isatty="7b513a986450394f7bbf1476909911b3aa3a55ce"
SRC_URI += "git://github.com/mattn/go-isatty;name=go_isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

#  github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

#   golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
# [1] git ls-remote https://go.googlesource.com/xerrors 5ec99f83aff198f5fbd629d6c8d8eb38a04218ca
SRCREV_xerrors="5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
SRC_URI += "git://go.googlesource.com/xerrors;name=xerrors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/xerrors"
