SUMMARY = "User space tools for kernel auditing"
DESCRIPTION = "The audit package contains the user space utilities for \
storing and searching the audit records generated by the audit subsystem \
in the Linux kernel."
HOMEPAGE = "http://people.redhat.com/sgrubb/audit/"
SECTION = "base"
LICENSE = "GPLv2+ & LGPLv2+"
LIC_FILES_CHKSUM = "file://COPYING;md5=94d55d512a9ba36caa9b7df079bae19f"

SRC_URI = "http://people.redhat.com/sgrubb/${BPN}/${BPN}-${PV}.tar.gz \
           file://auditd \
           file://auditd.service \
           file://audit-volatile.conf \
"
SRC_URI[sha256sum] = "b5f4d9b9ad69381ee18f33d3d918326aa52861509c901143f8a8c4ed5caa8913"

inherit autotools python3native update-rc.d systemd

UPDATERCPN = "auditd"
INITSCRIPT_NAME = "auditd"
INITSCRIPT_PARAMS = "defaults"

SYSTEMD_PACKAGES = "auditd"
SYSTEMD_SERVICE:auditd = "auditd.service"

DEPENDS += "tcp-wrappers libcap-ng linux-libc-headers (>= 2.6.30)"

PACKAGECONFIG ??= "python"
PACKAGECONFIG[python] = "--with-python3=yes,--with-python3=no,python3 swig-native"

EXTRA_OECONF += " \
	--with-libwrap \
	--enable-gssapi-krb5=no \
	--with-libcap-ng=yes \
	--libdir=${libdir} \
	--sbindir=${base_sbindir} \
	--without-python \
	--disable-zos-remote \
	"
EXTRA_OECONF:append:arm = " --with-arm=yes"

EXTRA_OEMAKE += "PYLIBVER='python${PYTHON_BASEVERSION}' \
	PYINC='${STAGING_INCDIR}/$(PYLIBVER)' \
	pyexecdir=${libdir}/python${PYTHON_BASEVERSION}/site-packages \
	STDINC='${STAGING_INCDIR}' \
	"

SUMMARY:audispd-plugins = "Plugins for the audit event dispatcher"
DESCRIPTION:audispd-plugins = "The audispd-plugins package provides plugins for the real-time \
interface to the audit system, audispd. These plugins can do things \
like relay events to remote machines or analyze events for suspicious \
behavior."

PACKAGES =+ "audispd-plugins"
PACKAGES =+ "auditd ${PN}-python"

FILES:${PN} = "${sysconfdir}/libaudit.conf ${libdir}/libaudit.so.1* ${libdir}/libauparse.so.*"
FILES:auditd += "${bindir}/* ${base_sbindir}/* ${sysconfdir}/* ${systemd_unitdir}/system ${datadir}/audit"
FILES:audispd-plugins += "${sysconfdir}/audisp/audisp-remote.conf \
	${sysconfdir}/audisp/plugins.d/au-remote.conf \
	${sbindir}/audisp-remote ${localstatedir}/spool/audit \
	"
FILES:${PN}-dbg += "${libdir}/python${PYTHON_BASEVERSION}/*/.debug"
FILES:${PN}-python = "${libdir}/python${PYTHON_BASEVERSION}"
FILES:${PN}-dev += "${libdir}/*.so ${libdir}/*.la ${libdir}/pkgconfig/*"

CONFFILES:auditd += "${sysconfdir}/audit/audit.rules"
RDEPENDS:auditd += "bash"

do_install:append() {
	rm -f ${D}/${libdir}/python${PYTHON_BASEVERSION}/site-packages/*.a
	rm -f ${D}/${libdir}/python${PYTHON_BASEVERSION}/site-packages/*.la

	# reuse auditd config
	[ ! -e ${D}/etc/default ] && mkdir ${D}/etc/default
	mv ${D}/etc/sysconfig/auditd ${D}/etc/default
	rmdir ${D}/etc/sysconfig/

	# replace init.d
	install -D -m 0755 ${S}/../auditd ${D}/etc/init.d/auditd
	rm -rf ${D}/etc/rc.d

	if ${@bb.utils.contains('DISTRO_FEATURES', 'systemd', 'true', 'false', d)}; then
		install -d ${D}${sysconfdir}/tmpfiles.d/
		install -m 0644 ${WORKDIR}/audit-volatile.conf ${D}${sysconfdir}/tmpfiles.d/
		rm -rf ${D}${libexecdir}/initscripts
	fi

	if ${@bb.utils.contains('DISTRO_FEATURES', 'selinux', 'true', 'false', d)}; then
		:
	else
		sed -i '/selinux/d' ${D}${datadir}/audit/sample-rules/*
	fi

	# install systemd unit files
	install -d ${D}${systemd_unitdir}/system
	install -m 0644 ${WORKDIR}/auditd.service ${D}${systemd_unitdir}/system

	# audit-2.5 doesn't install any rules by default, so we do that here
	mkdir -p ${D}/etc/audit ${D}/etc/audit/rules.d
	ln -s ${datadir}/audit/sample-rules/10-base-config.rules ${D}/etc/audit/rules.d/

	chmod 750 ${D}/etc/audit ${D}/etc/audit/rules.d
	chmod 640 ${D}/etc/audit/auditd.conf ${D}${datadir}/audit/sample-rules/*

	# Based on the audit.spec "Copy default rules into place on new installation"
	cp ${D}${datadir}/audit/sample-rules/10-base-config.rules ${D}/etc/audit/audit.rules

	# Remove unsupported go stuff for now
	rm -rf ${D}/${libdir}/golang
}
