# Use sstate-cache from build server or local mounted nfs
SSTATE_MIRRORS ?= "file://.* file:///opt/shared/yocto/sstate-cache/netiot/2.0/PATH \
                   file://.* http://nxybuilder01/sstate-cache/netiot/2.0/PATH \
                   file://.* http://nxybuilder01.hilscher.local/sstate-cache/netiot/2.0/PATH"

# Try tarballs from own local mirror
SOURCE_MIRROR_URL ?= "http://nxybuilder01/sources-mirror/"
INHERIT += "own-mirrors"
