#   github.com/OneOfOne/xxhash v1.2.8
# [1] git ls-remote https://github.com/OneOfOne/xxhash.git 73388e8298b5e5a3611e6b62c2fc41b1b108491e
SRCREV_xxhash="73388e8298b5e5a3611e6b62c2fc41b1b108491e"
SRC_URI += "git://github.com/OneOfOne/xxhash.git;name=xxhash;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/OneOfOne/xxhash"

#   github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks.git c49ff274687222a7373c4cd83578f1065cf3e143
SRCREV_perks="c49ff274687222a7373c4cd83578f1065cf3e143"
SRC_URI += "git://github.com/beorn7/perks.git;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

#   github.com/bytecodealliance/wasmtime-go v0.28.0
# [1] git ls-remote https://github.com/bytecodealliance/wasmtime-go.git b4e0103693087511b7af078a4b454136b1e8ca26
SRCREV_wasmtime-go="b4e0103693087511b7af078a4b454136b1e8ca26"
SRC_URI += "git://github.com/bytecodealliance/wasmtime-go.git;name=wasmtime-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/bytecodealliance/wasmtime-go"

#   github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew.git 152484fe5c9ff65d013f0f372d748c03e8749e6d
SRCREV_go-spew="152484fe5c9ff65d013f0f372d748c03e8749e6d"
SRC_URI += "git://github.com/davecgh/go-spew.git;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

#   github.com/fortytw2/leaktest v1.3.0
# [1] git ls-remote https://github.com/fortytw2/leaktest.git 9a23578d06a26ec1b47bfc8965bf5e7011df8bd6
SRCREV_leaktest="9a23578d06a26ec1b47bfc8965bf5e7011df8bd6"
SRC_URI += "git://github.com/fortytw2/leaktest.git;name=leaktest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fortytw2/leaktest"

#   github.com/fsnotify/fsnotify v1.4.9
# [1] git ls-remote https://github.com/fsnotify/fsnotify.git 45d7d09e39ef4ac08d493309fa031790c15bfe8a
SRCREV_fsnotify="45d7d09e39ef4ac08d493309fa031790c15bfe8a"
SRC_URI += "git://github.com/fsnotify/fsnotify.git;name=fsnotify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fsnotify/fsnotify"

#   github.com/ghodss/yaml v1.0.0
# [1] git ls-remote https://github.com/ghodss/yaml.git 0ca9ea5df5451ffdf184b4428c902747c2c11cd7
SRCREV_yaml="0ca9ea5df5451ffdf184b4428c902747c2c11cd7"
SRC_URI += "git://github.com/ghodss/yaml.git;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ghodss/yaml"

#   github.com/gobwas/glob v0.2.3
# [1] git ls-remote https://github.com/gobwas/glob.git 1dc80ac100b2114a77baa597fd7562057167b532
SRCREV_glob="1dc80ac100b2114a77baa597fd7562057167b532"
SRC_URI += "git://github.com/gobwas/glob.git;name=glob;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gobwas/glob"

#   github.com/golang/protobuf v1.4.3
# [1] git ls-remote https://github.com/golang/protobuf.git 4846b58453b3708320bdb524f25cc5a1d9cda4d4
SRCREV_protobuf="4846b58453b3708320bdb524f25cc5a1d9cda4d4"
SRC_URI += "git://github.com/golang/protobuf.git;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

#   github.com/google/go-cmp v0.5.4
# [1] git ls-remote https://github.com/google/go-cmp.git ec71d6d790538ad88c95a192fd059e11afb45b6f
SRCREV_go-cmp="ec71d6d790538ad88c95a192fd059e11afb45b6f"
SRC_URI += "git://github.com/google/go-cmp.git;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

#   github.com/gorilla/mux v1.8.0
# [1] git ls-remote https://github.com/gorilla/mux.git 98cb6bf42e086f6af920b965c38cacc07402d51b
SRCREV_mux="98cb6bf42e086f6af920b965c38cacc07402d51b"
SRC_URI += "git://github.com/gorilla/mux.git;name=mux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/mux"

#   github.com/inconshreveable/mousetrap v1.0.0
# [1] git ls-remote https://github.com/inconshreveable/mousetrap.git 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
SRCREV_mousetrap="76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
SRC_URI += "git://github.com/inconshreveable/mousetrap.git;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

#   github.com/kr/text v0.2.0
# [1] git ls-remote https://github.com/kr/text.git 0e5f52c28dd72ab84daeb81b5a51f20fdc35f9c5
SRCREV_text="0e5f52c28dd72ab84daeb81b5a51f20fdc35f9c5"
SRC_URI += "git://github.com/kr/text.git;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/kr/text"

#   github.com/mattn/go-runewidth v0.0.9
# [1] git ls-remote https://github.com/mattn/go-runewidth.git 14e809f6d78fcf9f48ff9b70981472b64c05f754
SRCREV_go-runewidth="14e809f6d78fcf9f48ff9b70981472b64c05f754"
SRC_URI += "git://github.com/mattn/go-runewidth.git;name=go-runewidth;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-runewidth"

#   github.com/matttproud/golang_protobuf_extensions v1.0.1
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions.git c12348ce28de40eed0136aa2b644d0ee0650e56c
SRCREV_golang_protobuf_extensions="c12348ce28de40eed0136aa2b644d0ee0650e56c"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions.git;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

#   github.com/niemeyer/pretty v0.0.0-20200227124842-a10e7caefd8e
# [1] git ls-remote https://github.com/niemeyer/pretty.git a6f3cf47d962d7c6eae13b363e2b860eb561e528
SRCREV_pretty="a6f3cf47d962d7c6eae13b363e2b860eb561e528"
SRC_URI += "git://github.com/niemeyer/pretty.git;name=pretty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/niemeyer/pretty"

#   github.com/olekukonko/tablewriter v0.0.5
# [1] git ls-remote https://github.com/olekukonko/tablewriter.git c7d2a8a09b076b70918308a3cd95464b2ae3b5d8
SRCREV_tablewriter="c7d2a8a09b076b70918308a3cd95464b2ae3b5d8"
SRC_URI += "git://github.com/olekukonko/tablewriter.git;name=tablewriter;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/olekukonko/tablewriter"

#   github.com/peterh/liner v0.0.0-20170211195444-bf27d3ba8e1d
# [1] git ls-remote https://github.com/peterh/liner.git 58a158787cd552b11ce4a45f589a5452072c1fc0
SRCREV_liner="58a158787cd552b11ce4a45f589a5452072c1fc0"
SRC_URI += "git://github.com/peterh/liner.git;name=liner;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/peterh/liner"

#   github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors.git 614d223910a179a466c1767a985424175c39b465
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors.git;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

#   github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib.git c0b812dadcf4498dede02bb7f0c5c478be997e34
SRCREV_go-difflib="c0b812dadcf4498dede02bb7f0c5c478be997e34"
SRC_URI += "git://github.com/pmezard/go-difflib.git;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

#   github.com/prometheus/client_golang v1.7.1
# [1] git ls-remote https://github.com/prometheus/client_golang.git 85aaa2b758c868d2040dcc0f3333497e47e39f47
SRCREV_client_golang="85aaa2b758c868d2040dcc0f3333497e47e39f47"
SRC_URI += "git://github.com/prometheus/client_golang.git;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

#   github.com/prometheus/client_model v0.2.0
# [1] git ls-remote https://github.com/prometheus/client_model.git f44e7adcba5ee54c8a94709e6fc300d83245f171
SRCREV_client_model="f44e7adcba5ee54c8a94709e6fc300d83245f171"
SRC_URI += "git://github.com/prometheus/client_model.git;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

#   github.com/prometheus/common v0.14.0
# [1] git ls-remote https://github.com/prometheus/common.git 317b7b125e8fddda956d0c9574e5f03f438ed5bc
SRCREV_common="317b7b125e8fddda956d0c9574e5f03f438ed5bc"
SRC_URI += "git://github.com/prometheus/common.git;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

#   github.com/prometheus/procfs v0.2.0
# [1] git ls-remote https://github.com/prometheus/procfs.git 76fccdf64b940a8e9eb1a904c6f053cb0b0411e0
SRCREV_procfs="76fccdf64b940a8e9eb1a904c6f053cb0b0411e0"
SRC_URI += "git://github.com/prometheus/procfs.git;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

#   github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
# [1] git ls-remote https://github.com/rcrowley/go-metrics.git 65e299d6c5c92718e672a9d2bc7f96e5b687eef8
SRCREV_go-metrics="65e299d6c5c92718e672a9d2bc7f96e5b687eef8"
SRC_URI += "git://github.com/rcrowley/go-metrics.git;name=go-metrics;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rcrowley/go-metrics"

#   github.com/shurcooL/sanitized_anchor_name v1.0.0
# [1] git ls-remote https://github.com/shurcooL/sanitized_anchor_name.git 7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615
SRCREV_sanitized_anchor_name="7bfe4c7ecddb3666a94b053b422cdd8f5aaa3615"
SRC_URI += "git://github.com/shurcooL/sanitized_anchor_name.git;name=sanitized_anchor_name;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/shurcooL/sanitized_anchor_name"

#   github.com/sirupsen/logrus v1.8.1
# [1] git ls-remote https://github.com/sirupsen/logrus.git bdc0db8ead3853c56b7cd1ac2ba4e11b47d7da6b
SRCREV_logrus="bdc0db8ead3853c56b7cd1ac2ba4e11b47d7da6b"
SRC_URI += "git://github.com/sirupsen/logrus.git;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

#   github.com/spf13/cobra v1.1.3
# [1] git ls-remote https://github.com/spf13/cobra.git 8380ddd3132bdf8fd77731725b550c181dda0aa8
SRCREV_cobra="8380ddd3132bdf8fd77731725b550c181dda0aa8"
SRC_URI += "git://github.com/spf13/cobra.git;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

#   github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag.git 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag.git;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

#   github.com/stretchr/testify v1.7.0
# [1] git ls-remote https://github.com/stretchr/testify.git acba37e5db06f0093b465a7d47822bf13644b66c
SRCREV_testify="acba37e5db06f0093b465a7d47822bf13644b66c"
SRC_URI += "git://github.com/stretchr/testify.git;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

#   github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb
# [1] git ls-remote https://github.com/xeipuuv/gojsonpointer.git 02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb
SRCREV_gojsonpointer="02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb"
SRC_URI += "git://github.com/xeipuuv/gojsonpointer.git;name=gojsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonpointer"

#   github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
# [1] git ls-remote https://github.com/xeipuuv/gojsonreference.git bd5ef7bd5415a7ac448318e64f11a24cd21e594b
SRCREV_gojsonreference="bd5ef7bd5415a7ac448318e64f11a24cd21e594b"
SRC_URI += "git://github.com/xeipuuv/gojsonreference.git;name=gojsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xeipuuv/gojsonreference"

#   github.com/yashtewari/glob-intersection v0.0.0-20180916065949-5c77d914dd0b
# [1] git ls-remote https://github.com/yashtewari/glob-intersection.git 9f24ebf25f62b3565b778d6ec98775caf0e37720
SRCREV_glob-intersection="9f24ebf25f62b3565b778d6ec98775caf0e37720"
SRC_URI += "git://github.com/yashtewari/glob-intersection.git;name=glob-intersection;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/yashtewari/glob-intersection"

#   gopkg.in/check.v1 v1.0.0-20200227125254-8fa46927fb4f
# [1] git ls-remote https://gopkg.in/check.v1.git 10cb98267c6cb43ea9cd6793f29ff4089c306974
SRCREV_check_v1="10cb98267c6cb43ea9cd6793f29ff4089c306974"
SRC_URI += "git://gopkg.in/check.v1.git;name=check_v1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/check.v1"

#   gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2.git 7649d4548cb53a614db133b2a8ac1f31859dda8c
SRCREV_yaml_v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2.git;name=yaml_v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

#   gopkg.in/yaml.v3 v3.0.0-20200313102051-9f266ea9e77c
# [1] git ls-remote https://gopkg.in/yaml.v3.git 00bbc0947ae889b9e480044dbc3bc3e3216a6a89
SRCREV_yaml_v3="00bbc0947ae889b9e480044dbc3bc3e3216a6a89"
SRC_URI += "git://gopkg.in/yaml.v3.git;name=yaml_v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#   github.com/elliotchance/orderedmap
# [1] git ls-remote https://github.com/elliotchance/orderedmap 9d80274286972e4b495b38de2923a4d5f9758c8d
SRCREV_orderedmap="9d80274286972e4b495b38de2923a4d5f9758c8d"
SRC_URI += "git://github.com/elliotchance/orderedmap;name=orderedmap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/elliotchance/orderedmap"

#   github.com/fatih/color v1.10.0
# [1] git ls-remote https://github.com/fatih/color.git bc2269661d49c6c9d0e514eef49710556883f3fa
SRCREV_color="bc2269661d49c6c9d0e514eef49710556883f3fa"
SRC_URI += "git://github.com/fatih/color.git;name=color;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fatih/color"

#   github.com/goccy/go-yaml v1.8.4
# [1] git ls-remote https://github.com/goccy/go-yaml.git bdb73b469f3cada6f5f8749b21e06f6c77e48540
SRCREV_go-yaml="bdb73b469f3cada6f5f8749b21e06f6c77e48540"
SRC_URI += "git://github.com/goccy/go-yaml.git;name=go-yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/goccy/go-yaml"

#   github.com/jinzhu/copier v0.1.0
# [1] git ls-remote https://github.com/jinzhu/copier.git fc254513a8dcc0d7605f87d87976b937be68c181
SRCREV_copier="fc254513a8dcc0d7605f87d87976b937be68c181"
SRC_URI += "git://github.com/jinzhu/copier.git;name=copier;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jinzhu/copier"

#  github.com/mattn/go-colorable v0.1.8
# [1] git ls-remote https://github.com/mattn/go-colorable 2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1
SRCREV_go_colorable="2e1b0c1546e0173c0907cf05c67b8ba29ed8b4d1"
SRC_URI += "git://github.com/mattn/go-colorable;name=go_colorable;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-colorable"

#  github.com/mattn/go-isatty v0.0.12
# [1] git ls-remote https://github.com/mattn/go-isatty 7b513a986450394f7bbf1476909911b3aa3a55ce
SRCREV_go_isatty="7b513a986450394f7bbf1476909911b3aa3a55ce"
SRC_URI += "git://github.com/mattn/go-isatty;name=go_isatty;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-isatty"

#   github.com/timtadh/data-structures v0.5.3
# [1] git ls-remote https://github.com/timtadh/data-structures.git a129e3f22e38b4028f45cc3b77b98149884f4c75
SRCREV_data-structures="a129e3f22e38b4028f45cc3b77b98149884f4c75"
SRC_URI += "git://github.com/timtadh/data-structures.git;name=data-structures;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/timtadh/data-structures"

#   github.com/timtadh/lexmachine v0.2.2
# [1] git ls-remote https://github.com/timtadh/lexmachine.git cde49191c807daa1fd820e1c424cea6a73c47858
SRCREV_lexmachine="cde49191c807daa1fd820e1c424cea6a73c47858"
SRC_URI += "git://github.com/timtadh/lexmachine.git;name=lexmachine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/timtadh/lexmachine"

#   golang.org/x/sys v0.0.0-20210105210732-16f7687f5001
# [1] git ls-remote https://go.googlesource.com/sys 16f7687f5001b816ff9f6b586071238941e88a9d
SRCREV_sys="16f7687f5001b816ff9f6b586071238941e88a9d"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#   golang.org/x/xerrors v0.0.0-20200804184101-5ec99f83aff1
# [1] git ls-remote https://go.googlesource.com/xerrors 5ec99f83aff198f5fbd629d6c8d8eb38a04218ca
SRCREV_xerrors="5ec99f83aff198f5fbd629d6c8d8eb38a04218ca"
SRC_URI += "git://go.googlesource.com/xerrors;name=xerrors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/xerrors"

#   gopkg.in/op/go-logging.v1 v1.0.0-20160211212156-b2cb9fa56473
# [1] git ls-remote https://gopkg.in/op/go-logging.v1 b2cb9fa56473e98db8caba80237377e83fe44db5
SRCREV_go-logging.v1="b2cb9fa56473e98db8caba80237377e83fe44db5"
SRC_URI += "git://gopkg.in/op/go-logging.v1;name=go-logging.v1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/op/go-logging.v1"

#    github.com/docker/go-plugins-helpers main
# [1] git ls-remote https://github.com/docker/go-plugins-helpers 45e2431495c83b9ca1c2a669987d6e1afad07774
SRCREV_go-plugins-helpers="45e2431495c83b9ca1c2a669987d6e1afad07774"
SRC_URI += "git://github.com/docker/go-plugins-helpers;name=go-plugins-helpers;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-plugins-helpers"

#    github.com/open-policy-agent/opa v0.30.0
# [1] git ls-remote https://github.com/open-policy-agent/opa 84d0b65d3bf8a25e6001a0bfc52142ea683326e4
SRCREV_opa="84d0b65d3bf8a25e6001a0bfc52142ea683326e4"
SRC_URI += "git://github.com/open-policy-agent/opa;name=opa;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/open-policy-agent/opa"

#    github.com/Microsoft/go-winio
# [1] git ls-remote https://github.com/Microsoft/go-winio bdc6c112805ce13d7b235dc6257f258d958f5471
SRCREV_go-winio="bdc6c112805ce13d7b235dc6257f258d958f5471"
SRC_URI += "git://github.com/Microsoft/go-winio.git;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

#    github.com/coreos/go-systemd
# [1] git ls-remote https://github.com/coreos/go-systemd 7d375ecc2b092916968b5601f74cca28a8de45dd
SRCREV_go-systemd="7d375ecc2b092916968b5601f74cca28a8de45dd"
SRC_URI += "git://github.com/coreos/go-systemd.git;name=go-systemd;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coreos/go-systemd"

#    github.com/docker/go-connections v0.4.1
# [1] git ls-remote https://github.com/docker/go-connections 9ef9d5a8e904216e104cb86ad35d6b02bb9d723b
SRCREV_go-connections="9ef9d5a8e904216e104cb86ad35d6b02bb9d723b"
SRC_URI += "git://github.com/docker/go-connections.git;name=go-connections;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-connections"

#   golang.org/x/net
# [1]  git ls-remote https://go.googlesource.com/net refs/heads/release-branch.go1.15
SRCREV_net="aea8142032473bb41e874c31eb771c364b790fb4"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

#   golang.org/x/text
# [1] git ls-remote https://go.googlesource.com/text 75a595aef632b07c6eeaaa805adb6f0f66e4130e
SRCREV_xtext="75a595aef632b07c6eeaaa805adb6f0f66e4130e"
SRC_URI += "git://go.googlesource.com/text;name=xtext;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

#   golang.org/x/time
# [1] git ls-remote https://go.googlesource.com/time 0c50ed881d02b171df1325a8b7f5fa7c8c8fbb6f
SRCREV_time="0c50ed881d02b171df1325a8b7f5fa7c8c8fbb6f"
SRC_URI += "git://go.googlesource.com/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"
