#!/bin/sh

restore_backup_enabled() {
	return 0
}

restore_backup_run() {
	# Mount backup partition
	backupdev=$(blkid | grep "LABEL=\"backup\"" | cut -d ":" -f1)
	if [ -b "$backupdev" ]; then
		tmpdir=$(mktemp -d)
		mount -o ro $backupdev $tmpdir

		if [ -e "$tmpdir/.restore" ]; then
			. $tmpdir/.restore
			if [ "$restore" = "1" ]; then
				[ -n "$password" ] && arg_password="-c $password"
				# id0 is always data backup
				dest="id=0,dest=/dev/mapper/data-data"
				if [ "$type" = "full" ]; then
					system_dev=$(blkid | grep "LABEL=\"system\"" | cut -d ":" -f1)
					dest="$dest id=1,dest=$system_dev"

					# Full restore requires reboot as kernel might have changed
					reboot="1"
				fi
				fsarchiver restfs $tmpdir/$archive $arg_password -j "$(grep -c ^processor /proc/cpuinfo)" $dest
				mount -o remount,rw $backupdev $tmpdir
				rm $tmpdir/.restore
				mount -o remount,ro $backupdev $tmpdir

				if [ "$reboot" = "1" ]; then
					echo "System is rebooting!"
					echo 1 > /proc/sys/kernel/sysrq
					echo e > /proc/sysrq-trigger # send SIGTERM to all processes, allowing them to terminate gracefully
					echo s > /proc/sysrq-trigger # flush data to disk
					echo u > /proc/sysrq-trigger # remount all filesystems read-only
					echo b > /proc/sysrq-trigger
				fi
			fi
		fi

		umount $tmpdir
		rmdir $tmpdir
	fi
}
