#!/bin/sh

interface=$1

WEBDIR=$(dirname "$0")
NAME=$(hostname)

if [ -e "/var/platform/device_data/emulated" ]; then
    MANUFACTURER="@EMULATED_MANUFACTURER@"
    MANUFACTURER_URL="@EMULATED_MANUFACTURER_URL@"
    MODEL_NAME="@EMULATED_MODEL_NAME@"
    MODEL_NUMBER="@EMULATED_MODEL_NUMBER@"
    MODEL_URL="@EMULATED_MODEL_URL@"

    SERIALNO=$(cat /var/platform/device_data/serial_number)
    PRODNAME="@EMULATED_PRODUCT_NAME@"
else
    MANUFACTURER="@MANUFACTURER@"
    MANUFACTURER_URL="@MANUFACTURER_URL@"
    MODEL_URL="@MODEL_URL@"

    SERIALNO=$(cat /var/platform/device_data/serial_number)
    PRODNAME=$(cat /var/platform/device_data/product_name)
    if [ -e "/var/platform/device_data/oem_data/identification/product_name" ]; then
        MODEL_NAME=$(cat /var/platform/device_data/oem_data/identification/product_name)
    else
        MODEL_NAME="$PRODNAME"
    fi

    MODEL_NUMBER="$PRODNAME"
fi

IP=$(/bin/ifconfig "$interface" | grep -o 'inet [0-9.]*' | cut -d ' ' -f2)

PORT=$(cat /etc/nginx/nginx.conf | grep listen | grep -v ssl | sed -e 's/.*:\([0-9]\+\).*/\1/g')

# Check if port is overriden
if [ -e /etc/default/upnpd ]; then
  . /etc/default/upnpd
  if [ -n "${UPNPD_PRESENTATION_PORT}" ] && [ "${UPNPD_PRESENTATION_PORT}" != "-1" ]; then
    PORT="${UPNPD_PRESENTATION_PORT}"
  fi
fi

if [ "$PORT" != "80" ]; then
  PRESENTATION_URL="http://${IP}:${PORT}/"
else
  PRESENTATION_URL="http://${IP}/"
fi

sed -e 's@<friendlyName>.*<\/friendlyName>@<friendlyName>'"${PRODNAME}"' ('"${NAME}"')<\/friendlyName>@g' \
    -e 's@<manufacturer>.*<\/manufacturer>@<manufacturer>'"${MANUFACTURER}"'<\/manufacturer>@g' \
    -e 's@<manufacturerURL>.*<\/manufacturerURL>@<manufacturerURL>'"${MANUFACTURER_URL}"'<\/manufacturerURL>@g' \
    -e 's@<modelName>.*<\/modelName>@<modelName>'"${MODEL_NAME}"'<\/modelName>@g' \
    -e 's@<modelNumber>.*<\/modelNumber>@<modelNumber>'"${MODEL_NUMBER}"'<\/modelNumber>@g' \
    -e 's@<modelURL>.*<\/modelURL>@<modelURL>'"${MODEL_URL}"'<\/modelURL>@g' \
    -e 's/<serialNumber>.*<\/serialNumber>/<serialNumber>'"${SERIALNO}"'<\/serialNumber>/g' \
    -e 's/<UDN>uuid:.*<\/UDN>/<UDN>uuid:'"${NAME}"'<\/UDN>/g' \
    -e "s@<presentationURL>.*<\/presentationURL>@<presentationURL>${PRESENTATION_URL}<\/presentationURL>@g" \
    "${WEBDIR}"/netiotdevicedesc.xml > "${WEBDIR}"/desc/netiotdevicedesc_"${interface}".xml
