require conf/distro/poky.conf
require conf/distro/include/rust_versions.inc
require include/sanity.inc
require include/fixed_versions.inc
require cve-whitelist.inc

# TODO: Newer Uninative versions sometimes cause wic image build errors
#    See:
#      - https://lore.kernel.org/all/CA+chaQcZCV6xUXPMzOO07trMsmx0R7T3_mQxfYWVHwqiK+LTXw@mail.gmail.com/T/#m7e2a819c3f4940a2e2eb44c0d0b79e16c79eddcf
#      - https://patchwork.yoctoproject.org/project/oe-core/patch/20230623093323.4058529-1-Martin.Jansa@gmail.com/
UNINATIVE_VERSION = "3.9"
UNINATIVE_CHECKSUM[aarch64] = "de35708c95c34573af140da910132c3291ba4fd26ebf7b74b755ada432cdf07b"
UNINATIVE_CHECKSUM[i686] = "adac07b08adb88eb26fc7fd87fee0cec9d5be167bf7c5ffd3a549a2a6699c29c"
UNINATIVE_CHECKSUM[x86_64] = "3dd82c3fbdb59e87bf091c3eef555a05fae528eeda3083828f76cd4deaceca8b"

DISTRO = "netiot"
DISTRO_CODENAME = "netFIELDOS"
DISTRO_NAME = "netFIELD OS"
DISTRO_VERSION = "2.5"

DISTRO_FEATURES_append = " systemd acl xattr pam bluez5 zeroconf apparmor polkit audit"
DISTRO_FEATURES_remove = " ptest x11 wayland"

# Enable audit support in libpam
# NOTE: audit has a circular dependency when build python bindings as pam and audit is enabled in distro features
#  Dependency chain: audit -> python3 -> util-linux -> libpam -> audit
PACKAGECONFIG_append_pn-libpam += "audit"
PACKAGECONFIG_remove_pn-audit  += "python"

# Make sure license files are copied to any image
COPY_LIC_MANIFEST = "1"
COPY_LIC_DIRS = "1"

# Make sure all user-ids are static
USERADDEXTENSION = "useradd-staticids"
USERADD_UID_TABLES ??= "files/static-user-ids/passwd"
USERADD_GID_TABLES ??= "files/static-user-ids/group"
USERADD_ERROR_DYNAMIC ??= "error"

RUST_VERSION = "1.66.%"
GOVERSION = "1.20%"
PREFERRED_PROVIDER_go-native ?= "go-binary-native"

VOLATILE_LOG_DIR = "no"

NETIOT_ROOT_OVERLAY ?= "0"
#next line only valid if NETIOT_ROOT_OVERLAY != 1
NETIOT_OVERLAY_DIRS ?= "etc home opt var/lib var/log usr/local var/secrets"

# Use squashfs as rootfs
IMAGE_FSTYPES ?= "squashfs"

PACKAGE_CLASSES ?= "package_ipk"

VIRTUAL-RUNTIME_dev_manager = "udev"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

DISTRO_FEATURES_BACKFILL_CONSIDERED = "sysvinit"

INCOMPATIBLE_LICENSE = "*GPLv3"
# Bash 3 is pulled in by reject GPLv3, thus switch to older bash-completions
PREFERRED_VERSION_pn-bash-completion = "1.%"

NETWORK_MANAGER = ""

PACKAGECONFIG_append_pn-networkmanager += "modemmanager"

# Only use openssl in image as TLS library. Ommit using gnutls
INHERIT_DISTRO_append += "blacklist"
PNBLACKLIST[gnutls] = "netfield only uses openssl as TLS / crypto library"
PACKAGECONFIG_remove_pn-curl += "gnutls"
PACKAGECONFIG_append_pn-curl += "ssl"
PACKAGECONFIG_pn-glib-networking = "openssl"

# Set empty hostname, so it is generated on first boot on all platforms
hostname_pn-base-files = ""

# Development images may pull in GPLv3, which is not allowed in our distro, allow them for debugging reasons.
# ATTENTION: These images may not be distributed
ALLOWED_DEBUG_PACKAGES="autoconf autoconf-dev \
    binutils binutils-dev ccache ccache-dev \
    cpp cpp-symlinks gcc gcc-dev gcc-symlinks \
    g++ g++-dev g++-symlinks gdb gdb-dev \
    gdbserver libbfd libmpc libmpc-dev \
    mpfr mpfr-dev \
"
WHITELIST_GPL-3.0_append += "${@bb.utils.contains('EXTRA_IMAGE_FEATURES', 'debug-tweaks', '${ALLOWED_DEBUG_PACKAGES}', '', d)}"
PROFILE_TOOLS_X_pn-packagegroup-core-tools-profile = ""

PACKAGECONFIG_remove_pn-gdb += "readline"
# systemtap fails with ../git/loc2stap.cxx:673:9: error: 'DW_OP_GNU_parameter_ref' was not declared in this scope
SYSTEMTAP_pn-packagegroup-core-tools-profile = ""
