# SSL session settings as recommended by Mozilla server-side-TLS
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
# disable session resumption to ensure PFS
ssl_session_tickets	off;

# intermediate configuration
ssl_protocols TLSv1.2 TLSv1.3;
ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
ssl_prefer_server_ciphers off;

# 2048 bit Diffie-Hellman parameters for DHE ciphers
ssl_dhparam     /etc/nginx/ssl/dhparam.pem;

#>>> Common HTTP security headers: default values if not set by upstream application
# https://stackoverflow.com/questions/31017524/how-to-add-headers-in-nginx-only-sometimes
map $upstream_http_referrer_policy $referrer_policy {
    # use the value provided in the upstream response
    "~."       $upstream_http_referrer_policy;
    # if header is not set by upstream, set the default value
    default    strict-origin;
}
map $upstream_http_strict_transport_security $strict_transport_security {
    # use the value provided in the upstream response
    "~."       $upstream_http_strict_transport_security;
    # if header is not set by upstream, set the default value
    default    "max-age=15768000; includeSubDomains";
}
map $upstream_http_x_content_type_options $x_content_type_options {
    # use the value provided in the upstream response
    "~."       $upstream_http_x_content_type_options;
    # if header is not set by upstream, set the default value
    default    nosniff;
}
map $upstream_http_x_frame_options $x_frame_options {
    # use the value provided in the upstream response
    "~."       $upstream_http_x_frame_options;
    # if header is not set by upstream, set the default value
    default    SAMEORIGIN;
}
map $upstream_http_x_permitted_cross_domain_policies $x_permitted_cross_domain_policies {
    # use the value provided in the upstream response
    "~."       $upstream_http_x_permitted_cross_domain_policies;
    # if header is not set by upstream, set the default value
    default    none;
}
map $upstream_http_x_xss_protection $x_xss_protection {
    # use the value provided in the upstream response
    "~."       $upstream_http_x_xss_protection;
    # if header is not set by upstream, set the default value
    default    "1; mode=block";
}
#<<< END -- Common HTTP security headers
