user  www-data;
worker_processes  auto;
# number of file descriptors used for nginx
# the limit for the maximum FDs on the server is usually set by the OS.
# if you don't set FD's then OS settings will be used which is by default 2000
worker_rlimit_nofile 50000;

error_log stderr;
pid       /var/run/nginx/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log off;
    include /etc/nginx/conf.d/*.conf;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout  65;
    reset_timedout_connection on;
    proxy_cache_path /tmp/cache levels=1:2 keys_zone=cache:60m;

    proxy_request_buffering off;
    proxy_buffering off;

    #gzip  on;

    # prevent nginx from revealing the version number on error pages and response header
    server_tokens off;

    # set file size limits for the client body
    client_body_buffer_size 1k;
    client_max_body_size 1k;

    server {
        listen                  [::]:80 default ipv6only=off;
        root                    /var/www/localhost/html;

        include /etc/nginx/services/http/*.conf;

        # Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
        location ~ ^/.* {
           return                  301 https://$host:443$request_uri;
        }

        # only respond to GET or HEAD requests
        if ($request_method !~ ^(GET|HEAD)$ ) {
          # close connection without response
          return 444;
        }
    }

    server {
        listen                  [::]:443 default ipv6only=off ssl http2;
        root                    /var/www/localhost/html;
        server_name             Hilscher netIOT - Edge Gateway;
        ssl_certificate         /etc/ssl/services/nginx/cert.pem;
        ssl_certificate_key     /etc/ssl/services/nginx/key.pem;

        # global ssl settings in conf.d/90.hardening.conf

        include /etc/nginx/services/https/*.conf;

        # only respond to GET, HEAD or POST requests
        if ($request_method !~ ^(GET|HEAD|POST|PUT|DELETE)$ ) {
          # close connection without response
          return 444;
        }
    }
}
