require conf/distro/netiot.conf

DISTRO = "netiot-oem"
DISTRO_NAME = "netiot distro version used for oem overlay images."

DISTRO_EXTRA_RDEPENDS = ""
DISTRO_EXTRA_RRECOMMENDS = ""

INITRAMFS_IMAGE = ""

MACHINE_EXTRA_RDEPENDS = ""
MACHINE_EXTRA_RRECOMMENDS = ""

MACHINE_ESSENTIAL_EXTRA_RDEPENDS = ""
MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS = ""

PREFERRED_PROVIDER_virtual/kernel = ""
PREFERRED_PROVIDER_virtual/dtb = ""
