#!/bin/sh

# Example for led control structure. For help see led-state script.
#       led1=("/sys/class/leds/system-led/"                                        # led to process
#                   "none"        "1"                                              # state 0 = enable led
#                   "timer"     "100" "200"                                        # state 1 = enable blinking 100ms on and 100ms off
#                   "pattern"     "8"   "1" "100" "0" "200" "1" "1000" "0" "1000"  # state 2 = the '8' is the number of pattern following
#                                                                                              on 100ms / off 200ms / on 1s / off 1s
#                   "none"        "0"                                              # state 3 = disable led
#                   ...                                                            # state ...
#       leds2=("...")
#       leds="led1 led2 ..."

# NOTE: In case the system does not provide a cloud_red/green LED but LED signalling
#       is required, any free LED can be configured. For led control check "machine-state" service.

led1=("/var/platform/led_cloud_red/"
      "none"     "1"         # state 0
      "timer"  "500" "500"   # state 1
      "timer"  "500" "500"   # state 2
      "timer"  "100" "100"   # state 3
      "none"     "1"         # state 4
      "none"     "0"         # state 5
      "none"     "0"         # state 6
      "none"     "0"         # state 7
      "none"     "0"         # state 8
      )

led2=("/var/platform/led_cloud_green/"
      "none"     "0"        # state 0
      "none"     "0"        # state 1
      "none"     "0"        # state 2
      "none"     "0"        # state 3
      "none"     "1"        # state 4
      "timer"  "500" "500"  # state 5
      "timer"  "500" "500"  # state 6
      "timer"  "100" "100"  # state 7
      "none"     "1"        # state 8
      )

leds="led1 led2"
