# Auto-Generated by cargo-bitbake 0.3.14
#
inherit cargo

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

# how to get bindgen could be as easy as but default to a git checkout:
# SRC_URI += "crate://crates.io/bindgen/0.54.1"
SRC_URI += "git://github.com/rust-lang/rust-bindgen.git;protocol=https;nobranch=1"
SRCREV = "79f2c131dfc571852b7c097ca3d08d31ab9874c3"
S = "${WORKDIR}/git"
CARGO_SRC_DIR = ""


# please note if you have entries that do not begin with crate://
# you must change them to how that package can be fetched
SRC_URI += " \
    crate://crates.io/aho-corasick/0.7.6 \
    crate://crates.io/ansi_term/0.11.0 \
    crate://crates.io/atty/0.2.13 \
    crate://crates.io/bitflags/1.2.0 \
    crate://crates.io/byteorder/1.3.2 \
    crate://crates.io/cc/1.0.45 \
    crate://crates.io/cexpr/0.4.0 \
    crate://crates.io/cfg-if/0.1.10 \
    crate://crates.io/clang-sys/0.29.0 \
    crate://crates.io/clap/2.33.0 \
    crate://crates.io/diff/0.1.11 \
    crate://crates.io/env_logger/0.7.0 \
    crate://crates.io/glob/0.3.0 \
    crate://crates.io/humantime/1.3.0 \
    crate://crates.io/lazy_static/1.4.0 \
    crate://crates.io/lazycell/1.2.1 \
    crate://crates.io/libc/0.2.66 \
    crate://crates.io/libloading/0.5.2 \
    crate://crates.io/log/0.4.8 \
    crate://crates.io/memchr/2.2.1 \
    crate://crates.io/nom/5.1.1 \
    crate://crates.io/peeking_take_while/0.1.2 \
    crate://crates.io/proc-macro2/1.0.4 \
    crate://crates.io/quick-error/1.2.2 \
    crate://crates.io/quote/1.0.2 \
    crate://crates.io/regex-syntax/0.6.12 \
    crate://crates.io/regex/1.3.1 \
    crate://crates.io/rustc-hash/1.0.1 \
    crate://crates.io/shlex/0.1.1 \
    crate://crates.io/strsim/0.8.0 \
    crate://crates.io/termcolor/1.0.5 \
    crate://crates.io/textwrap/0.11.0 \
    crate://crates.io/thread_local/0.3.6 \
    crate://crates.io/unicode-width/0.1.6 \
    crate://crates.io/unicode-xid/0.2.0 \
    crate://crates.io/vec_map/0.8.1 \
    crate://crates.io/version_check/0.9.1 \
    crate://crates.io/which/3.0.0 \
    crate://crates.io/winapi-i686-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi-util/0.1.2 \
    crate://crates.io/winapi-x86_64-pc-windows-gnu/0.4.0 \
    crate://crates.io/winapi/0.3.8 \
    crate://crates.io/wincolor/1.0.2 \
"



# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM = " \
    file://LICENSE;md5=0b9a98cb3dcdefcceb145324693fda9b \
"

SUMMARY = "Automatically generates Rust FFI bindings to C and C++ libraries."
HOMEPAGE = "https://rust-lang.github.io/rust-bindgen/"
LICENSE = "BSD-3-Clause"

# includes this file if it exists but does not fail
# this is useful for anything you may want to override from
# what cargo-bitbake generates.
include bindgen-${PV}.inc
include bindgen.inc
