#!/bin/sh

help() {
	echo "Usage: $(basename "${0}") [options] <archive.fsa>"
	echo ""
	echo "Options:"
	echo " -p <password> : Password protect archive (6-64 chars)"
	echo ""
	echo "  Example: $(basename "${0}") -p 'password' 20190724.fsa"
}

while getopts hfp: opt; do
   case $opt in
       h) help; exit 0;;
       p) password="$OPTARG" ;;
       *) help; exit 1;;
   esac
done
shift "$(( OPTIND - 1 ))"
archive="${1}"

if [ -z "$archive" ]; then
	help
	exit 1
fi

if [ ! -e "/mnt/backup/$archive" ]; then
	echo "Error $archive not existant on backup volumt"
	exit 1
fi

# Check archive contents
if [ -z "$password" ]; then
    arch_content=$(fsarchiver archinfo /mnt/backup/"$archive" 2>&1)
else
    arch_content=$(fsarchiver archinfo /mnt/backup/"$archive" -c "$password" 2>&1)
fi

if [ $? -ne 0 ]; then
    echo "Error parsing archive $archive (Invalid archive or wrong password)"
    echo "Output: $arch_content"
    exit 1
fi

# Output label variables
arch_label=$(echo "$arch_content" | grep 'Archive label:' | cut -d ":" -f2- | sed -e 's/^[\t ]*//')
output=$(echo "$arch_label" | tr ';' '\n')
echo "$output"
