#!/bin/sh

get_arg() {
	echo ${args} | sed 's/ /\n/g' | grep $1 | cut -s -d'=' -f2
}

log() {
	echo "$@" | tee -a ${logfile}
}

do_reboot() {
	trap "" 15 # TERM
	log "System is rebooting!"
	echo 1 > /proc/sys/kernel/sysrq
	echo e > /proc/sysrq-trigger # send SIGTERM to all processes, allowing them to terminate gracefully
#	echo i > /proc/sysrq-trigger # send SIGKILL to all processes, forcing them to terminate immediately
	echo s > /proc/sysrq-trigger # flush data to disk
	echo u > /proc/sysrq-trigger # remount all filesystems read-only
	echo b > /proc/sysrq-trigger
}

do_shutdown() {
	trap "" 9 15 # TERM
	log "System is shutting down!"
	echo 1 > /proc/sys/kernel/sysrq
	echo e > /proc/sysrq-trigger # send SIGTERM to all processes, allowing them to terminate gracefully
#	echo i > /proc/sysrq-trigger # send SIGKILL to all processes, forcing them to terminate immediately
	echo s > /proc/sysrq-trigger # flush data to disk
	echo u > /proc/sysrq-trigger # remount all filesystems read-only
	echo o > /proc/sysrq-trigger
}

args=$*
apifile=$(get_arg apifile)
logfile=$(get_arg logfile)
reboot=$(get_arg internal)
shutdown=$(get_arg external)

