#!/bin/sh

backup_restore_enabled() {
	return 0
}

backup_get_var() {
	grep "^${2}=" "$1" | cut -d '=' -f2-
}

backup_restore_run() {
	dev=$(blkid | grep "LABEL=\"backup\"" | cut -d ":" -f1)
	if [ -b "$dev" ]; then
		mp=$(mktemp -d) && mount -o ro "$dev" "$mp"

		if [ -e "$mp/.restore" ]; then
			restore=$(backup_get_var "$mp/.restore" "restore")
			archive=$(backup_get_var "$mp/.restore" "archive")
			password=$(backup_get_var "$mp/.restore" "password")
			type=$(backup_get_var "$mp/.restore" "type")
			if [ "$restore" = "1" ]; then
				# id0 is always data backup
				dest="id=0,dest=/dev/mapper/data-data"
				if [ "$type" = "full" ]; then
					system_dev=$(blkid | grep "LABEL=\"system\"" | cut -d ":" -f1)
					dest="$dest id=1,dest=$system_dev"

					# Older backups may not contain the boot partition
					if [ -n "$password" ]; then
						arch_info=$(fsarchiver archinfo -c "$password" "$mp"/"$archive" 2>&1)
					else
						arch_info=$(fsarchiver archinfo "$mp"/"$archive" 2>&1)
					fi
					num_ids=$(echo "$arch_info" | grep "Filesystems count:" | cut -d ':' -f2- | tr -d '\t ')
					if [ "$num_ids" -gt 2 ]; then
						boot_dev=$(blkid | grep "LABEL=\"boot\"" | cut -d ":" -f1)
						dest="$dest id=2,dest=$boot_dev"
					fi

					# Full restore requires reboot as kernel might have changed
					reboot="1"

					# Full restore requires unmount of system partition
					umount "$boot_mp"
				fi

				if [ -n "$password" ]; then
					fsarchiver restfs "$mp"/"$archive" -c "$password" -j "$(grep -c ^processor /proc/cpuinfo)" $dest
				else
					fsarchiver restfs "$mp"/"$archive" -j "$(grep -c ^processor /proc/cpuinfo)" $dest
				fi

				# Perform platform specific restore (e.g. bootloader)
				if [ -e "/usr/sbin/platform_restore" ]; then
					/usr/sbin/platform_restore "$type"
				fi

				# Delete restore request file.
				mount -o remount,rw "$dev" "$mp" && rm "$mp"/.restore && mount -o remount,ro "$dev" "$mp"

				if [ "$reboot" = "1" ]; then
					__debug "System is rebooting!"
					echo 1 > /proc/sys/kernel/sysrq
					echo e > /proc/sysrq-trigger # send SIGTERM to all processes, allowing them to terminate gracefully
					echo s > /proc/sysrq-trigger # flush data to disk
					echo u > /proc/sysrq-trigger # remount all filesystems read-only
					echo b > /proc/sysrq-trigger
				fi
			fi
		fi

		umount "$mp" && rmdir "$mp"
	fi
}
