#!/bin/sh

check_fs_enabled() {
	return 0
}

check_fs_run() {
	# Check all filesystems for defects
	for check_label in system data backup; do
		dev_list=$(blkid | grep "LABEL=\"$check_label\"" | cut -d ":" -f1)
		for dev in $dev_list; do
			dev=$(readlink -f $dev)
			if [ -b "$dev" ]; then
				FS=$(lsblk -f -o KNAME,FSTYPE | grep $(basename $dev) | tr -s ' ' | cut -d ' ' -f2)
				echo "Checking $FS on $dev"
				case $FS in
				'ext4' | 'ext3' | 'ext2')
					fsck.ext4 -p $dev
					;;
				*)
					echo "Unknown fstype $FS on $dev to check"
					;;
				esac
			fi
		done
	done
}
