#!/bin/sh

device_data_enabled() {
	return 0
}

migrate_device_data() {
	# Since V2.4. the device data will be kept only under [backup partition]/nvd/.

	# CASE1:
	# Old devices may keep the device label still on the rescue partition,
	# in this case move it to the common dedicated storage location
	mkdir -p /tmp/rescue
	mount $(blkid -L rescue) /tmp/rescue
	if [ -e "/tmp/rescue/nvd/device_data" ] && [ ! -e "$mp/nvd/device_data" ]; then
		__debug "Moving production device data to final location"
		mount -o remount,rw $dev $mp && mkdir -p $mp/nvd
		mv /tmp/rescue/nvd/device_data $mp/nvd/device_data
		mount -o remount,ro $dev $mp
		rmdir /tmp/rescue/nvd
		sync
	fi
	umount /tmp/rescue
	rmdir /tmp/rescue

	# CASE2:
	# As old INTEL devices/firmwares stored the device-label only in efivar,
	# this migration step is carried out to copy this device-label to a common dedicated storage location.
	[ ! -r $mp/nvd/device_data ] && {
		load_kernel_module efivarfs && mount -t efivarfs none /sys/firmware/efi/efivars
		[ -e /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 ] && {
			mount -o remount,rw $dev $mp && mkdir -p $mp/nvd
			cat /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 > $mp/nvd/device_data
			mount -o remount,ro $dev $mp
		}
		[ -e /sys/firmware/efi/efivars ] && umount /sys/firmware/efi/efivars
	}
}

device_data_run() {
	# Create temporary module directory
	moddir=/tmp/$module; mkdir -p $moddir

	dev=$(blkid -L backup)
	mp=$(mktemp -d) && mkdir -p $mp && mount -o ro $dev $mp

	migrate_device_data

	mac=$(cat /sys/class/net/eth0/address | tr -d ':' | tr "[:lower:]" "[:upper:]")
	openssl x509 -pubkey -in /proc/sys/srm/owner-cert -noout > $moddir/owner-public.key

	dd=$mp/nvd/device_data
	if [ -r $dd ]; then
		# Split device data into signature and data
		dd_sig=$(cut -d $'\n' -f1 < $dd)
		dd_data=$(cut -d $'\n' -f2 < $dd)

		base64 -i -d <<<$dd_sig > $moddir/dd.sig

		__debug "Verifying $dd ..."
		echo -n $dd_data | openssl dgst -sha512 -verify  $moddir/owner-public.key -signature $moddir/dd.sig && {
			# Check against all found MAC's
			grep -q mac\":\"$mac <<< $dd_data && {
				device_data=$dd_data
				__debug "... success => Using $dd as device_data file."
			}
		}
		[ -n "$device_data" ] || __debug "... failed! => Using fake device data."
	else
		__debug "Invalid or missing device data! => Using fake device data."
	fi

	# Load kernel driver for securly providing device data in runtime environment.
	load_kernel_module device-data

	# Export device-/fake-data to runtime environment.
	if [ -n "$device_data" ]; then
		# Replace single backslash with double backslashes (some labels are non-standard JSON)
		echo -n $device_data |  sed -e 's,\([^\\]\\\)\([^\\]\),\1\\\2,g' > /sys/device_data/export
	else
		# Define some defaults used to create fake device data.
		productname="unknown"
		[ -e "/proc/device-tree/model" ] && productname=$(cat /proc/device-tree/model)
		[ -e "/sys/class/dmi/id/product_name" ] && productname=$(cat /sys/class/dmi/id/product_name)
		[ -e "/forced_productname" ] && productname=$(cat /forced_productname)
		[ -e "/forced_productnumber" ] && add_dl_data=",\"product_number\":\"$(cat /forced_productnumber)\""

		fallback_serial="MAC:$mac"

		echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
	fi

	# Export the device-data signature as well as the public device key to runtime environment.
	signature="${dd_sig:-"na"}"
	pubkey="$(cat $moddir/owner-public.key)"
	echo -n '{"signature":"'"${signature}"'"}' > /sys/device_data/export
	echo -n '{"publickey":"'"${pubkey}"'"}' | sed 's,\n,\\n,' > /sys/device_data/export

	# Lock the kernel driver to prevent later tampering.
	echo 1 > /sys/device_data/lock

	# Provide a link in /var/platform
	ln -s /sys/device_data /var/platform/device_data

	# Cleanup
	umount $mp  && rmdir $mp
	rm -rf $moddir
}
