#!/bin/sh

device_data_enabled() {
	return 0
}

FALLBACK_LABELS="backup rescue boot"

device_data_run() {
  echo "Running device_data ... "

  for fallback_label in ${FALLBACK_LABELS}; do
    dev_list=$(blkid | grep "LABEL=\"$fallback_label\"" | cut -d ":" -f1)
    for dev in $dev_list; do
      if [ -n "${dev}" ]; then
        mp="/mnt/$fallback_label-$(find /mnt/$fallback_label-* -type d -maxdepth 0 2>/dev/null | wc -l)"
        mkdir -p ${mp}
        mount ${dev} ${mp}
      fi
    done
  done

  mac=$(cat /sys/class/net/eth0/address | sed 's/://g' | tr "[:lower:]" "[:upper:]")
  pub_key=/tmp/owner-public.key
  openssl x509 -pubkey -in /proc/sys/srm/owner-cert -noout > ${pub_key}

  load_kernel_module device-data

  load_kernel_module efivarfs
  [ -e /sys/firmware/efi/efivars ] && mount -t efivarfs none /sys/firmware/efi/efivars

  # Verifying device data ...
  for dd in /mnt/backup-*/nvd/device_data /mnt/rescue-*/nvd/device_data /mnt/boot-*/nvd/device_data /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9
  do
    if [ -r ${dd} ]; then
      # Split device data into signature and data
      tmp_sig=$(cat ${dd} | cut -d$'\n' -f1)
      tmp_devdata=$(cat ${dd} | cut -d$'\n' -f2-)

      # extract signature
      dd_sig=/tmp/dd.sig
      echo -n $tmp_sig | base64 -i -d - > ${dd_sig}
      echo -n $tmp_devdata | openssl dgst -sha512 -verify "${pub_key}" -signature "${dd_sig}" && {
        # Check against all found MAC's NOTE: Bluetooth and WIFI are not checked as this hacky split does not work for sub-objects
        found_macs=`echo $tmp_devdata | tr -d "{}" | tr "," "\n" | grep "^\"mac" | cut -d ":" -f2 | tr -d "\"" | tr "\n" " "`
        for dd_mac in $found_macs; do
          if [ "$dd_mac" == "$mac" ]; then
            # Export the device data
            device_data=$tmp_devdata
            signed_device_data=$(cat ${dd})
            echo "Found device data on $dd"
            break
          fi
        done
        [ ! -z "$device_data" ] && break
      }

      rm ${dd_sig}
    fi
  done

  productname="unknown"
  [ -e "/proc/device-tree/model" ] && productname=$(cat /proc/device-tree/model)
  [ -e "/sys/class/dmi/id/product_name" ] && productname=$(cat /sys/class/dmi/id/product_name)
  [ -e "/forced_productname" ] && productname=$(cat /forced_productname)
  fallback_serial="MAC:$mac"
  if [ -e "/sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574" ]; then
    machine_id="$(cat /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574 | tail -c +5)"
    modulus=$(openssl x509 -noout -modulus -in /proc/sys/srm/owner-cert | cut -d "=" -f2)
    machine_id=$(echo $machine_id | openssl aes-256-cbc -nosalt -a -d -k "$modulus" -pbkdf2)
    if [ $? -ne 0 ]; then
        add_dl_data=',"product_number":"!!TAMPERED!!"'
        fallback_serial="!!TAMPERED!!"
        chattr -i /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
        rm -f /sys/firmware/efi/efivars/hmi-45cd6521-a671-4782-8119-c29a709d2574
    else
        add_dl_data=',"machine_id":"'"$machine_id"'"'
        add_dl_data="${add_dl_data},"'"product_number":"'"$(echo $machine_id | head -c 12)"'"'
        fallback_serial="$(echo $machine_id | tail -c 13)"
    fi
  fi

  if [ -z "$device_data" ]; then
    # Insert fallback data to show error in edge gw manager
    echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
  else
    # Replace single backslash with double backslashes (some labels are non-standard JSON)
    echo -n $device_data |  sed -e 's,\([^\\]\\\)\([^\\]\),\1\\\2,g' > /sys/device_data/export
    if [ $? -ne 0 ]; then
      # Unable to inject device data (e.g. INVALID JSON),
      # insert fallback data to show error in edge gw manager
      echo -n '{"product_name":"'"${productname}"'","serial_number":"'"${fallback_serial}"'"'"${add_dl_data}"'}' > /sys/device_data/export
    fi

    # Restore efivars if not available
    if [ -d /sys/firmware/efi/efivars ]; then
      if [ ! -e /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9 ]; then
        # create
        printf "\x07\x00\x00\x00" > /tmp/efivars_temp
        echo "$signed_device_data" >> /tmp/efivars_temp
        cat /tmp/efivars_temp > /sys/firmware/efi/efivars/hilscher-23682453-5d09-4e17-a1a6-f5efb21996d9
        rm /tmp/efivars_temp
      fi
    fi
  fi

  signature="${tmp_sig:-"na"}"
  pubkey="$(cat $pub_key)"
  echo -n '{"signature":"'"${signature}"'"}' > /sys/device_data/export
  echo -n '{"publickey":"'"${pubkey}"'"}' | sed 's,\n,\\n,' > /sys/device_data/export
  echo 1 > /sys/device_data/lock

  ln -s /sys/device_data /var/platform/device_data

  for fallback_label in ${FALLBACK_LABELS}; do
    mp_list="find /mnt/$fallback_label-* -type d -maxdepth 0 2>/dev/null"
    for mp in $mp_list; do
      if [ -d "${mp}" ]; then
        # Restore on BACKUP if not available
        if [ -n "$device_data" ]; then
          if [ ! -e "${mp}/nvd/device_data" ]; then
            mkdir -p ${mp}/nvd
            echo -n "$signed_device_data" > ${mp}/nvd/device_data
          fi
        fi
        umount ${mp}
        rmdir ${mp}
      fi
    done
  done
  [ -e /sys/firmware/efi/efivars ] && umount /sys/firmware/efi/efivars
}
