#!/bin/sh

logfile="/tmp/initrd-api.log"
log() {
	echo "$0: $@" | tee -a $logfile
}

initrd_api_enabled() {
	remove_old_logfiles=1
	return 0
}

initrd_api_run() {
	# NOTE:
	# The device mount takes place in two steps, first as read-only and then as read/write.
	# This is to avoid mount errors for devices already mounted read-only.
	mp=$(mktemp -d) && mkdir -p $mp && mount -o ro $boot_dev $mp && mount -o remount,rw $boot_dev $mp

	for f in $(find $mp -name initrd-api*); do
		grep -q .log$ <<< $f && continue

		# Remove old logfiles if this initrd-api script is called during within normal boot process
		# and a new initrd API file should be executed!
		[ "$remove_old_logfiles" = "1" ] && {
			__debug "Removing old logfiles ..."
			find $mp -name initrd-api*.log -type f -exec rm {} \;
			remove_old_logfiles=0
		}

		# Set initial working directory used as the starting point for each initrd-api file.
		cd /tmp

		[ -e $f ] && {
			# Verify initrd-api file
			log "Verifying $f ..."
			offset=$(verify_file $f) || {
				log "... failed!"
				rm -f $f
				continue
			}
			log "... success => Using $f as initrd-api file."

			# Extract contents of initrd-api file
			mkdir -p /tmp/$(basename $f) && cd /tmp/$(basename $f)
			contents=$(tail -c+${offset} $f | tar xzv)
			log "$f: Provided contents: $(tr '\n' ' ' <<< $contents)"

			# Start the provided runscript
			[ -x runscript.sh ] && ./runscript.sh apifile=$f || {
				log "Executing $f failed ($?)!"
				__fatal "Executing $f failed ($?)!"
			}

			cd - >/dev/null && rm -rf /tmp/$(basename $f)
		}
	done

	sync && umount $mp && rmdir $mp
}
