#!/bin/sh

# Macros ...
############

# logs to kernel ring buffer is implemented as in 'msg', 'info' and 'fatal'
# commands in 'poky/meta/recipes-core/initrdscripts/initramfs-framework/init'

__msg() {
  msg "### ${module}: $@"
  echo "<14>initrd: ### ${module}: $@" > /dev/kmsg
}

__info() {
  info "### ${module}: $@"
  [ -n "$bootparam_verbose" ] && echo "<14>initrd: ### ${module}: $@" > /dev/kmsg
}

__debug() {
  [ $bootparam_mydebug ] && echo "### ${module}: $@" >/dev/console
  [ $bootparam_mydebug ] && echo "<15>initrd: ### ${module}: $@" > /dev/kmsg
}

__fatal() {
  echo "<9>initrd: ### ${module}: $@" > /dev/kmsg # 'fatal' command goes in endless loop
  fatal "### ${module}: $@"
}

__skip() {
  [ -n "$bootparam_mydebug" ] && {
    echo "### Skipping $1 ..." >/dev/console
    echo "################################################################################" >/dev/console
    echo "<15>initrd: ### Skipping $1 ..." >/dev/kmsg
    echo "<15>initrd: ################################################################################" >/dev/kmsg
  }
}

ADDITIONAL_MOUNTPOINTS=""
add_mp() {
	ADDITIONAL_MOUNTPOINTS="$ADDITIONAL_MOUNTPOINTS $@"
}

# Hook functions ...
####################

premod() {
  echo "################################################################################" >/dev/console
  echo "### Starting $1 ..." >/dev/console
  echo "<15>initrd: ################################################################################" >/dev/kmsg
  echo "<15>initrd: ### Starting $1 ..." >/dev/kmsg
}

postmod() {
  echo "### Exiting $1 ..." >/dev/console
  echo "################################################################################" >/dev/console
  echo "<15>initrd: ### Exiting $1 ..." >/dev/kmsg
  echo "<15>initrd: ################################################################################" >/dev/kmsg
}

get_physical_boot_device() {
	# Replace LABEL of bootparam_bootCfg by real block device.
	if grep -q "^LABEL=" <<<$bootparam_bootCfg; then
		label=$(echo $bootparam_bootCfg | cut -d'=' -f2 | cut -d'/' -f1)
		while ! dev=$(blkid -L $label); do sleep 1; done
		bootparam_bootCfg=$(sed "s,^LABEL=$label,$dev," <<< $bootparam_bootCfg)
	fi

	boot_dev=$(grep ^/dev/ <<< $bootparam_bootCfg | cut -d'/' -f-3)

	[ -n "$boot_dev" ] && echo "/dev/$(lsblk -no pkname $boot_dev)"
}

__app=$0
__func=$1
__module=$2

case $__func in
	pre)
		premod $__module;;
	post)
		postmod $__module;;
	*);;
esac

# Module functions ...
######################

# Required for chroot environments
export PATH

# Add extra options for debug images ...
grep -qo debug < /firmware.version && {
	bootparam_init_fatal_sh=true
	bootparam_mydebug=true
}

macros_hooks_enabled() {
	return 0
}

macros_hooks_run() {
	# Limit the LVM scan to the active boot device only!
	physical_boot_device=$(get_physical_boot_device)
	[ -n "$physical_boot_device" ] && sed -i -e "s;filter = .*;filter = \[\"a|$physical_boot_device|\"\, \"r|.*|\"\];" /etc/lvm/lvm.conf

	if [ $bootparam_mydebug ]; then
		premod $module
		[ -n "$physical_boot_device" ] && __debug "physical_boot_device = $physical_boot_device"
		add_module_pre_hook $(find /init.d/ -name *-macros_hooks)
		add_module_post_hook $(find /init.d/ -name *-macros_hooks)
	fi
}
