#!/bin/sh

usage() {
    cat <<EOF

Usage: $0 clean
EOF
}

case "$1" in
    clean)
        rm -f /run/overlay/iotedge-docker/network/files/local-kv.db /run/overlay/docker/network/files/local-kv.db
        ;;
    *)
        usage
        exit 1
        ;;
esac
