#!/bin/sh

SYSTEMD_PROXY_CONFIG="/etc/systemd/system.conf.d/10-default-env.conf"
PROFILE_PROXY_CONFIG="/etc/profile.d/10-proxy.sh"

usage() {
    cat <<EOF
Usage:
    Set proxy config:
        $0 -s <proxy-config>
    Reboot:
        $0 -r

Example:
    $0 -s '{"no_proxy":"", "http_proxy": "192.168.10.20:8080"}'
    $0 -r
EOF
}

set_proxy_config() {
    if ! echo "$1" | jq >/dev/null;then
        usage
        exit 2
    fi

    # Extract value
    http_proxy=$(echo "$1" | jq -r '.http_proxy // ""')
    https_proxy=$(echo "$1" | jq -r '.https_proxy // ""')
    ftp_proxy=$(echo "$1" | jq -r '.ftp_proxy // ""')
    no_proxy=$(echo "$1" | jq -r '.no_proxy // ""')

    mkdir -p $(dirname ${SYSTEMD_PROXY_CONFIG})
    mkdir -p $(dirname ${PROFILE_PROXY_CONFIG})

    cat <<EOF>${SYSTEMD_PROXY_CONFIG}
[Manager]
DefaultEnvironment="http_proxy=${http_proxy}" "https_proxy=${https_proxy}" "ftp_proxy=${ftp_proxy}" "no_proxy=${no_proxy}"
EOF

    cat <<EOF>${PROFILE_PROXY_CONFIG}
#!/bin/sh

export "http_proxy=${http_proxy}" "https_proxy=${https_proxy}" "ftp_proxy=${ftp_proxy}" "no_proxy=${no_proxy}"
EOF
}

if [ $# -eq 0 ]; then
    do_usage="1"
fi

while getopts "hrs:" arg; do
  case $arg in
    h)
      do_usage="1"
      ;;
    r)
      do_reboot="1"
      ;;
    s)
      proxy_settings="$OPTARG"
      do_proxy_settings="1"
      ;;
  esac
done

if [ "$do_usage" = "1" ]; then
    usage
    exit 1
fi

if [ "$do_proxy_settings" = "1" ]; then
    set_proxy_config "$proxy_settings"
fi

if [ "$do_reboot" = "1" ]; then
    shutdown --reboot now
fi
