#!/bin/sh -e

SYSTEMD_PROXY_CONFIG="/etc/systemd/system.conf.d/10-default-env.conf"
PROFILE_PROXY_CONFIG="/etc/profile.d/10-proxy.sh"

usage() {
    cat <<EOF
Usage:
    Set proxy config:
        $0 -s <proxy-config>
    Reboot:
        $0 -r

Example:
    $0 -s '{"no_proxy":"", "http_proxy": "192.168.10.20:8080"}'
    $0 -r
EOF
}

set_proxy_config() {
    if ! echo "$1" | jq >/dev/null;then
        usage
        exit 2
    fi

    # Extract value
    http_proxy=$(echo "$1" | jq -r '.http_proxy // ""')
    https_proxy=$(echo "$1" | jq -r '.https_proxy // ""')
    ftp_proxy=$(echo "$1" | jq -r '.ftp_proxy // ""')
    no_proxy=$(echo "$1" | jq -r '.no_proxy // ""')

    mkdir -p $(dirname ${SYSTEMD_PROXY_CONFIG})
    mkdir -p $(dirname ${PROFILE_PROXY_CONFIG})

    cat <<EOF>${SYSTEMD_PROXY_CONFIG}
[Manager]
DefaultEnvironment="http_proxy=${http_proxy}" "https_proxy=${https_proxy}" "ftp_proxy=${ftp_proxy}" "no_proxy=${no_proxy}"
EOF

    cat <<EOF>${PROFILE_PROXY_CONFIG}
#!/bin/sh

export "http_proxy=${http_proxy}" "https_proxy=${https_proxy}" "ftp_proxy=${ftp_proxy}" "no_proxy=${no_proxy}"
EOF

    # Patch config.toml if existing
    if [ -e "/etc/aziot/config.toml" ]; then
        python3 - <<END

import toml
config_toml=toml.load('/etc/aziot/config.toml')

vals_to_set = [
    {'key': 'http_proxy',  'val': '$http_proxy' },
    {'key': 'https_proxy', 'val': '$https_proxy'},
    {'key': 'ftp_proxy',   'val': '$ftp_proxy'  },
    {'key': 'no_proxy',    'val': '$no_proxy'   },
]

for kv_pair in vals_to_set:
    if kv_pair['val'] != '':
        if 'agent' not in config_toml:
            config_toml['agent'] = {}
        if 'env' not in config_toml['agent']:
            config_toml['agent']['env'] = {}
        config_toml['agent']['env'][kv_pair['key']] = kv_pair['val']
    else:
        try:
            x = config_toml['agent']['env'][kv_pair['key']]
            del config_toml['agent']['env'][kv_pair['key']]
        except KeyError:
            pass

with open('/etc/aziot/config.toml', 'w') as f:
    toml.dump(config_toml, f)
END

    fi
}

if [ $# -eq 0 ]; then
    do_usage="1"
fi

while getopts "hrs:" arg; do
  case $arg in
    h)
      do_usage="1"
      ;;
    r)
      do_reboot="1"
      ;;
    s)
      proxy_settings="$OPTARG"
      do_proxy_settings="1"
      ;;
  esac
done

if [ "$do_usage" = "1" ]; then
    usage
    exit 1
fi

if [ "$do_proxy_settings" = "1" ]; then
    set_proxy_config "$proxy_settings"
fi

if [ "$do_reboot" = "1" ]; then
    shutdown --reboot now
fi
