# Auto-Generated by cargo-bitbake 0.3.16-alpha.0
#
inherit cargo
inherit pkgconfig

# If this is git based prefer versioned ones if they exist
# DEFAULT_PREFERENCE = "-1"

SRC_URI = "git://github.com/azure/iotedge;protocol=https;nobranch=1"
SRCREV = "7523e680ae9feacaa54df13de80fa82a2b2e7b74"
S = "${WORKDIR}/git/edgelet"
CARGO_SRC_DIR = "."

require aziot-edge-crates.inc

require aziot-edge.inc
