FILESEXTRAPATHS_prepend := "${THISDIR}/docker:${THISDIR}/iotedge:"

SRC_URI_append += "file://iotedge-docker.service \
                   file://iotedge-docker.socket \
                   file://iotedge.json \
                   file://iotedge_bridge.sh \
                   file://iotedge.rules \
                   file://iotedge.default \
                   file://docker-iotedge.sh \
                   file://iotedged-gencerts \
                   file://iotedge_systemd_use_rundir.patch \
                   file://iotedged-prepare \
"

RDEPENDS_${PN}_append += "bridge-utils yq"

SYSTEMD_SERVICE_${PN}_append += "iotedge-docker.service iotedge-docker.socket"

do_install_append() {
    install -d ${D}${sysconfdir}/docker
    install -m0644 ${WORKDIR}/iotedge.json ${D}${sysconfdir}/docker/
    install -m0644 ${WORKDIR}/iotedge-docker.service ${D}${systemd_system_unitdir}
    install -m0644 ${WORKDIR}/iotedge-docker.socket ${D}${systemd_system_unitdir}

    sed -i -e 's/docker.socket/iotedge-docker.socket/g' \
           -e 's/docker.service/iotedge-docker.service/g' \
           -e 's/\[Service\]/\[Service\]\nOOMScoreAdjust=-1000/g' \
           ${D}${systemd_system_unitdir}/iotedge.service

    sed -i -e 's@uri: "unix:///run/docker.sock"@uri: "unix:///run/iotedge-docker.sock"@g' \
           ${D}${sysconfdir}/iotedge/config.yaml

    install ${WORKDIR}/docker-iotedge.sh ${D}${bindir}/docker-iotedge

    install -d ${D}${sbindir}
    install ${WORKDIR}/iotedge_bridge.sh ${D}${sbindir}/iotedge_bridge
    install -d ${D}${sysconfdir}/default
    install -m 0644 ${WORKDIR}/iotedge.default ${D}${sysconfdir}/default/${PN}

    install -d ${D}${base_libdir}/udev/rules.d/
    install -m 0644 ${WORKDIR}/iotedge.rules ${D}${base_libdir}/udev/rules.d/80-iotedge.rules

    # Add script to update device certificates (otherwise autogenerated ones will be used)
    install -d ${D}${sbindir}
    install ${WORKDIR}/iotedged-gencerts ${D}${sbindir}
    sed -i -e 's@\(^ExecStart=.*$\)@ExecStartPre=+${sbindir}/iotedged-gencerts\n\1@g' ${D}${systemd_system_unitdir}/iotedge.service

    # Insert script to change docker sockets to /run to avoid systemd warning
    install ${WORKDIR}/iotedged-prepare ${D}${sbindir}
    sed -i -e 's@\(^ExecStart=.*$\)@ExecStartPre=+${sbindir}/iotedged-prepare\n\1@g' ${D}${systemd_system_unitdir}/iotedge.service
}

FILES_${PN}_append += "${sbindir} ${base_libdir}/udev/rules.d/"
