#!/bin/sh

updateiotedge_preoverlay() {
	:
}

updateiotedge_postoverlay() {
	echo "Updating iotedge system daemons..."

	# Update docker socket in config.yaml
	if [ -e "${ROOTFS_DIR}/etc/iotedge/config.yaml" ]; then
		sed -i -e 's@/var/run/@/run/@g' ${ROOTFS_DIR}/etc/iotedge/config.yaml

		# Move cockpit onboarding json to new location
		if [ -e "${ROOTFS_DIR}/etc/iotedge/onboard.json" ]; then
			mv "${ROOTFS_DIR}/etc/iotedge/onboard.json" "${ROOTFS_DIR}/etc/aziot/onboard.json"
		fi

		# Check if iotedge service is available and active
		if [ -L "${ROOTFS_DIR}/etc/systemd/system/multi-user.target.wants/iotedge.service" ]; then
			rm ${ROOTFS_DIR}/etc/systemd/system/multi-user.target.wants/iotedge.service \
			   ${ROOTFS_DIR}/etc/systemd/system/sockets.target.wants/iotedge.socket \
			   ${ROOTFS_DIR}/etc/systemd/system/sockets.target.wants/iotedge.mgmt.socket
			chroot "${ROOTFS_DIR}" iotedge config import --force
			chroot "${ROOTFS_DIR}" iotedge config apply
			chroot "${ROOTFS_DIR}" systemctl enable aziot-edged
		fi
	fi

	# Check for "bad" HostConfig bind mount, which are usually inserted by iotedge config import as follows:
	#    [agent.config]
	#    image = "mcr.microsoft.com/azureiotedge-agent:1.2"
	#    createOptions = { HostConfig = { Binds = ["/iotedge/storage:/iotedge/storage"] } }
	#
	# This results in failure to start:
	#  HTTP 500 Internal Server Error: error while creating mount source path '/iotedge/storage': mkdir /iotedge: read-only file system
	if [ -e "${ROOTFS_DIR}/etc/aziot/config.toml" ]; then
                if grep -q "/iotedge/storage:/iotedge/storage" "${ROOTFS_DIR}/etc/aziot/config.toml"; then
			sed -e 's@"/iotedge/storage:/iotedge/storage"@"/var/lib/aziot/storage:/iotedge/storage"@g' \
			    -i "${ROOTFS_DIR}/etc/aziot/config.toml"
			chroot "${ROOTFS_DIR}" iotedge config apply
		fi
	fi

	# Add edgeagentuser if not existing
	if ! grep -q "edgeagentuser:x:13622" ${ROOTFS_DIR}/etc/passwd; then
		chroot "${ROOTFS_DIR}" useradd -g iotedge -c "edgeAgent user" -ms /sbin/nologin -u 13622 edgeagentuser
	fi

	# Add edgehubuser if not existing
        if ! grep -q "edgehubuser:x:13623" ${ROOTFS_DIR}/etc/passwd; then
		chroot "${ROOTFS_DIR}" useradd -g iotedge -c "edgeHub user" -ms /sbin/nologin -u 13623 edgehubuser
	fi

	# Adjust certificate and key permissions for CA
	if [ -d "${ROOTFS_DIR}/etc/ssl/private/iotedge-ca" ]; then
		chroot "${ROOTFS_DIR}" chown aziotks:aziotks /etc/ssl/private/iotedge-ca/privkey.pem
		chroot "${ROOTFS_DIR}" chmod 0640 /etc/ssl/private/iotedge-ca/privkey.pem
		chroot "${ROOTFS_DIR}" chown aziotcs:aziotcs $/etc/ssl/private/iotedge-ca/cert.pem
		chroot "${ROOTFS_DIR}" chmod 0644 /etc/ssl/private/iotedge-ca/cert.pem
	fi

	# Bridge config has moved, so update location
	if [ -f "${ROOTFS_DIR}/etc/default/iotedge" ]; then
		mv ${ROOTFS_DIR}/etc/default/iotedge ${ROOTFS_DIR}/etc/default/iotedge.tmp
		mkdir -p ${ROOTFS_DIR}/etc/default/iotedge
		chmod 0775 ${ROOTFS_DIR}/etc/default/iotedge

		mv ${ROOTFS_DIR}/etc/default/iotedge.tmp ${ROOTFS_DIR}/etc/default/iotedge/bridge
		chmod 0664 ${ROOTFS_DIR}/etc/default/iotedge/bridge

		chroot "${ROOTFS_DIR}" chown root:netadmin -R /etc/default/iotedge
	fi

	# Add separate containerd instance to iotedge docker
	if ! grep -q '"containerd":' ${ROOTFS_DIR}/etc/docker/iotedge.json; then
		tmp = $(cat ${ROOTFS_DIR}/etc/docker/iotedge.json)
		tmp = $(echo "$tmp" | jq ".containerd=/run/containerd-iotedge/containerd-iotedge.sock")
		echo "$tmp" > ${ROOTFS_DIR}/etc/docker/iotedge.json
	fi
}
