#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

run_update_hooks() {
	type="$1"

	# Load and run hooks
	if [ -d "/etc/update-hooks.d/" ] ; then
		for m in /etc/update-hooks.d/*; do

		        module=`basename $m | cut -d'-' -f 2`

			# process hook
			. $m

		        eval "${module}_${type}"
		done
	fi
}

finish_enabled() {
	return 0
}

finish_run() {
	if [ -n "${ROOTFS_DIR}" ]; then
		if [ ! -d ${ROOTFS_DIR}/dev ]; then
			fatal "ERROR: There's no '/dev' on rootfs."
		fi

		run_update_hooks "preoverlay"

		if [ -n "$bootparam_overlaytargets" ]; then
			rwdir="/run/overlay"
			mkdir -p $rwdir

			[ -n "$bootparam_overlayfstype" ] && bootparam_overlayfstype="-t $bootparam_overlayfstype"
			[ -n "$bootparam_overlayflags" ] && bootparam_overlayflags="-o $bootparam_overlayflags"

			[ -n "$bootparam_overlay" ] && mount $bootparam_overlay $rwdir $bootparam_overlayfstype $bootparam_overlayflags
			if grep -q $rwdir /proc/mounts; then
				[ -b "$bootparam_overlay" ] && msg "Info: Use block device $bootparam_overlay as overlay"
				[ -f "$bootparam_overlay" ] && msg "Info: Use image file $bootparam_overlay as overlay"
				[ -d "$bootparam_overlay" ] && msg "Info: Use directory $bootparam_overlay as overlay"
			else
				msg "Info: Use tmpfs as overlay"
			fi

			# Handles the OEM rootfs overlay
			if [ -d "$BOOT_LOCATION/oem" ]; then
				oemdir="$BOOT_LOCATION/oem"

				oem_overlay_image=$(find $oemdir | grep ".*-image-oem-.*" | grep -v ".sig$" | sort | tail -n1)
				if [ -n "$oem_overlay_image" ]; then
					verify_file $oem_overlay_image || {
						fatal "Error: $oem_overlay_image Invalid or missing signature"
					}
					msg "Info: $oem_overlay_image Successfully verified"

					mkdir -p /run/.oem_overlay
					mount -o ro $oem_overlay_image /run/.oem_overlay

					msg "Info: Using $oem_overlay_image as OEM rootfs overlay ..."
					mount -t overlay overlay -o lowerdir=/run/.oem_overlay:${ROOTFS_DIR} ${ROOTFS_DIR}
				else
					msg "Error: Unable to find OEM rootfs file ..."
				fi
			fi

			for dir in $bootparam_overlaytargets; do
				msg "Info: Mounting overlay on $dir"

				if [ "$dir" = "/" -o "$dir" = "rootfs" ]; then
					mp="${ROOTFS_DIR}"
					lowerdirs=$mp
					#[ -e $oemdir ] && lowerdirs="$oemdir:$lowerdirs"
					upperdir="$rwdir/rootfs"
					workdir="$rwdir/.rootfs-work"
				else
					dir=$(echo $dir | sed 's/^\///')
					mp="${ROOTFS_DIR}/$dir"
					lowerdirs=$mp
					#[ -e $oemdir/$dir ] && lowerdirs="$oemdir/$dir:$lowerdirs"
					dir=$(echo $dir | sed 's/\//-/g')
					upperdir="$rwdir/$dir"
					workdir="$rwdir/.$dir-work"
				fi

				mkdir -p $upperdir $workdir
				mount -t overlay overlay -o lowerdir=$lowerdirs,upperdir=$upperdir,workdir=$workdir $mp
			done
		fi

		info "Switching root to '${ROOTFS_DIR}'..."

		debug "Moving /dev, /proc, /sys and /run onto rootfs..."
		mount --move /dev ${ROOTFS_DIR}/dev
		mount --move /proc ${ROOTFS_DIR}/proc
		mount --move /sys ${ROOTFS_DIR}/sys
		mount --move /run ${ROOTFS_DIR}/run
		if [ -d /var/platform ]; then
			mkdir -p ${ROOTFS_DIR}/var/platform
			mount --move /var/platform ${ROOTFS_DIR}/var/platform
		fi

		# check if the update was already running - we do not need to
		# to check / run every time, typically this will run after system update
		updated_version=$(cat "${ROOTFS_DIR}/etc/.last_fw_update" 2>/dev/null)
		running_version=$(cat "${ROOTFS_DIR}/firmware.version")
		if [ "${running_version}" != "${updated_version}" ]; then
			run_update_hooks "postoverlay"
			echo "${running_version}" > ${ROOTFS_DIR}/etc/.last_fw_update
		fi

		cd ${ROOTFS_DIR}
		exec switch_root ${ROOTFS_DIR} ${bootparam_init:-/sbin/init}
	else
		debug "No rootfs has been set"
	fi
}
