#!/bin/sh
# Copyright (C) 2011 O.S. Systems Software LTDA.
# Licensed on MIT

finish_enabled() {
	return 0
}

finish_run() {
	if [ -n "$ROOTFS_DIR" ]; then
		if [ ! -d $ROOTFS_DIR/dev ]; then
			__fatal "ERROR: There's no '/dev' on rootfs."
		fi

		__info "Switching root to '$ROOTFS_DIR'..."

		__debug "Moving /dev, /proc and /sys onto rootfs..."
		mount --move /dev $ROOTFS_DIR/dev
		mount --move /proc $ROOTFS_DIR/proc
		mount --move /sys $ROOTFS_DIR/sys

		# Move additional mountpoints
		for mp in $ADDITIONAL_MOUNTPOINTS; do
			mkdir -p ${ROOTFS_DIR}$mp
			mount --move $mp ${ROOTFS_DIR}$mp
			__debug "Moving additional mountpoint: mount --move $mp ${ROOTFS_DIR}$mp"
		done

		cd $ROOTFS_DIR
		exec switch_root -c /dev/console $ROOTFS_DIR ${bootparam_init:-/sbin/init}
	else
		__debug "No rootfs has been set"
	fi
}
