#!/bin/sh

platform_mounts_enabled() {
	return 0
}

platform_mounts_run() {
	# Mount required partitions
	mount -t tmpfs -o size=128K,mode=777 tmpfs ${ROOTFS_DIR}/mnt
	for platform_mnt in backup; do
		backup_dev=$(blkid | grep "LABEL=\"${platform_mnt}\"" | cut -d ":" -f1)
		if [ -n "${backup_dev}" ]; then
			mkdir -p ${ROOTFS_DIR}/mnt/${platform_mnt}
                        [ -n "$bootparam_overlayflags" ] && mountflags="-o $bootparam_overlayflags"
			mount ${mountflags} ${backup_dev} ${ROOTFS_DIR}/mnt/${platform_mnt}
		fi
	done
}
