#   bitbucket.org/bertimus9/systemstat v0.5.0
# [1] git ls-remote https://bitbucket.org/bertimus9/systemstat a9593ffcd68e650a7a948ece6e3cedea1e335947
SRCREV_systemstat="a9593ffcd68e650a7a948ece6e3cedea1e335947"
SRC_URI += "git://bitbucket.org/bertimus9/systemstat;name=systemstat;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/bitbucket.org/bertimus9/systemstat"

#   github.com/GoogleCloudPlatform/k8s-cloud-provider v1.18.1-0.20220218231025-f11817397a1b
# [1] git ls-remote https://github.com/GoogleCloudPlatform/k8s-cloud-provider.git f11817397a1bb27e88115807a9c083a36e12eaf8
SRCREV_k8s-cloud-provider="f11817397a1bb27e88115807a9c083a36e12eaf8"
SRC_URI += "git://github.com/GoogleCloudPlatform/k8s-cloud-provider.git;name=k8s-cloud-provider;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/GoogleCloudPlatform/k8s-cloud-provider"

#   github.com/JeffAshton/win_pdh v0.0.0-20161109143554-76bb4ee9f0ab
# [1] git ls-remote https://github.com/JeffAshton/win_pdh.git 76bb4ee9f0ab50f77826f2a2ee7fb9d3880d6ec2
SRCREV_win_pdh="76bb4ee9f0ab50f77826f2a2ee7fb9d3880d6ec2"
SRC_URI += "git://github.com/JeffAshton/win_pdh.git;name=win_pdh;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/JeffAshton/win_pdh"

#   github.com/Microsoft/go-winio v0.6.0
# [1] git ls-remote https://github.com/microsoft/go-winio.git 376b2013fee695d54f9b21db81716426a8a736d9
SRCREV_go-winio="376b2013fee695d54f9b21db81716426a8a736d9"
SRC_URI += "git://github.com/microsoft/go-winio.git;name=go-winio;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/go-winio"

#   github.com/Microsoft/hcsshim v0.8.25
# [1] git ls-remote https://github.com/microsoft/hcsshim.git 619117bc0844a5d3e9e29f3a24303b7bce5ab9d0
SRCREV_hcsshim="619117bc0844a5d3e9e29f3a24303b7bce5ab9d0"
SRC_URI += "git://github.com/microsoft/hcsshim.git;name=hcsshim;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Microsoft/hcsshim"

#   github.com/armon/circbuf v0.0.0-20150827004946-bbbad097214e
# [1] git ls-remote https://github.com/armon/circbuf.git bbbad097214e2918d8543d5201d12bfd7bca254d
SRCREV_circbuf="bbbad097214e2918d8543d5201d12bfd7bca254d"
SRC_URI += "git://github.com/armon/circbuf.git;name=circbuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/armon/circbuf"

#   github.com/armon/go-socks5 v0.0.0-20160902184237-e75332964ef5
# [1] git ls-remote https://github.com/armon/go-socks5.git e75332964ef517daa070d7c38a9466a0d687e0a5
SRCREV_go-socks5="e75332964ef517daa070d7c38a9466a0d687e0a5"
SRC_URI += "git://github.com/armon/go-socks5.git;name=go-socks5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/armon/go-socks5"

#   github.com/blang/semver/v4 v4.0.0
# [1] git ls-remote https://github.com/blang/semver.git af3461a9cbcf1f3f5889d21b83f5ef63880c33a8
SRCREV_semver-v4="af3461a9cbcf1f3f5889d21b83f5ef63880c33a8"
SRC_URI += "git://github.com/blang/semver.git;name=semver-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/blang/semver/v4"

#   github.com/container-storage-interface/spec v1.8.0
# [1] git ls-remote https://github.com/container-storage-interface/spec.git c7ab2f379311a9ae234ae42bdfbfebfa9c15e538
SRCREV_spec="c7ab2f379311a9ae234ae42bdfbfebfa9c15e538"
SRC_URI += "git://github.com/container-storage-interface/spec.git;name=spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/container-storage-interface/spec"

#   github.com/containerd/cgroups v1.1.0
# [1] git ls-remote https://github.com/containerd/cgroups.git fe7323f622bc222e72473679f12a9089aeeda177
SRCREV_cgroups="fe7323f622bc222e72473679f12a9089aeeda177"
SRC_URI += "git://github.com/containerd/cgroups.git;name=cgroups;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/cgroups"

#   github.com/coredns/corefile-migration v1.0.21
# [1] git ls-remote https://github.com/coredns/corefile-migration.git 3fd650db4c04b82fe0c1677467eff352110fdfca
SRCREV_corefile-migration="3fd650db4c04b82fe0c1677467eff352110fdfca"
SRC_URI += "git://github.com/coredns/corefile-migration.git;name=corefile-migration;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coredns/corefile-migration"

#   github.com/coreos/go-oidc v2.2.1+incompatible
# [1] git ls-remote https://github.com/coreos/go-oidc.git 8d771559cf6e5111c9b9159810d0e4538e7cdc82
SRCREV_go-oidc="8d771559cf6e5111c9b9159810d0e4538e7cdc82"
SRC_URI += "git://github.com/coreos/go-oidc.git;name=go-oidc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coreos/go-oidc"

#   github.com/coreos/go-systemd/v22 v22.5.0
# [1] git ls-remote https://github.com/coreos/go-systemd.git 762d2ddf3fbb263943eaabe85fa0f6bac424d78a
SRCREV_go-systemd-v22="762d2ddf3fbb263943eaabe85fa0f6bac424d78a"
SRC_URI += "git://github.com/coreos/go-systemd.git;name=go-systemd-v22;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coreos/go-systemd/v22"

#   github.com/cpuguy83/go-md2man/v2 v2.0.2
# [1] git ls-remote https://github.com/cpuguy83/go-md2man.git d97078115282836e16d0dca10b4b42ce60fc70e6
SRCREV_go-md2man-v2="d97078115282836e16d0dca10b4b42ce60fc70e6"
SRC_URI += "git://github.com/cpuguy83/go-md2man.git;name=go-md2man-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cpuguy83/go-md2man/v2"

#   github.com/cyphar/filepath-securejoin v0.2.4
# [1] git ls-remote https://github.com/cyphar/filepath-securejoin.git d2b5ebc16d77669416ac176ff84733cf475380ea
SRCREV_filepath-securejoin="d2b5ebc16d77669416ac176ff84733cf475380ea"
SRC_URI += "git://github.com/cyphar/filepath-securejoin.git;name=filepath-securejoin;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cyphar/filepath-securejoin"

#   github.com/distribution/reference v0.5.0
# [1] git ls-remote https://github.com/distribution/reference.git 7be746a6cd867c6cece517b557fa086ca26ac214
SRCREV_reference="7be746a6cd867c6cece517b557fa086ca26ac214"
SRC_URI += "git://github.com/distribution/reference.git;name=reference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/distribution/reference"

#   github.com/docker/go-units v0.5.0
# [1] git ls-remote https://github.com/docker/go-units.git 1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8
SRCREV_go-units="1ffdb9681fc2d4930ee7419feb410cc3eb5e18e8"
SRC_URI += "git://github.com/docker/go-units.git;name=go-units;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/docker/go-units"

#   github.com/emicklei/go-restful/v3 v3.11.0
# [1] git ls-remote https://github.com/emicklei/go-restful.git f5c977ef92e3216a04db6918fee81c8be4b1fc4c
SRCREV_go-restful-v3="f5c977ef92e3216a04db6918fee81c8be4b1fc4c"
SRC_URI += "git://github.com/emicklei/go-restful.git;name=go-restful-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/emicklei/go-restful/v3"

#   github.com/evanphx/json-patch v4.12.0+incompatible
# [1] git ls-remote https://github.com/evanphx/json-patch.git 50fdc0b4c9ab36933e6a0c9288fef3ac5df2b907
SRCREV_json-patch="50fdc0b4c9ab36933e6a0c9288fef3ac5df2b907"
SRC_URI += "git://github.com/evanphx/json-patch.git;name=json-patch;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/evanphx/json-patch"

#   github.com/fsnotify/fsnotify v1.7.0
# [1] git ls-remote https://github.com/fsnotify/fsnotify.git e78666528154600ed55506fb4bd38b758e091c22
SRCREV_fsnotify="e78666528154600ed55506fb4bd38b758e091c22"
SRC_URI += "git://github.com/fsnotify/fsnotify.git;name=fsnotify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fsnotify/fsnotify"

#   github.com/go-logr/logr v1.4.1
# [1] git ls-remote https://github.com/go-logr/logr.git dcdc3f2cd12e8a5c4e2a6712d6958c90e2e5bd98
SRCREV_logr="dcdc3f2cd12e8a5c4e2a6712d6958c90e2e5bd98"
SRC_URI += "git://github.com/go-logr/logr.git;name=logr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/logr"

#   github.com/godbus/dbus/v5 v5.1.0
# [1] git ls-remote https://github.com/godbus/dbus.git e523abc905595cf17fb0001a7d77eaaddfaa216d
SRCREV_dbus-v5="e523abc905595cf17fb0001a7d77eaaddfaa216d"
SRC_URI += "git://github.com/godbus/dbus.git;name=dbus-v5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/godbus/dbus/v5"

#   github.com/gogo/protobuf v1.3.2
# [1] git ls-remote https://github.com/gogo/protobuf.git b03c65ea87cdc3521ede29f62fe3ce239267c1bc
SRCREV_protobuf="b03c65ea87cdc3521ede29f62fe3ce239267c1bc"
SRC_URI += "git://github.com/gogo/protobuf.git;name=protobuf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gogo/protobuf"

#   github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
# [1] git ls-remote https://github.com/golang/groupcache.git 41bb18bfe9da5321badc438f91158cd790a33aa3
SRCREV_groupcache="41bb18bfe9da5321badc438f91158cd790a33aa3"
SRC_URI += "git://github.com/golang/groupcache.git;name=groupcache;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/groupcache"

#   github.com/golang/mock v1.6.0
# [1] git ls-remote https://github.com/golang/mock.git aba2ff9a6844d5e3289e8472d3217d5b3090f083
SRCREV_mock="aba2ff9a6844d5e3289e8472d3217d5b3090f083"
SRC_URI += "git://github.com/golang/mock.git;name=mock;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/mock"

#   github.com/golang/protobuf v1.5.4
# [1] git ls-remote https://github.com/golang/protobuf.git 75de7c059e36b64f01d0dd234ff2fff404ec3374
SRCREV_protobufv1_5_4="75de7c059e36b64f01d0dd234ff2fff404ec3374"
SRC_URI += "git://github.com/golang/protobuf.git;name=protobufv1_5_4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang/protobuf"

#   github.com/google/cadvisor v0.49.0
# [1] git ls-remote https://github.com/google/cadvisor.git 8b80fdb206efd4b2fd02cc1ff269a9a80b10396f
SRCREV_cadvisor="8b80fdb206efd4b2fd02cc1ff269a9a80b10396f"
SRC_URI += "git://github.com/google/cadvisor.git;name=cadvisor;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/cadvisor"

#   github.com/google/cel-go v0.17.8
# [1] git ls-remote https://github.com/google/cel-go.git 98b8351f702d7a298bdf8f40bb995c76ecd35ed2
SRCREV_cel-go="98b8351f702d7a298bdf8f40bb995c76ecd35ed2"
SRC_URI += "git://github.com/google/cel-go.git;name=cel-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/cel-go"

#   github.com/google/gnostic-models v0.6.8
# [1] git ls-remote https://github.com/google/gnostic-models.git 577692584cdf09674595bba0c182d0e8a44655d3
SRCREV_gnostic-models="577692584cdf09674595bba0c182d0e8a44655d3"
SRC_URI += "git://github.com/google/gnostic-models.git;name=gnostic-models;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gnostic-models"

#   github.com/google/go-cmp v0.6.0
# [1] git ls-remote https://github.com/google/go-cmp.git c3ad8435e7bef96af35732bc0789e5a2278c6d5f
SRCREV_go-cmp="c3ad8435e7bef96af35732bc0789e5a2278c6d5f"
SRC_URI += "git://github.com/google/go-cmp.git;name=go-cmp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/go-cmp"

#   github.com/google/gofuzz v1.2.0
# [1] git ls-remote https://github.com/google/gofuzz.git 41febe7ec24d8c0e442e940f3f15ee4e8511c447
SRCREV_gofuzz="41febe7ec24d8c0e442e940f3f15ee4e8511c447"
SRC_URI += "git://github.com/google/gofuzz.git;name=gofuzz;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/gofuzz"

#   github.com/google/uuid v1.3.0
# [1] git ls-remote https://github.com/google/uuid.git 44b5fee7c49cf3bcdf723f106b36d56ef13ccc88
SRCREV_uuid="44b5fee7c49cf3bcdf723f106b36d56ef13ccc88"
SRC_URI += "git://github.com/google/uuid.git;name=uuid;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/uuid"

#   github.com/ishidawataru/sctp v0.0.0-20230406120618-7ff4192f6ff2
# [1] git ls-remote https://github.com/ishidawataru/sctp.git 7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0
SRCREV_sctp="7ff4192f6ff2b4b181ec7dce269bdf4076ff90a0"
SRC_URI += "git://github.com/ishidawataru/sctp.git;name=sctp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/ishidawataru/sctp"

#   github.com/libopenstorage/openstorage v1.0.0
# [1] git ls-remote https://github.com/libopenstorage/openstorage.git a0608a35f2d0151fe79b4761a8780621fd83dc27
SRCREV_openstorage="a0608a35f2d0151fe79b4761a8780621fd83dc27"
SRC_URI += "git://github.com/libopenstorage/openstorage.git;name=openstorage;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/libopenstorage/openstorage"

#   github.com/lithammer/dedent v1.1.0
# [1] git ls-remote https://github.com/lithammer/dedent.git 7da0ef12e7f6e16e724290d47c139520f1ad6171
SRCREV_dedent="7da0ef12e7f6e16e724290d47c139520f1ad6171"
SRC_URI += "git://github.com/lithammer/dedent.git;name=dedent;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/lithammer/dedent"

#   github.com/moby/ipvs v1.1.0
# [1] git ls-remote https://github.com/moby/ipvs.git aab21766fdbf9b5613a59f85cd88f5e038307307
SRCREV_ipvs="aab21766fdbf9b5613a59f85cd88f5e038307307"
SRC_URI += "git://github.com/moby/ipvs.git;name=ipvs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/ipvs"

#   github.com/mrunalp/fileutils v0.5.1
# [1] git ls-remote https://github.com/mrunalp/fileutils.git 7363e975f9cfb558be601bece0df81714c3c9084
SRCREV_fileutils="7363e975f9cfb558be601bece0df81714c3c9084"
SRC_URI += "git://github.com/mrunalp/fileutils.git;name=fileutils;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mrunalp/fileutils"

#   github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
# [1] git ls-remote https://github.com/munnerz/goautoneg.git a7dc8b61c822528f973a5e4e7b272055c6fdb43e
SRCREV_goautoneg="a7dc8b61c822528f973a5e4e7b272055c6fdb43e"
SRC_URI += "git://github.com/munnerz/goautoneg.git;name=goautoneg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/munnerz/goautoneg"

#   github.com/onsi/ginkgo/v2 v2.15.0
# [1] git ls-remote https://github.com/onsi/ginkgo.git 7fa019079a7b6cfe92acac92df4a84f2748e45a4
SRCREV_ginkgo-v2="7fa019079a7b6cfe92acac92df4a84f2748e45a4"
SRC_URI += "git://github.com/onsi/ginkgo.git;name=ginkgo-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/onsi/ginkgo/v2"

#   github.com/onsi/gomega v1.31.0
# [1] git ls-remote https://github.com/onsi/gomega.git ba8bba2272bbf185a144b2681b5ed1f72d7f04f7
SRCREV_gomega="ba8bba2272bbf185a144b2681b5ed1f72d7f04f7"
SRC_URI += "git://github.com/onsi/gomega.git;name=gomega;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/onsi/gomega"

#   github.com/opencontainers/runc v1.1.12
# [1] git ls-remote https://github.com/opencontainers/runc.git 20381324e21b5b232fea74d448b5975d85d34d25
SRCREV_runc="20381324e21b5b232fea74d448b5975d85d34d25"
SRC_URI += "git://github.com/opencontainers/runc.git;name=runc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runc"

#   github.com/opencontainers/selinux v1.11.0
# [1] git ls-remote https://github.com/opencontainers/selinux.git b68c45eb2df48c6b0c949901ccda90c8e65fe677
SRCREV_selinux="b68c45eb2df48c6b0c949901ccda90c8e65fe677"
SRC_URI += "git://github.com/opencontainers/selinux.git;name=selinux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/selinux"

#   github.com/pkg/errors v0.9.1
# [1] git ls-remote https://github.com/pkg/errors.git 614d223910a179a466c1767a985424175c39b465
SRCREV_errors="614d223910a179a466c1767a985424175c39b465"
SRC_URI += "git://github.com/pkg/errors.git;name=errors;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pkg/errors"

#   github.com/pmezard/go-difflib v1.0.0
# [1] git ls-remote https://github.com/pmezard/go-difflib.git c0b812dadcf4498dede02bb7f0c5c478be997e34
SRCREV_go-difflib="c0b812dadcf4498dede02bb7f0c5c478be997e34"
SRC_URI += "git://github.com/pmezard/go-difflib.git;name=go-difflib;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pmezard/go-difflib"

#   github.com/prometheus/client_golang v1.16.0
# [1] git ls-remote https://github.com/prometheus/client_golang.git 3583c1e1d085b75cab406c78b015562d45552b39
SRCREV_client_golang="3583c1e1d085b75cab406c78b015562d45552b39"
SRC_URI += "git://github.com/prometheus/client_golang.git;name=client_golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_golang"

#   github.com/prometheus/client_model v0.4.0
# [1] git ls-remote https://github.com/prometheus/client_model.git 91c3945f2cfbfb9040e34a0b6764d804b5a5a490
SRCREV_client_model="91c3945f2cfbfb9040e34a0b6764d804b5a5a490"
SRC_URI += "git://github.com/prometheus/client_model.git;name=client_model;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/client_model"

#   github.com/prometheus/common v0.44.0
# [1] git ls-remote https://github.com/prometheus/common.git 94bf9828e56d9670579b28a9f78237d3cd8d0395
SRCREV_common="94bf9828e56d9670579b28a9f78237d3cd8d0395"
SRC_URI += "git://github.com/prometheus/common.git;name=common;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/common"

#   github.com/robfig/cron/v3 v3.0.1
# [1] git ls-remote https://github.com/robfig/cron.git ccba498c397bb90a9c84945bbb0f7af2d72b6309
SRCREV_cron-v3="ccba498c397bb90a9c84945bbb0f7af2d72b6309"
SRC_URI += "git://github.com/robfig/cron.git;name=cron-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/robfig/cron/v3"

#   github.com/spf13/cobra v1.7.0
# [1] git ls-remote https://github.com/spf13/cobra.git 4dd4b25de38418174a6e859e8a32eaccca32dccc
SRCREV_cobra="4dd4b25de38418174a6e859e8a32eaccca32dccc"
SRC_URI += "git://github.com/spf13/cobra.git;name=cobra;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/cobra"

#   github.com/spf13/pflag v1.0.5
# [1] git ls-remote https://github.com/spf13/pflag.git 2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab
SRCREV_pflag="2e9d26c8c37aae03e3f9d4e90b7116f5accb7cab"
SRC_URI += "git://github.com/spf13/pflag.git;name=pflag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/spf13/pflag"

#   github.com/stretchr/testify v1.8.4
# [1] git ls-remote https://github.com/stretchr/testify.git f97607b89807936ac4ff96748d766cf4b9711f78
SRCREV_testify="f97607b89807936ac4ff96748d766cf4b9711f78"
SRC_URI += "git://github.com/stretchr/testify.git;name=testify;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stretchr/testify"

#   github.com/vishvananda/netlink v1.1.0
# [1] git ls-remote https://github.com/vishvananda/netlink.git f049be6f391489d3f374498fe0c8df8449258372
SRCREV_netlink="f049be6f391489d3f374498fe0c8df8449258372"
SRC_URI += "git://github.com/vishvananda/netlink.git;name=netlink;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/vishvananda/netlink"

#   go.etcd.io/etcd/api/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_api-v3="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=api-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/api/v3"

#   go.etcd.io/etcd/client/pkg/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_pkg-v3="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=pkg-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/client/pkg/v3"

#   go.etcd.io/etcd/client/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_client-v3="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=client-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/client/v3"

#   go.opentelemetry.io/proto/otlp v1.0.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-proto-go 97744b2e4a0fa6787b96b9c3c740daefca754333
SRCREV_otlp="97744b2e4a0fa6787b96b9c3c740daefca754333"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-proto-go;name=otlp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/proto/otlp"

#   go.opentelemetry.io/otel v1.19.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go 60666c554065ac4da502fe28943eea4b938ab479
SRCREV_otel="60666c554065ac4da502fe28943eea4b938ab479"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go;name=otel;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/otel"

#   go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp v0.44.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib fdfa6e3abf03caa6a1d3267913e01526d97eab8a
SRCREV_otelhttp="fdfa6e3abf03caa6a1d3267913e01526d97eab8a"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelhttp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp"

#   go.opentelemetry.io/contrib/instrumentation/github.com/emicklei/go-restful/otelrestful v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 849072ef827b4abab754253e1e63e7b410a31084
SRCREV_otelrestful="849072ef827b4abab754253e1e63e7b410a31084"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelrestful;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/github.com/emicklei/go-restful/otelrestful"

#   go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.42.0
# [1] git ls-remote https://github.com/open-telemetry/opentelemetry-go-contrib 849072ef827b4abab754253e1e63e7b410a31084
SRCREV_otelgrpc="849072ef827b4abab754253e1e63e7b410a31084"
SRC_URI += "git://github.com/open-telemetry/opentelemetry-go-contrib;name=otelgrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc"

#   go.uber.org/goleak v1.3.0
# [1] git ls-remote https://github.com/uber-go/goleak 31095c657c34bba405a8d480db27989aa5f60b9c
SRCREV_goleak="31095c657c34bba405a8d480db27989aa5f60b9c"
SRC_URI += "git://github.com/uber-go/goleak;name=goleak;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/goleak"

#   go.uber.org/zap v1.26.0
# [1] git ls-remote https://github.com/uber-go/zap ed19d16419a33a596048f7465ce60021b7711dc9
SRCREV_zap="ed19d16419a33a596048f7465ce60021b7711dc9"
SRC_URI += "git://github.com/uber-go/zap;name=zap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/zap"

#   golang.org/x/crypto v0.21.0
# [1] git ls-remote https://go.googlesource.com/crypto 7067223927c4e3f3bb91a5c6e0d2aae83df74e7a
SRCREV_crypto="7067223927c4e3f3bb91a5c6e0d2aae83df74e7a"
SRC_URI += "git://go.googlesource.com/crypto;name=crypto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/crypto"

#   golang.org/x/net v0.23.0
# [1] git ls-remote https://go.googlesource.com/net c48da131589f122489348be5dfbcb6457640046f
SRCREV_net="c48da131589f122489348be5dfbcb6457640046f"
SRC_URI += "git://go.googlesource.com/net;name=net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/net"

#   golang.org/x/oauth2 v0.10.0
# [1] git ls-remote https://go.googlesource.com/oauth2 ec5679f607c139709bdc4c2608494d56b95611fe
SRCREV_oauth2="ec5679f607c139709bdc4c2608494d56b95611fe"
SRC_URI += "git://go.googlesource.com/oauth2;name=oauth2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/oauth2"

#   golang.org/x/sync v0.6.0
# [1] git ls-remote https://go.googlesource.com/sync 59c1ca1e4661ed4452be4069ceea3c233f4deec1
SRCREV_sync="59c1ca1e4661ed4452be4069ceea3c233f4deec1"
SRC_URI += "git://go.googlesource.com/sync;name=sync;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sync"

#   golang.org/x/sys v0.18.0
# [1] git ls-remote https://go.googlesource.com/sys 360f961f8978a4c9a7c2e849bb482780cd6bb553
SRCREV_sys="360f961f8978a4c9a7c2e849bb482780cd6bb553"
SRC_URI += "git://go.googlesource.com/sys;name=sys;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/sys"

#   golang.org/x/term v0.18.0
# [1] git ls-remote https://go.googlesource.com/term c5eaf76d63c69ba9d890c5969f892022e97598da
SRCREV_term="c5eaf76d63c69ba9d890c5969f892022e97598da"
SRC_URI += "git://go.googlesource.com/term;name=term;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/term"

#   golang.org/x/time v0.3.0
# [1] git ls-remote https://go.googlesource.com/time 2c09566ef13fb5556401ddff3c53c3dbc2a42dac
SRCREV_time="2c09566ef13fb5556401ddff3c53c3dbc2a42dac"
SRC_URI += "git://go.googlesource.com/time;name=time;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/time"

#   golang.org/x/tools v0.18.0
# [1] git ls-remote https://go.googlesource.com/tools c5643e9baf7fed6936d70e3abf925f86fa895ca1
SRCREV_tools="c5643e9baf7fed6936d70e3abf925f86fa895ca1"
SRC_URI += "git://go.googlesource.com/tools;name=tools;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/tools"

#   google.golang.org/api v0.126.0
# [1] git ls-remote https://github.com/googleapis/google-api-go-client 884dbd55027ea2033d627d3b82901eee4e3d97c7
SRCREV_api="884dbd55027ea2033d627d3b82901eee4e3d97c7"
SRC_URI += "git://github.com/googleapis/google-api-go-client;name=api;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/api"

#   google.golang.org/genproto/googleapis/rpc v0.0.0-20230822172742-b8732ec3820d
# [1] git ls-remote https://github.com/googleapis/go-genproto b8732ec3820db4bd1e4eda89392b7728e81bd825
SRCREV_rpc="b8732ec3820db4bd1e4eda89392b7728e81bd825"
SRC_URI += "git://github.com/googleapis/go-genproto;name=rpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto/googleapis/rpc"

#   google.golang.org/grpc v1.58.3
# [1] git ls-remote https://github.com/grpc/grpc-go bf05b9558c16677e362d231120f8213eb276d406
SRCREV_grpc="bf05b9558c16677e362d231120f8213eb276d406"
SRC_URI += "git://github.com/grpc/grpc-go;name=grpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/grpc"

#   google.golang.org/protobuf v1.33.0
# [1] git ls-remote https://go.googlesource.com/protobuf ec47fd138f9221b19a2afd6570b3c39ede9df3dc
SRCREV_protobufv1_33_0="ec47fd138f9221b19a2afd6570b3c39ede9df3dc"
SRC_URI += "git://go.googlesource.com/protobuf;name=protobufv1_33_0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/protobuf"

#   gopkg.in/square/go-jose.v2 v2.6.0
# [1] git ls-remote https://gopkg.in/square/go-jose.v2 607249a5a5c49149329c9200230c602c9bd80bb7
SRCREV_go-jose.v2="607249a5a5c49149329c9200230c602c9bd80bb7"
SRC_URI += "git://gopkg.in/square/go-jose.v2;name=go-jose.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/square/go-jose.v2"

#   gopkg.in/yaml.v2 v2.4.0
# [1] git ls-remote https://gopkg.in/yaml.v2 7649d4548cb53a614db133b2a8ac1f31859dda8c
SRCREV_yaml.v2="7649d4548cb53a614db133b2a8ac1f31859dda8c"
SRC_URI += "git://gopkg.in/yaml.v2;name=yaml.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v2"

#   gopkg.in/yaml.v3 v3.0.1
# [1] git ls-remote https://gopkg.in/yaml.v3 f6f7691b1fdeb513f56608cd2c32c51f8194bf51
SRCREV_yaml.v3="f6f7691b1fdeb513f56608cd2c32c51f8194bf51"
SRC_URI += "git://gopkg.in/yaml.v3;name=yaml.v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/yaml.v3"

#   k8s.io/klog/v2 v2.120.1
# [1] git ls-remote https://github.com/kubernetes/klog 007e661a007dacdf017ad9c1b53e9f96d32d4b7d
SRCREV_klog-v2="007e661a007dacdf017ad9c1b53e9f96d32d4b7d"
SRC_URI += "git://github.com/kubernetes/klog;name=klog-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/klog/v2"

#   k8s.io/kube-openapi v0.0.0-20240228011516-70dd3763d340
# [1] git ls-remote https://github.com/kubernetes/kube-openapi 70dd3763d340b13ccc008be05cb1f59ff245dbfd
SRCREV_kube-openapi="70dd3763d340b13ccc008be05cb1f59ff245dbfd"
SRC_URI += "git://github.com/kubernetes/kube-openapi;name=kube-openapi;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/kube-openapi"

#   k8s.io/system-validators v1.8.0
# [1] git ls-remote https://github.com/kubernetes/system-validators 737f948078e6648f34337a8aaff892f1d846bf6b
SRCREV_system-validators="737f948078e6648f34337a8aaff892f1d846bf6b"
SRC_URI += "git://github.com/kubernetes/system-validators;name=system-validators;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/system-validators"

#   k8s.io/utils v0.0.0-20230726121419-3b25d923346b
# [1] git ls-remote https://github.com/kubernetes/utils 3b25d923346b3814e0898684c97390092f31a61e
SRCREV_utils="3b25d923346b3814e0898684c97390092f31a61e"
SRC_URI += "git://github.com/kubernetes/utils;name=utils;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/utils"

#   sigs.k8s.io/knftables v0.0.14
# [1] git ls-remote https://github.com/kubernetes-sigs/knftables 634465fd3248dc1826c1d6d6d5d617d7027c79f8
SRCREV_knftables="634465fd3248dc1826c1d6d6d5d617d7027c79f8"
SRC_URI += "git://github.com/kubernetes-sigs/knftables;name=knftables;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/knftables"

#   sigs.k8s.io/structured-merge-diff/v4 v4.4.1
# [1] git ls-remote https://github.com/kubernetes-sigs/structured-merge-diff cf09e71f4508bfc416135048e392a8a4990bf4e3
SRCREV_structured-merge-diff-v4="cf09e71f4508bfc416135048e392a8a4990bf4e3"
SRC_URI += "git://github.com/kubernetes-sigs/structured-merge-diff;name=structured-merge-diff-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/structured-merge-diff/v4"

#   sigs.k8s.io/yaml v1.3.0
# [1] git ls-remote https://github.com/kubernetes-sigs/yaml 9535b3b1e2893fe44efb37c5c9f5665e245d786a
SRCREV_yaml="9535b3b1e2893fe44efb37c5c9f5665e245d786a"
SRC_URI += "git://github.com/kubernetes-sigs/yaml;name=yaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/yaml"

#   cloud.google.com/go/compute v1.23.0
# [1] git ls-remote https://github.com/googleapis/google-cloud-go 2d046059cc09ddd72eb2c58fac2fdadce81e82b3
SRCREV_compute="2d046059cc09ddd72eb2c58fac2fdadce81e82b3"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=compute;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/compute"

#   cloud.google.com/go/compute/metadata v0.2.3
# [1] git ls-remote https://github.com/googleapis/google-cloud-go 115646cd9d1d0b6429d216b286e8b6accc767486
SRCREV_metadata="115646cd9d1d0b6429d216b286e8b6accc767486"
SRC_URI += "git://github.com/googleapis/google-cloud-go;name=metadata;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/cloud.google.com/go/compute/metadata"

#   github.com/Azure/go-ansiterm v0.0.0-20210617225240-d185dfc1b5a1
# [1] git ls-remote https://github.com/Azure/go-ansiterm.git d185dfc1b5a126116ea5a19e148e29d16b4574c9
SRCREV_go-ansiterm="d185dfc1b5a126116ea5a19e148e29d16b4574c9"
SRC_URI += "git://github.com/Azure/go-ansiterm.git;name=go-ansiterm;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/Azure/go-ansiterm"

#   github.com/MakeNowJust/heredoc v1.0.0
# [1] git ls-remote https://github.com/makenowjust/heredoc.git bbd9af33722b79a933ef99c7c94833065e2d6c20
SRCREV_heredoc="bbd9af33722b79a933ef99c7c94833065e2d6c20"
SRC_URI += "git://github.com/makenowjust/heredoc.git;name=heredoc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/MakeNowJust/heredoc"

#   github.com/NYTimes/gziphandler v1.1.1
# [1] git ls-remote https://github.com/nytimes/gziphandler.git dd0439581c7657cb652dfe5c71d7d48baf39541d
SRCREV_gziphandler="dd0439581c7657cb652dfe5c71d7d48baf39541d"
SRC_URI += "git://github.com/nytimes/gziphandler.git;name=gziphandler;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/NYTimes/gziphandler"

#   github.com/antlr/antlr4/runtime/Go/antlr/v4 v4.0.0-20230305170008-8188dc5388df
# [1] git ls-remote https://github.com/antlr/antlr4.git 8188dc5388dfe9246deb9b6ae507c3693fd55c3f
SRCREV_antlr-v4="8188dc5388dfe9246deb9b6ae507c3693fd55c3f"
SRC_URI += "git://github.com/antlr/antlr4.git;name=antlr-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/antlr/antlr4/runtime/Go/antlr/v4"

#   github.com/asaskevich/govalidator v0.0.0-20190424111038-f61b66f89f4a
# [1] git ls-remote https://github.com/asaskevich/govalidator.git f61b66f89f4a311bef65f13e575bcf1a2ffadda6
SRCREV_govalidator="f61b66f89f4a311bef65f13e575bcf1a2ffadda6"
SRC_URI += "git://github.com/asaskevich/govalidator.git;name=govalidator;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/asaskevich/govalidator"

#   github.com/beorn7/perks v1.0.1
# [1] git ls-remote https://github.com/beorn7/perks.git c49ff274687222a7373c4cd83578f1065cf3e143
SRCREV_perks="c49ff274687222a7373c4cd83578f1065cf3e143"
SRC_URI += "git://github.com/beorn7/perks.git;name=perks;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/beorn7/perks"

#   github.com/cenkalti/backoff/v4 v4.2.1
# [1] git ls-remote https://github.com/cenkalti/backoff.git a04a6fe64ffb0e3fd0816460529d300be5f252df
SRCREV_backoff-v4="a04a6fe64ffb0e3fd0816460529d300be5f252df"
SRC_URI += "git://github.com/cenkalti/backoff.git;name=backoff-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cenkalti/backoff/v4"

#   github.com/cespare/xxhash/v2 v2.2.0
# [1] git ls-remote https://github.com/cespare/xxhash.git 50472e8238a5564de4b2f10531e8b6d1529876e8
SRCREV_xxhash-v2="50472e8238a5564de4b2f10531e8b6d1529876e8"
SRC_URI += "git://github.com/cespare/xxhash.git;name=xxhash-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cespare/xxhash/v2"

#   github.com/chai2010/gettext-go v1.0.2
# [1] git ls-remote https://github.com/chai2010/gettext-go.git f07b08dc491934f7941fd0e57c7c20f1feb8716d
SRCREV_gettext-go="f07b08dc491934f7941fd0e57c7c20f1feb8716d"
SRC_URI += "git://github.com/chai2010/gettext-go.git;name=gettext-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/chai2010/gettext-go"

#   github.com/checkpoint-restore/go-criu/v5 v5.3.0
# [1] git ls-remote https://github.com/checkpoint-restore/go-criu.git 571ae4df11b462a8ec384ae52e16a3a3c0cfd348
SRCREV_go-criu-v5="571ae4df11b462a8ec384ae52e16a3a3c0cfd348"
SRC_URI += "git://github.com/checkpoint-restore/go-criu.git;name=go-criu-v5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/checkpoint-restore/go-criu/v5"

#   github.com/cilium/ebpf v0.9.1
# [1] git ls-remote https://github.com/cilium/ebpf.git d560e4479b395c4523851a4571b04ba0b3846cd1
SRCREV_ebpf="d560e4479b395c4523851a4571b04ba0b3846cd1"
SRC_URI += "git://github.com/cilium/ebpf.git;name=ebpf;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cilium/ebpf"

#   github.com/containerd/console v1.0.3
# [1] git ls-remote https://github.com/containerd/console.git 060a791de16aeb90b3bb4dcd78dfec3ca45fa5df
SRCREV_console="060a791de16aeb90b3bb4dcd78dfec3ca45fa5df"
SRC_URI += "git://github.com/containerd/console.git;name=console;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/console"

#   github.com/containerd/ttrpc v1.2.2
# [1] git ls-remote https://github.com/containerd/ttrpc.git ac26f8cbea1c440d451dd19a4a1b847fd073f3c3
SRCREV_ttrpc="ac26f8cbea1c440d451dd19a4a1b847fd073f3c3"
SRC_URI += "git://github.com/containerd/ttrpc.git;name=ttrpc;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/containerd/ttrpc"

#   github.com/coredns/caddy v1.1.1
# [1] git ls-remote https://github.com/coredns/caddy.git 8adcfe62194e7ae9f1a7cf952a02dff49e9dc6bd
SRCREV_caddy="8adcfe62194e7ae9f1a7cf952a02dff49e9dc6bd"
SRC_URI += "git://github.com/coredns/caddy.git;name=caddy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coredns/caddy"

#   github.com/coreos/go-semver v0.3.1
# [1] git ls-remote https://github.com/coreos/go-semver.git abe97b7f7eb1e0a15220883251bd38f5f64db0b9
SRCREV_go-semver="abe97b7f7eb1e0a15220883251bd38f5f64db0b9"
SRC_URI += "git://github.com/coreos/go-semver.git;name=go-semver;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/coreos/go-semver"

#   github.com/davecgh/go-spew v1.1.1
# [1] git ls-remote https://github.com/davecgh/go-spew.git 152484fe5c9ff65d013f0f372d748c03e8749e6d
SRCREV_go-spew="152484fe5c9ff65d013f0f372d748c03e8749e6d"
SRC_URI += "git://github.com/davecgh/go-spew.git;name=go-spew;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/davecgh/go-spew"

#   github.com/daviddengcn/go-colortext v1.0.0
# [1] git ls-remote https://github.com/daviddengcn/go-colortext.git dc4cd66b56a892657c0bea8bf4389d35210ce0ee
SRCREV_go-colortext="dc4cd66b56a892657c0bea8bf4389d35210ce0ee"
SRC_URI += "git://github.com/daviddengcn/go-colortext.git;name=go-colortext;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/daviddengcn/go-colortext"

#   github.com/dustin/go-humanize v1.0.1
# [1] git ls-remote https://github.com/dustin/go-humanize.git e308a8fc2981a19ebce7ae9d7c32094fe2b7baad
SRCREV_go-humanize="e308a8fc2981a19ebce7ae9d7c32094fe2b7baad"
SRC_URI += "git://github.com/dustin/go-humanize.git;name=go-humanize;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/dustin/go-humanize"

#   github.com/euank/go-kmsg-parser v2.0.0+incompatible
# [1] git ls-remote https://github.com/euank/go-kmsg-parser.git 5ba4d492e455a77d25dcf0d2c4acc9f2afebef4e
SRCREV_go-kmsg-parser="5ba4d492e455a77d25dcf0d2c4acc9f2afebef4e"
SRC_URI += "git://github.com/euank/go-kmsg-parser.git;name=go-kmsg-parser;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/euank/go-kmsg-parser"

#   github.com/exponent-io/jsonpath v0.0.0-20151013193312-d6023ce2651d
# [1] git ls-remote https://github.com/exponent-io/jsonpath.git d6023ce2651d8eafb5c75bb0c7167536102ec9f5
SRCREV_jsonpath="d6023ce2651d8eafb5c75bb0c7167536102ec9f5"
SRC_URI += "git://github.com/exponent-io/jsonpath.git;name=jsonpath;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/exponent-io/jsonpath"

#   github.com/fatih/camelcase v1.0.0
# [1] git ls-remote https://github.com/fatih/camelcase.git 44e46d280b43ec1531bb25252440e34f1b800b65
SRCREV_camelcase="44e46d280b43ec1531bb25252440e34f1b800b65"
SRC_URI += "git://github.com/fatih/camelcase.git;name=camelcase;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fatih/camelcase"

#   github.com/felixge/httpsnoop v1.0.3
# [1] git ls-remote https://github.com/felixge/httpsnoop.git ef9fc62cdc3cc5abc33d6018fe1324890bb48145
SRCREV_httpsnoop="ef9fc62cdc3cc5abc33d6018fe1324890bb48145"
SRC_URI += "git://github.com/felixge/httpsnoop.git;name=httpsnoop;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/felixge/httpsnoop"

#   github.com/fvbommel/sortorder v1.1.0
# [1] git ls-remote https://github.com/fvbommel/sortorder.git a8d9302c17f9f46c6580b82b919672e58ef6e396
SRCREV_sortorder="a8d9302c17f9f46c6580b82b919672e58ef6e396"
SRC_URI += "git://github.com/fvbommel/sortorder.git;name=sortorder;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fvbommel/sortorder"

#   github.com/fxamacker/cbor/v2 v2.6.0
# [1] git ls-remote https://github.com/fxamacker/cbor.git 1f67e1e4b1131ae0ea0b52955606b1ef47307f62
SRCREV_cbor-v2="1f67e1e4b1131ae0ea0b52955606b1ef47307f62"
SRC_URI += "git://github.com/fxamacker/cbor.git;name=cbor-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/fxamacker/cbor/v2"

#   github.com/go-errors/errors v1.4.2
# [1] git ls-remote https://github.com/go-errors/errors.git 33d496f939bc762321a636d4035e15c302eb0b00
SRCREV_errorsv1_4_2="33d496f939bc762321a636d4035e15c302eb0b00"
SRC_URI += "git://github.com/go-errors/errors.git;name=errorsv1_4_2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-errors/errors"

#   github.com/go-logr/stdr v1.2.2
# [1] git ls-remote https://github.com/go-logr/stdr.git 521af2addfa7c81c8a65d0e85ed34bb6bb6dc262
SRCREV_stdr="521af2addfa7c81c8a65d0e85ed34bb6bb6dc262"
SRC_URI += "git://github.com/go-logr/stdr.git;name=stdr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/stdr"

#   github.com/go-logr/zapr v1.3.0
# [1] git ls-remote https://github.com/go-logr/zapr.git 78b8af5329abd1ba8695aad821f95fb2e7f4e651
SRCREV_zapr="78b8af5329abd1ba8695aad821f95fb2e7f4e651"
SRC_URI += "git://github.com/go-logr/zapr.git;name=zapr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-logr/zapr"

#   github.com/go-openapi/jsonpointer v0.19.6
# [1] git ls-remote https://github.com/go-openapi/jsonpointer.git 5df0d69a6be189afff354877d332f9ede32afe12
SRCREV_jsonpointer="5df0d69a6be189afff354877d332f9ede32afe12"
SRC_URI += "git://github.com/go-openapi/jsonpointer.git;name=jsonpointer;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonpointer"

#   github.com/go-openapi/jsonreference v0.20.2
# [1] git ls-remote https://github.com/go-openapi/jsonreference.git 4bc87e59f54ca39b8a39859a30d34583eb466b3a
SRCREV_jsonreference="4bc87e59f54ca39b8a39859a30d34583eb466b3a"
SRC_URI += "git://github.com/go-openapi/jsonreference.git;name=jsonreference;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/jsonreference"

#   github.com/go-openapi/swag v0.22.3
# [1] git ls-remote https://github.com/go-openapi/swag.git 2b96580f970aa8746d598fbe976d922905b9065f
SRCREV_swag="2b96580f970aa8746d598fbe976d922905b9065f"
SRC_URI += "git://github.com/go-openapi/swag.git;name=swag;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-openapi/swag"

#   github.com/go-task/slim-sprig v0.0.0-20230315185526-52ccab3ef572
# [1] git ls-remote https://github.com/go-task/slim-sprig.git 52ccab3ef572c7e1a2c258be183f9a9296d60152
SRCREV_slim-sprig="52ccab3ef572c7e1a2c258be183f9a9296d60152"
SRC_URI += "git://github.com/go-task/slim-sprig.git;name=slim-sprig;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/go-task/slim-sprig"

#   github.com/golang-jwt/jwt/v4 v4.5.0
# [1] git ls-remote https://github.com/golang-jwt/jwt.git 9358574a7a1a2c8d644f22b6e8de627ba85c58d0
SRCREV_jwt-v4="9358574a7a1a2c8d644f22b6e8de627ba85c58d0"
SRC_URI += "git://github.com/golang-jwt/jwt.git;name=jwt-v4;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/golang-jwt/jwt/v4"

#   github.com/google/btree v1.0.1
# [1] git ls-remote https://github.com/google/btree.git 479b5e81b0a93ec038d201b0b33d17db599531d3
SRCREV_btree="479b5e81b0a93ec038d201b0b33d17db599531d3"
SRC_URI += "git://github.com/google/btree.git;name=btree;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/btree"

#   github.com/google/pprof v0.0.0-20210720184732-4bb14d4b1be1
# [1] git ls-remote https://github.com/google/pprof.git 4bb14d4b1be14417e47d0bbaf2bd4e188eda647f
SRCREV_pprof="4bb14d4b1be14417e47d0bbaf2bd4e188eda647f"
SRC_URI += "git://github.com/google/pprof.git;name=pprof;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/pprof"

#   github.com/google/s2a-go v0.1.7
# [1] git ls-remote https://github.com/google/s2a-go.git 141996cc2c0b07d53f1970aa1b2e8e5dde4a7a52
SRCREV_s2a-go="141996cc2c0b07d53f1970aa1b2e8e5dde4a7a52"
SRC_URI += "git://github.com/google/s2a-go.git;name=s2a-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/s2a-go"

#   github.com/google/shlex v0.0.0-20191202100458-e7afc7fbc510
# [1] git ls-remote https://github.com/google/shlex.git e7afc7fbc51079733e9468cdfd1efcd7d196cd1d
SRCREV_shlex="e7afc7fbc51079733e9468cdfd1efcd7d196cd1d"
SRC_URI += "git://github.com/google/shlex.git;name=shlex;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/google/shlex"

#   github.com/googleapis/enterprise-certificate-proxy v0.2.3
# [1] git ls-remote https://github.com/googleapis/enterprise-certificate-proxy.git d0957a96ce28f68cd21ce2742c06237f3fa93fbe
SRCREV_enterprise-certificate-proxy="d0957a96ce28f68cd21ce2742c06237f3fa93fbe"
SRC_URI += "git://github.com/googleapis/enterprise-certificate-proxy.git;name=enterprise-certificate-proxy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/enterprise-certificate-proxy"

#   github.com/googleapis/gax-go/v2 v2.11.0
# [1] git ls-remote https://github.com/googleapis/gax-go.git c594005ac26a7da661e756bc913b08b3b98f5639
SRCREV_gax-go-v2="c594005ac26a7da661e756bc913b08b3b98f5639"
SRC_URI += "git://github.com/googleapis/gax-go.git;name=gax-go-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/gax-go/v2"

#   github.com/gorilla/websocket v1.5.0
# [1] git ls-remote https://github.com/gorilla/websocket.git 9111bb834a68b893cebbbaed5060bdbc1d9ab7d2
SRCREV_websocket="9111bb834a68b893cebbbaed5060bdbc1d9ab7d2"
SRC_URI += "git://github.com/gorilla/websocket.git;name=websocket;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gorilla/websocket"

#   github.com/gregjones/httpcache v0.0.0-20180305231024-9cad4c3443a7
# [1] git ls-remote https://github.com/gregjones/httpcache.git 9cad4c3443a7200dd6400aef47183728de563a38
SRCREV_httpcache="9cad4c3443a7200dd6400aef47183728de563a38"
SRC_URI += "git://github.com/gregjones/httpcache.git;name=httpcache;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/gregjones/httpcache"

#   github.com/grpc-ecosystem/go-grpc-middleware v1.3.0
# [1] git ls-remote https://github.com/grpc-ecosystem/go-grpc-middleware.git df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd
SRCREV_go-grpc-middleware="df0f91b29bbbdfc3a686a7a8edbe2b9de2072fdd"
SRC_URI += "git://github.com/grpc-ecosystem/go-grpc-middleware.git;name=go-grpc-middleware;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/go-grpc-middleware"

#   github.com/grpc-ecosystem/go-grpc-prometheus v1.2.0
# [1] git ls-remote https://github.com/grpc-ecosystem/go-grpc-prometheus.git 502116f1a0a0c1140aab04fd3787489209b357d3
SRCREV_go-grpc-prometheus="502116f1a0a0c1140aab04fd3787489209b357d3"
SRC_URI += "git://github.com/grpc-ecosystem/go-grpc-prometheus.git;name=go-grpc-prometheus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/go-grpc-prometheus"

#   github.com/grpc-ecosystem/grpc-gateway v1.16.0
# [1] git ls-remote https://github.com/grpc-ecosystem/grpc-gateway.git 094a6fe78b3ca888297d090185cdf30f0e42e157
SRCREV_grpc-gateway="094a6fe78b3ca888297d090185cdf30f0e42e157"
SRC_URI += "git://github.com/grpc-ecosystem/grpc-gateway.git;name=grpc-gateway;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/grpc-gateway"

#   github.com/grpc-ecosystem/grpc-gateway/v2 v2.16.0
# [1] git ls-remote https://github.com/grpc-ecosystem/grpc-gateway.git 09e3965a330155f7db8482269d7d91b9bceb7641
SRCREV_grpc-gateway-v2="09e3965a330155f7db8482269d7d91b9bceb7641"
SRC_URI += "git://github.com/grpc-ecosystem/grpc-gateway.git;name=grpc-gateway-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/grpc-ecosystem/grpc-gateway/v2"

#   github.com/imdario/mergo v0.3.6
# [1] git ls-remote https://github.com/darccio/mergo.git 9f23e2d6bd2a77f959b2bf6acdbefd708a83a4a4
SRCREV_mergo="9f23e2d6bd2a77f959b2bf6acdbefd708a83a4a4"
SRC_URI += "git://github.com/darccio/mergo.git;name=mergo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/imdario/mergo"

#   github.com/inconshreveable/mousetrap v1.1.0
# [1] git ls-remote https://github.com/inconshreveable/mousetrap.git 4e8053ee7ef85a6bd26368364a6d27f1641c1d21
SRCREV_mousetrap="4e8053ee7ef85a6bd26368364a6d27f1641c1d21"
SRC_URI += "git://github.com/inconshreveable/mousetrap.git;name=mousetrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/inconshreveable/mousetrap"

#   github.com/jonboulle/clockwork v0.2.2
# [1] git ls-remote https://github.com/jonboulle/clockwork.git b019beee95aca697d4f042c77f9cf2d1af979960
SRCREV_clockwork="b019beee95aca697d4f042c77f9cf2d1af979960"
SRC_URI += "git://github.com/jonboulle/clockwork.git;name=clockwork;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/jonboulle/clockwork"

#   github.com/josharian/intern v1.0.0
# [1] git ls-remote https://github.com/josharian/intern.git 8e6ff32b3e7c0b018c43953085fe2ac330fe9acd
SRCREV_intern="8e6ff32b3e7c0b018c43953085fe2ac330fe9acd"
SRC_URI += "git://github.com/josharian/intern.git;name=intern;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/josharian/intern"

#   github.com/json-iterator/go v1.1.12
# [1] git ls-remote https://github.com/json-iterator/go.git 024077e996b048517130b21ea6bf12aa23055d3d
SRCREV_go="024077e996b048517130b21ea6bf12aa23055d3d"
SRC_URI += "git://github.com/json-iterator/go.git;name=go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/json-iterator/go"

#   github.com/karrick/godirwalk v1.17.0
# [1] git ls-remote https://github.com/karrick/godirwalk.git 11b96caa8cbdc5b729ce8ed1c73125deb448e9d7
SRCREV_godirwalk="11b96caa8cbdc5b729ce8ed1c73125deb448e9d7"
SRC_URI += "git://github.com/karrick/godirwalk.git;name=godirwalk;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/karrick/godirwalk"

#   github.com/liggitt/tabwriter v0.0.0-20181228230101-89fcab3d43de
# [1] git ls-remote https://github.com/liggitt/tabwriter.git 89fcab3d43de07060e4fd4c1547430ed57e87f24
SRCREV_tabwriter="89fcab3d43de07060e4fd4c1547430ed57e87f24"
SRC_URI += "git://github.com/liggitt/tabwriter.git;name=tabwriter;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/liggitt/tabwriter"

#   github.com/mailru/easyjson v0.7.7
# [1] git ls-remote https://github.com/mailru/easyjson.git c120ca7ced6051261161ce15e8f1542a4b2567fc
SRCREV_easyjson="c120ca7ced6051261161ce15e8f1542a4b2567fc"
SRC_URI += "git://github.com/mailru/easyjson.git;name=easyjson;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mailru/easyjson"

#   github.com/matttproud/golang_protobuf_extensions v1.0.4
# [1] git ls-remote https://github.com/matttproud/golang_protobuf_extensions.git c182affec369e30f25d3eb8cd8a478dee585ae7d
SRCREV_golang_protobuf_extensions="c182affec369e30f25d3eb8cd8a478dee585ae7d"
SRC_URI += "git://github.com/matttproud/golang_protobuf_extensions.git;name=golang_protobuf_extensions;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/matttproud/golang_protobuf_extensions"

#   github.com/mistifyio/go-zfs v2.1.2-0.20190413222219-f784269be439+incompatible
# [1] git ls-remote https://github.com/mistifyio/go-zfs.git f784269be439d704d3dfa1906f45dd848fed2beb
SRCREV_go-zfs="f784269be439d704d3dfa1906f45dd848fed2beb"
SRC_URI += "git://github.com/mistifyio/go-zfs.git;name=go-zfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mistifyio/go-zfs"

#   github.com/mitchellh/go-wordwrap v1.0.1
# [1] git ls-remote https://github.com/mitchellh/go-wordwrap.git ecf0936a077a4bd73a1cc2ac5c370f2b55618d62
SRCREV_go-wordwrap="ecf0936a077a4bd73a1cc2ac5c370f2b55618d62"
SRC_URI += "git://github.com/mitchellh/go-wordwrap.git;name=go-wordwrap;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mitchellh/go-wordwrap"

#   github.com/moby/spdystream v0.2.0
# [1] git ls-remote https://github.com/moby/spdystream.git dbc715126c0e3fa07721879c6d265b2b82c71e5b
SRCREV_spdystream="dbc715126c0e3fa07721879c6d265b2b82c71e5b"
SRC_URI += "git://github.com/moby/spdystream.git;name=spdystream;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/spdystream"

#   github.com/moby/sys/mountinfo v0.6.2
# [1] git ls-remote https://github.com/moby/sys.git 1bf36f7188c31f2797c556c4c4d7d9af7a6a965b
SRCREV_mountinfo="1bf36f7188c31f2797c556c4c4d7d9af7a6a965b"
SRC_URI += "git://github.com/moby/sys.git;name=mountinfo;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/sys/mountinfo"

#   github.com/moby/term v0.0.0-20221205130635-1aeaba878587
# [1] git ls-remote https://github.com/moby/term.git 1aeaba8785877a66f57739be9fccb6f5cfab429e
SRCREV_termv0_0_0_20221205130635_1aeaba878587="1aeaba8785877a66f57739be9fccb6f5cfab429e"
SRC_URI += "git://github.com/moby/term.git;name=termv0_0_0_20221205130635_1aeaba878587;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/moby/term"

#   github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
# [1] git ls-remote https://github.com/modern-go/concurrent.git bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94
SRCREV_concurrent="bacd9c7ef1dd9b15be4a9909b8ac7a4e313eec94"
SRC_URI += "git://github.com/modern-go/concurrent.git;name=concurrent;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/concurrent"

#   github.com/modern-go/reflect2 v1.0.2
# [1] git ls-remote https://github.com/modern-go/reflect2.git 2b33151c9bbc5231aea69b8861c540102b087070
SRCREV_reflect2="2b33151c9bbc5231aea69b8861c540102b087070"
SRC_URI += "git://github.com/modern-go/reflect2.git;name=reflect2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/modern-go/reflect2"

#   github.com/mohae/deepcopy v0.0.0-20170603005431-491d3605edfb
# [1] git ls-remote https://github.com/mohae/deepcopy.git 491d3605edfb866af34a48075bd4355ac1bf46ca
SRCREV_deepcopy="491d3605edfb866af34a48075bd4355ac1bf46ca"
SRC_URI += "git://github.com/mohae/deepcopy.git;name=deepcopy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mohae/deepcopy"

#   github.com/monochromegane/go-gitignore v0.0.0-20200626010858-205db1a8cc00
# [1] git ls-remote https://github.com/monochromegane/go-gitignore.git 205db1a8cc001de79230472da52edde4974df734
SRCREV_go-gitignore="205db1a8cc001de79230472da52edde4974df734"
SRC_URI += "git://github.com/monochromegane/go-gitignore.git;name=go-gitignore;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/monochromegane/go-gitignore"

#   github.com/mxk/go-flowrate v0.0.0-20140419014527-cca7078d478f
# [1] git ls-remote https://github.com/mxk/go-flowrate.git cca7078d478f8520f85629ad7c68962d31ed7682
SRCREV_go-flowrate="cca7078d478f8520f85629ad7c68962d31ed7682"
SRC_URI += "git://github.com/mxk/go-flowrate.git;name=go-flowrate;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mxk/go-flowrate"

#   github.com/opencontainers/go-digest v1.0.0
# [1] git ls-remote https://github.com/opencontainers/go-digest.git 4a41a1fddd8208cc64f911e551a7f361716f8ae5
SRCREV_go-digest="4a41a1fddd8208cc64f911e551a7f361716f8ae5"
SRC_URI += "git://github.com/opencontainers/go-digest.git;name=go-digest;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/go-digest"

#   github.com/opencontainers/runtime-spec v1.0.3-0.20220909204839-494a5a6aca78
# [1] git ls-remote https://github.com/opencontainers/runtime-spec.git 494a5a6aca782455c0fbfc35af8e12f04e98a55e
SRCREV_runtime-spec="494a5a6aca782455c0fbfc35af8e12f04e98a55e"
SRC_URI += "git://github.com/opencontainers/runtime-spec.git;name=runtime-spec;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/opencontainers/runtime-spec"

#   github.com/peterbourgon/diskv v2.0.1+incompatible
# [1] git ls-remote https://github.com/peterbourgon/diskv.git 5f041e8faa004a95c88a202771f4cc3e991971e6
SRCREV_diskv="5f041e8faa004a95c88a202771f4cc3e991971e6"
SRC_URI += "git://github.com/peterbourgon/diskv.git;name=diskv;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/peterbourgon/diskv"

#   github.com/pquerna/cachecontrol v0.1.0
# [1] git ls-remote https://github.com/pquerna/cachecontrol.git fb00f8a766ae43bf209f50299ce7d69669416dfb
SRCREV_cachecontrol="fb00f8a766ae43bf209f50299ce7d69669416dfb"
SRC_URI += "git://github.com/pquerna/cachecontrol.git;name=cachecontrol;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/pquerna/cachecontrol"

#   github.com/prometheus/procfs v0.10.1
# [1] git ls-remote https://github.com/prometheus/procfs.git 332e865adfebaa7eaedc94535a3f12f7e5eeb2d4
SRCREV_procfs="332e865adfebaa7eaedc94535a3f12f7e5eeb2d4"
SRC_URI += "git://github.com/prometheus/procfs.git;name=procfs;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/prometheus/procfs"

#   github.com/russross/blackfriday/v2 v2.1.0
# [1] git ls-remote https://github.com/russross/blackfriday.git 4c9bf9512682b995722660a4196c0013228e2049
SRCREV_blackfriday-v2="4c9bf9512682b995722660a4196c0013228e2049"
SRC_URI += "git://github.com/russross/blackfriday.git;name=blackfriday-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/russross/blackfriday/v2"

#   github.com/seccomp/libseccomp-golang v0.10.0
# [1] git ls-remote https://github.com/seccomp/libseccomp-golang.git d1056fed0893f222c3f5c1d8305696fcde6ed332
SRCREV_libseccomp-golang="d1056fed0893f222c3f5c1d8305696fcde6ed332"
SRC_URI += "git://github.com/seccomp/libseccomp-golang.git;name=libseccomp-golang;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/seccomp/libseccomp-golang"

#   github.com/sirupsen/logrus v1.9.0
# [1] git ls-remote https://github.com/sirupsen/logrus.git f8bf7650dccb756cea26edaf9217aab85500fe07
SRCREV_logrus="f8bf7650dccb756cea26edaf9217aab85500fe07"
SRC_URI += "git://github.com/sirupsen/logrus.git;name=logrus;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/sirupsen/logrus"

#   github.com/soheilhy/cmux v0.1.5
# [1] git ls-remote https://github.com/soheilhy/cmux.git 5ec6847320e53b5fee0ab9a4757b56625a946c85
SRCREV_cmux="5ec6847320e53b5fee0ab9a4757b56625a946c85"
SRC_URI += "git://github.com/soheilhy/cmux.git;name=cmux;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/soheilhy/cmux"

#   github.com/stoewer/go-strcase v1.2.0
# [1] git ls-remote https://github.com/stoewer/go-strcase.git 7962b205553802087345c0b4c74d57b65236f676
SRCREV_go-strcase="7962b205553802087345c0b4c74d57b65236f676"
SRC_URI += "git://github.com/stoewer/go-strcase.git;name=go-strcase;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/stoewer/go-strcase"

#   github.com/syndtr/gocapability v0.0.0-20200815063812-42c35b437635
# [1] git ls-remote https://github.com/syndtr/gocapability.git 42c35b4376354fd554efc7ad35e0b7f94e3a0ffb
SRCREV_gocapability="42c35b4376354fd554efc7ad35e0b7f94e3a0ffb"
SRC_URI += "git://github.com/syndtr/gocapability.git;name=gocapability;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/syndtr/gocapability"

#   github.com/tmc/grpc-websocket-proxy v0.0.0-20220101234140-673ab2c3ae75
# [1] git ls-remote https://github.com/tmc/grpc-websocket-proxy.git 673ab2c3ae75cc01952b84b88590e30e75dcf395
SRCREV_grpc-websocket-proxy="673ab2c3ae75cc01952b84b88590e30e75dcf395"
SRC_URI += "git://github.com/tmc/grpc-websocket-proxy.git;name=grpc-websocket-proxy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/tmc/grpc-websocket-proxy"

#   github.com/vishvananda/netns v0.0.4
# [1] git ls-remote https://github.com/vishvananda/netns.git 7a452d2d15292b2bfb2a2d88e6bdeac156a761b9
SRCREV_netns="7a452d2d15292b2bfb2a2d88e6bdeac156a761b9"
SRC_URI += "git://github.com/vishvananda/netns.git;name=netns;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/vishvananda/netns"

#   github.com/x448/float16 v0.8.4
# [1] git ls-remote https://github.com/x448/float16.git cb9afec31f2649663ebb64da5c6c32c3d365c3ca
SRCREV_float16="cb9afec31f2649663ebb64da5c6c32c3d365c3ca"
SRC_URI += "git://github.com/x448/float16.git;name=float16;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/x448/float16"

#   github.com/xiang90/probing v0.0.0-20190116061207-43a291ad63a2
# [1] git ls-remote https://github.com/xiang90/probing.git 43a291ad63a214a207fefbf03c7d9d78b703162b
SRCREV_probing="43a291ad63a214a207fefbf03c7d9d78b703162b"
SRC_URI += "git://github.com/xiang90/probing.git;name=probing;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xiang90/probing"

#   github.com/xlab/treeprint v1.2.0
# [1] git ls-remote https://github.com/xlab/treeprint.git 044005a3b405f660f109e066d9f589755835c2ea
SRCREV_treeprint="044005a3b405f660f109e066d9f589755835c2ea"
SRC_URI += "git://github.com/xlab/treeprint.git;name=treeprint;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/xlab/treeprint"

#   go.etcd.io/bbolt v1.3.8
# [1] git ls-remote https://github.com/etcd-io/bbolt 74bfdc2d62e38b96144d9023561e95247c55c86a
SRCREV_bbolt="74bfdc2d62e38b96144d9023561e95247c55c86a"
SRC_URI += "git://github.com/etcd-io/bbolt;name=bbolt;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/bbolt"

#   go.etcd.io/etcd/client/v2 v2.305.10
# [1] git ls-remote https://github.com/etcd-io/etcd 42159affa1c05f1aa91d9d49b7255f2033f5f8f4
SRCREV_client-v2="42159affa1c05f1aa91d9d49b7255f2033f5f8f4"
SRC_URI += "git://github.com/etcd-io/etcd;name=client-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/client/v2"

#   go.etcd.io/etcd/pkg/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_pkg-v3v3_5_10="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=pkg-v3v3_5_10;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/pkg/v3"

#   go.etcd.io/etcd/raft/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_raft-v3="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=raft-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/raft/v3"

#   go.etcd.io/etcd/server/v3 v3.5.10
# [1] git ls-remote https://github.com/etcd-io/etcd 2825455ca74f606037423ac573347513fdbc7276
SRCREV_server-v3="2825455ca74f606037423ac573347513fdbc7276"
SRC_URI += "git://github.com/etcd-io/etcd;name=server-v3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.etcd.io/etcd/server/v3"

#   go.opencensus.io v0.24.0
# [1] git ls-remote https://github.com/census-instrumentation/opencensus-go b1a01ee95db0e690d91d7193d037447816fae4c5
SRCREV_go.opencensus.io="b1a01ee95db0e690d91d7193d037447816fae4c5"
SRC_URI += "git://github.com/census-instrumentation/opencensus-go;name=go.opencensus.io;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.opencensus.io"

#   go.starlark.net v0.0.0-20230525235612-a134d8f9ddca
# [1] git ls-remote https://github.com/google/starlark-go a134d8f9ddca7469c736775b67544671f0a135ad
SRCREV_go.starlark.net="a134d8f9ddca7469c736775b67544671f0a135ad"
SRC_URI += "git://github.com/google/starlark-go;name=go.starlark.net;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.starlark.net"

#   go.uber.org/multierr v1.11.0
# [1] git ls-remote https://github.com/uber-go/multierr 11a08d20da25289e445ae9b49b75beda94ab2c9b
SRCREV_multierr="11a08d20da25289e445ae9b49b75beda94ab2c9b"
SRC_URI += "git://github.com/uber-go/multierr;name=multierr;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/go.uber.org/multierr"

#   golang.org/x/exp v0.0.0-20220722155223-a9213eeb770e
# [1] git ls-remote https://go.googlesource.com/exp a9213eeb770e134e82907790f9fa16af15091e63
SRCREV_exp="a9213eeb770e134e82907790f9fa16af15091e63"
SRC_URI += "git://go.googlesource.com/exp;name=exp;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/exp"

#   golang.org/x/mod v0.15.0
# [1] git ls-remote https://go.googlesource.com/mod fa1ba4269bda724bb9f01ec381fbbaf031e45833
SRCREV_mod="fa1ba4269bda724bb9f01ec381fbbaf031e45833"
SRC_URI += "git://go.googlesource.com/mod;name=mod;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/mod"

#   golang.org/x/text v0.14.0
# [1] git ls-remote https://go.googlesource.com/text 6c97a165dd661335ff7bce6104a008558123c353
SRCREV_text="6c97a165dd661335ff7bce6104a008558123c353"
SRC_URI += "git://go.googlesource.com/text;name=text;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/golang.org/x/text"

#   google.golang.org/appengine v1.6.7
# [1] git ls-remote https://github.com/golang/appengine 5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a
SRCREV_appengine="5d1c1d03f8703c2e81478d9a30e9afa2d3e4bd8a"
SRC_URI += "git://github.com/golang/appengine;name=appengine;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/appengine"

#   google.golang.org/genproto v0.0.0-20230803162519-f966b187b2e5
# [1] git ls-remote https://github.com/googleapis/go-genproto f966b187b2e5cc15e67ca68e47d6aa17b0cacf55
SRCREV_genproto="f966b187b2e5cc15e67ca68e47d6aa17b0cacf55"
SRC_URI += "git://github.com/googleapis/go-genproto;name=genproto;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto"

#   google.golang.org/genproto/googleapis/api v0.0.0-20230726155614-23370e0ffb3e
# [1] git ls-remote https://github.com/googleapis/go-genproto 23370e0ffb3e8ba4ece5dc4fd27b4ba3f5218f9e
SRCREV_apiv0_0_0_20230726155614_23370e0ffb3e="23370e0ffb3e8ba4ece5dc4fd27b4ba3f5218f9e"
SRC_URI += "git://github.com/googleapis/go-genproto;name=apiv0_0_0_20230726155614_23370e0ffb3e;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/google.golang.org/genproto/googleapis/api"

#   gopkg.in/gcfg.v1 v1.2.3
# [1] git ls-remote https://gopkg.in/gcfg.v1 61b2c08bc8f6068f7c5ca684372f9a6cb1c45ebe
SRCREV_gcfg.v1="61b2c08bc8f6068f7c5ca684372f9a6cb1c45ebe"
SRC_URI += "git://gopkg.in/gcfg.v1;name=gcfg.v1;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/gcfg.v1"

#   gopkg.in/inf.v0 v0.9.1
# [1] git ls-remote https://gopkg.in/inf.v0 d2d2541c53f18d2a059457998ce2876cc8e67cbf
SRCREV_inf.v0="d2d2541c53f18d2a059457998ce2876cc8e67cbf"
SRC_URI += "git://gopkg.in/inf.v0;name=inf.v0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/inf.v0"

#   gopkg.in/natefinch/lumberjack.v2 v2.2.1
# [1] git ls-remote https://gopkg.in/natefinch/lumberjack.v2 4cb27fcfbb0f35cb48c542c5ea80b7c1d18933d0
SRCREV_lumberjack.v2="4cb27fcfbb0f35cb48c542c5ea80b7c1d18933d0"
SRC_URI += "git://gopkg.in/natefinch/lumberjack.v2;name=lumberjack.v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/natefinch/lumberjack.v2"

#   gopkg.in/warnings.v0 v0.1.2
# [1] git ls-remote https://gopkg.in/warnings.v0 ec4a0fea49c7b46c2aeb0b51aac55779c607e52b
SRCREV_warnings.v0="ec4a0fea49c7b46c2aeb0b51aac55779c607e52b"
SRC_URI += "git://gopkg.in/warnings.v0;name=warnings.v0;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/gopkg.in/warnings.v0"

#   k8s.io/gengo/v2 v2.0.0-20240228010128-51d4e06bde70
# [1] git ls-remote https://github.com/kubernetes/gengo 51d4e06bde7070d095fd4c266e51dbe135511a97
SRCREV_gengo-v2="51d4e06bde7070d095fd4c266e51dbe135511a97"
SRC_URI += "git://github.com/kubernetes/gengo;name=gengo-v2;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/k8s.io/gengo/v2"

#   sigs.k8s.io/apiserver-network-proxy/konnectivity-client v0.29.0
# [1] git ls-remote https://github.com/kubernetes-sigs/apiserver-network-proxy 8429e059792fad00b3c9d7ae28ba97bdb461b938
SRCREV_konnectivity-client="8429e059792fad00b3c9d7ae28ba97bdb461b938"
SRC_URI += "git://github.com/kubernetes-sigs/apiserver-network-proxy;name=konnectivity-client;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/apiserver-network-proxy/konnectivity-client"

#   sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd
# [1] git ls-remote https://github.com/kubernetes-sigs/json bc3834ca7abd3a90f03ef00a27ad80cb892f9c21
SRCREV_json="bc3834ca7abd3a90f03ef00a27ad80cb892f9c21"
SRC_URI += "git://github.com/kubernetes-sigs/json;name=json;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/json"

#   sigs.k8s.io/kustomize/api v0.13.5-0.20230601165947-6ce0bf390ce3
# [1] git ls-remote https://github.com/kubernetes-sigs/kustomize 6ce0bf390ce3dae580947a2b739da3306c675eef
SRCREV_apiv0_13_5_0_20230601165947_6ce0bf390ce3="6ce0bf390ce3dae580947a2b739da3306c675eef"
SRC_URI += "git://github.com/kubernetes-sigs/kustomize;name=apiv0_13_5_0_20230601165947_6ce0bf390ce3;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/kustomize/api"

#   sigs.k8s.io/kustomize/kustomize/v5 v5.0.4-0.20230601165947-6ce0bf390ce3
# [1] git ls-remote https://github.com/kubernetes-sigs/kustomize 6ce0bf390ce3dae580947a2b739da3306c675eef
SRCREV_kustomize-v5="6ce0bf390ce3dae580947a2b739da3306c675eef"
SRC_URI += "git://github.com/kubernetes-sigs/kustomize;name=kustomize-v5;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/kustomize/kustomize/v5"

#   sigs.k8s.io/kustomize/kyaml v0.14.3-0.20230601165947-6ce0bf390ce3
# [1] git ls-remote https://github.com/kubernetes-sigs/kustomize 6ce0bf390ce3dae580947a2b739da3306c675eef
SRCREV_kyaml="6ce0bf390ce3dae580947a2b739da3306c675eef"
SRC_URI += "git://github.com/kubernetes-sigs/kustomize;name=kyaml;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/sigs.k8s.io/kustomize/kyaml"

SRCREV_speakeasy="4aabc24848ce5fd31929f7d1e4ea74d3709c14cd"
SRC_URI += "git://github.com/bgentry/speakeasy;name=speakeasy;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/bgentry/speakeasy"

SRCREV_tablewriter="c7d2a8a09b076b70918308a3cd95464b2ae3b5d8"
SRC_URI += "git://github.com/olekukonko/tablewriter;name=tablewriter;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/olekukonko/tablewriter"

SRCREV_runewidth="44b7c5b4d67df8ca22917b6800c158a6d3be3560"
SRC_URI += "git://github.com/mattn/go-runewidth;name=runewidth;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/mattn/go-runewidth"

SRCREV_uniseg="03509a98a092b522b2ff0de13e53513d18b3b837"
SRC_URI += "git://github.com/rivo/uniseg;name=uniseg;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/rivo/uniseg"

SRCREV_pb="f907f6f5dd81f77c2bbc1cde92e4c5a04720cb11"
SRC_URI += "git://github.com/cheggaaa/pb;name=pb;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/cheggaaa/pb"

SRCREV_gax-go="bd5b16380fd03dc758d11cef74ba2e3bc8b0e8c2"
SRC_URI += "git://github.com/googleapis/gax-go;name=gax-go;protocol=https;nobranch=1;destsuffix=${WORKDIR}/${BP}/src/import/vendor.fetch/github.com/googleapis/gax-go"
