# We have a conf and classes directory, add to BBPATH
BBPATH := "${BBPATH}:${LAYERDIR}"

# We have a recipes directory, add to BBFILES
BBFILES := "${BBFILES} ${LAYERDIR}/recipes-*/*/*.bb \
	    ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "netfield-oem"
BBFILE_PATTERN_netfield-oem := "^${LAYERDIR}/"
BBFILE_PRIORITY_netfield-oem = "100"

LAYERSERIES_COMPAT_netfield-oem = "dunfell"

# Mask old-brandings when meta-oem is used
BBMASK += "meta-netfield/dynamic-layers/meta-freescale/recipes-old-branding/"

